In [2]:
import os
os.environ["TRANSFORMERS_NO_TF"] = "1"

In [3]:
from generate_subqueries_agent import run_generate_subqueries_agent
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, SystemMessagePromptTemplate
from langchain_core.messages import HumanMessage
from multi_agent import llm
from pydantic import BaseModel

In [4]:
class GradeSubQuery(BaseModel):
    score: int

In [5]:
llm_grade = llm.with_structured_output(GradeSubQuery)
def run_test(query: str):
    sub_queries = run_generate_subqueries_agent({"messages": [HumanMessage(content=query)]})
    system_prompt = """
    Bạn là một giám kháo chấm điểm độ liên quan của các truy vấn con đối với truy vấn chính. 
    Điểm số từ 1 đến 10, trong đó 10 là rất liên quan và 1 là không liên quan.
    Yêu cầu: Đánh giá một cách gắt gao, công tâm và chính xác.
    """
    prompt = ChatPromptTemplate.from_messages([
        SystemMessagePromptTemplate.from_template(system_prompt),
        HumanMessagePromptTemplate.from_template(
            "Query chính: {query}\n"
            "Query phụ: {sub_query}\n"
        )
    ])
    llm_judge = prompt | llm_grade
    scores = []
    for sub_query in sub_queries[1:]:
        response = llm_judge.invoke({"query": query, "sub_query": sub_query})
        scores.append(response.score)
    print(f"Query: {query}")
    average_score = sum(scores) / len(scores) if scores else 0
    print(f"Average scores: {average_score}")
    return sub_queries, average_score

In [6]:
run_test("Giải thích Quốc Hội Việt Nam là gì?")

Query: Giải thích Quốc Hội Việt Nam là gì?
Average scores: 9.8

(['Giải thích Quốc Hội Việt Nam là gì?',
  'Quốc hội Việt Nam được quy định tại văn bản pháp luật nào?',
  'Quốc hội Việt Nam là cơ quan gì, có vị trí, vai trò và chức năng, nhiệm vụ chính nào trong hệ thống chính trị Việt Nam?',
  'Cơ cấu tổ chức của Quốc hội Việt Nam bao gồm những thành phần nào và nhiệm kỳ của Quốc hội là bao lâu?',
  'Quốc hội Việt Nam có những quyền hạn và nhiệm vụ cụ thể nào trong việc lập hiến, lập pháp, quyết định các vấn đề quan trọng của đất nước và giám sát tối cao?',
  'Đại biểu Quốc hội được bầu cử theo nguyên tắc và quy định nào?'],
 9.8)

In [ ]:
import pandas as pd
data = pd.read_csv("E:\Downloads\projectcongty\Dataset\sent_truncated_dvc_train.csv", encoding='utf-16')
data = data.sample(frac=1, random_state=42)

In [ ]:
print(questions_test[2])

In [ ]:
questions = data["noi_dung_hoi"].tolist()
scores_test = []
sub_queries_list = []
questions_test = questions[:20]
for query in questions_test:
    sub_queries, score = run_test(query)
    sub_queries_list.append(sub_queries)
    scores_test.append(score)
    print("-----")

average_test_score = sum(scores_test) / len(scores_test) if scores_test else 0
print(f"Average test scores: {average_test_score}")
#lưu sub_queries_list và questions_test vào file để dùng sau
import pickle
with open("sub_queries_list.pkl", "wb") as f:
    pickle.dump(sub_queries_list, f)
with open("questions_test.pkl", "wb") as f:
    pickle.dump(questions_test, f)

In [ ]:
import os
import sys
import transformers.utils.import_utils

# Patch: Đánh lừa transformers rằng TensorFlow không tồn tại
# Cách này tránh lỗi "DLL load failed" và lỗi "None in sys.modules"
os.environ["TRANSFORMERS_NO_TF"] = "1"
transformers.utils.import_utils._tf_available = False

#compute cosine similarity between two vectors
from sklearn.metrics.pairwise import cosine_similarity
def compute_cosine_similarity(vec1, vec2):
    return cosine_similarity([vec1], [vec2])[0][0]

PATH_TO_EMBEDDING = "intfloat/multilingual-e5-large"
from sentence_transformers import SentenceTransformer
# Thêm trust_remote_code=True vì model này yêu cầu code custom
embedder = SentenceTransformer(PATH_TO_EMBEDDING, trust_remote_code=True)
def get_embedding(text: str):
    embedding = embedder.encode(text)
    return embedding
# Example usage
vec1 = get_embedding("This is a sample sentence.")
print(vec1)

In [ ]:
print(get_similarity(questions_test[1], sub_queries_list[1][3]))

0.8883544

In [ ]:
def get_similarity(main_query: str, sub_query:str):
    similarity = compute_cosine_similarity(get_embedding(main_query), get_embedding(sub_query))
    return similarity
def get_average_similary(main_query: str, sub_queries: list[str]):
    similarities = [get_similarity(main_query, sub_query) for sub_query in sub_queries[1:]]
    average_similarity = sum(similarities) / len(similarities) if similarities else 0
    return average_similarity
similarities_test = []
for query, sub_queries in zip(questions_test,sub_queries_list):
    avg_sim = get_average_similary(query, sub_queries)
    similarities_test.append(avg_sim)
    print(f"Query: {query}")
    print(f"Average similarity: {avg_sim}")
    print("-----")
print(f"Average similarity on test set: {sum(similarities_test)/len(similarities_test)}")

Query: Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?
Average similarity: 0.9307035207748413
-----
Query: Xin cho hỏi thời hạn thanh toán trực tiếp chi phí khám, chữa bệnh bảo hiểm y tế tại cơ quan bảo hiểm xã hội là bao lâu?
Average similarity: 0.90125572681427
-----
Query: Thời điểm lập Hồ sơ cấp giấy phép của các công trình thuộc đối tượng lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan trong khai thác, sử dụng tài nguyên nước sau khi quyết định việc đầu tư thì việc lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan tiến hành như thế nào và có cần phải công khai thông tin về những nội dung liên quan đến khai thác, sử dụng tài nguyên nước theo quy định?
Average similarity: 0.9208710789680481
-----
Query: Trong trường hợp nào thì khai thác khoáng sản làm vật liệu xây dựng thông thường thông thường không phải xin giấy phép khai thác?
Average similarity: 0.8974435925483704
-----
Query: Hồ sơ đề nghị góp ý đối với hồ sơ thiết kế cơ sở gồm những thành phần gì?
Average similarity: 0.9204072952270508
-----
Query: Khi nộp hồ sơ đăng ký hoạt động chi nhánh, văn phòng đại diện thuộc ngân hàng thương mại, tôi được yêu cầu nộp bổ sung Nghị quyết của Đại hội đồng cổ đông về việc thành lập chi nhánh, văn phòng đại diện. Xin hỏi, yêu cầu này có đúng với quy định pháp luật hiện hành hay không?
Average similarity: 0.8831451535224915
-----
Query: Hồ sơ đề nghị đổi thẻ nhà báo gồm những gì?
Average similarity: 0.9318076372146606
-----
Query: Cơ quan Hải quan hay người khai hải quan có trách nhiệm tổ chức tham vấn trị giá hải quan?
Average similarity: 0.9338504076004028
-----
Query: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Average similarity: 0.9216631650924683
-----
Query: Tiền lương đóng bảo hiểm vào quỹ bảo hiểm tai nạn lao động, bệnh nghề nghiệp làm căn cứ tính hưởng chế độ tai nạn lao động được quy định như thế nào?
Average similarity: 0.9479564428329468
-----
Query: Đề nghị làm rõ việc đánh dấu mẫu vật bằng “vật liệu khác” quy định tại khoản 2 Điều 34 Thông tư số 27/2018/TT-BNNPTNT là gì?
Average similarity: 0.9307200312614441
-----
Query: Trong trường hợp tôi đã có văn bản làm căn cứ yêu cầu bồi thường và muốn yêu cầu cơ quan trực tiếp quản lý người thi hành công vụ gây thiệt hại bồi thường nhưng tôi không biết phải gửi hồ sơ yêu cầu bồi thường đến cơ quan nào thì tôi có thể đề nghị cơ quan nào xác định cơ quan giải quyết bồi thường giúp tôi?
Average similarity: 0.8893033266067505
-----
Query: Công ty tôi có nhu cầu xin cấp giấy phép bưu chính, vậy cho chúng tôi hỏi giấy phép bưu chính có thời hạn tối đa bao nhiêu năm?
Average similarity: 0.8896676301956177
-----
Query: Năm tính thuế của nước cư trú của Tôi là từ ngày 01/4 đến ngày 31/3 năm sau, theo đó, Tôi sẽ không có được Giấy chứng nhận cư trú cho năm 2018 tại thời điểm nộp hồ sơ Thông báo áp dụng Hiệp định (vào tháng 3/2018). Với trường hợp của Tôi thì được giải quyết như thế nào?
Average similarity: 0.8642820119857788
-----
Query: Theo quy định tại Khoản 3 Điều 16 Nghị định số 201/2013/NĐ-CP ngày 27/11/2013 của Chính phủ quy định chi tiết thi hành một số điều của Luật tài nguyên nước thì “xả nước thải của cá nhân, hộ gia đình thuộc trường hợp không phải xin cấp phép xả nước thải vào nguồn nước” và “xả nước thải của các cơ sở, sản xuất, kinh doanh dịch vụ với quy mô từ 05 m3/ngày đêm trở lên thuộc đối tượng phải cấp phép xả nước thải”. Tuy nhiên, phần hệ thống công trình hạ tầng kỹ thuật về xử lý, xả nước thải của khu căn hộ và dịch vụ thương mại không được tách riêng. Như vậy các Dự án tổ hợp thương mại, dịch vụ, căn hộ và chung cư có thuộc đối tượng phải xin cấp phép không?
Average similarity: 0.8976716995239258
-----
Query: Tôi muốn biết sau bao lâu tôi sẽ được gia hạn hiệu lực VBBH?
Average similarity: 0.8750717043876648
-----
Query: Điều kiện cấp Giấy chứng nhận đủ điều kiện hoạt động kiểm định kỹ thuật an toàn lao động đối với tổ chức gồm những gì?
Average similarity: 0.9142118692398071
-----
Query: Thành phần hồ sơ và trách nhiệm lập hồ sơ đối với thương binh đang công tác trong Quân đội đề nghị giám định bổ sung vết thương còn sót?
Average similarity: 0.9144388437271118
-----
Query: Ngân hàng Nhà nước Chi nhánh tỉnh thành phố có tiếp nhận và xử lý hồ sơ đăng ký khoản cho vay ra nước ngoài của tổ chức kinh tế trên địa bàn không?
Average similarity: 0.8854734301567078
-----
Query: Công ty của chúng  tôi mới được  cấp giấy chứng nhận đủ điều kiện  huấn luyện an toàn, vệ sinh lao động hạng B. Nay do Công ty chúng tôi thay đổi tên Công ty nên Công ty đã nộp hồ sơ đề nghị đổi tên Công ty trong giấy chứng nhận đủ điều kiện huấn luyện an toàn, vệ sinh lao động, vậy sau bao nhiêu ngày chúng tôi có thể nhận được giấy chứng nhận đổi tên?
Average similarity: 0.9072970151901245
-----
Average similarity on test set: 0.9078620076179504

In [22]:
pip install deepeval

Collecting deepeval
  Downloading deepeval-3.7.6-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: aiohttp in e:\downloads\app\python\lib\site-packages (from deepeval) (3.12.15)
Collecting click<8.3.0,>=8.0.0 (from deepeval)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: grpcio<2.0.0,>=1.67.1 in e:\downloads\app\python\lib\site-packages (from deepeval) (1.75.1)
Requirement already satisfied: jinja2 in e:\downloads\app\python\lib\site-packages (from deepeval) (3.1.6)
Requirement already satisfied: nest_asyncio in c:\users\trieu kinh quoc\appdata\roaming\python\python313\site-packages (from deepeval) (1.6.0)
Collecting openai (from deepeval)
  Downloading openai-2.14.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.24.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (1.38.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.24.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<2.0.0,>=1.24.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (1.38.0)
Collecting portalocker (from deepeval)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: posthog<6.0.0,>=5.4.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (5.4.0)
Requirement already satisfied: pydantic<3.0.0,>=2.11.7 in e:\downloads\app\python\lib\site-packages (from deepeval) (2.11.9)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in e:\downloads\app\python\lib\site-packages (from deepeval) (2.11.0)
Collecting pyfiglet (from deepeval)
  Downloading pyfiglet-1.0.4-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pytest in e:\downloads\app\python\lib\site-packages (from deepeval) (8.4.2)
Collecting pytest-asyncio (from deepeval)
  Downloading pytest_asyncio-1.3.0-py3-none-any.whl.metadata (4.1 kB)
Collecting pytest-repeat (from deepeval)
  Downloading pytest_repeat-0.9.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: pytest-rerunfailures in e:\downloads\app\python\lib\site-packages (from deepeval) (16.1)
Requirement already satisfied: pytest-xdist in e:\downloads\app\python\lib\site-packages (from deepeval) (3.8.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.1.1 in e:\downloads\app\python\lib\site-packages (from deepeval) (1.1.1)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (2.32.5)
Requirement already satisfied: rich<15.0.0,>=13.6.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (14.2.0)
Collecting sentry-sdk (from deepeval)
  Downloading sentry_sdk-2.48.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools in e:\downloads\app\python\lib\site-packages (from deepeval) (80.9.0)
Collecting tabulate<0.10.0,>=0.9.0 (from deepeval)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: tenacity<=10.0.0,>=8.0.0 in e:\downloads\app\python\lib\site-packages (from deepeval) (9.1.2)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in e:\downloads\app\python\lib\site-packages (from deepeval) (4.67.1)
Requirement already satisfied: typer<1.0.0,>=0.9 in e:\downloads\app\python\lib\site-packages (from deepeval) (0.20.0)
Requirement already satisfied: wheel in e:\downloads\app\python\lib\site-packages (from deepeval) (0.45.1)
Requirement already satisfied: colorama in c:\users\trieu kinh quoc\appdata\roaming\python\python313\site-packages (from click<8.3.0,>=8.0.0->deepeval) (0.4.6)
Requirement already satisfied: typing-extensions~=4.12 in e:\downloads\app\python\lib\site-packages (from grpcio<2.0.0,>=1.67.1->deepeval) (4.15.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in e:\downloads\app\python\lib\site-packages (from opentelemetry-api<2.0.0,>=1.24.0->deepeval) (8.7.0)
Requirement already satisfied: zipp>=3.20 in e:\downloads\app\python\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<2.0.0,>=1.24.0->deepeval) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in e:\downloads\app\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.24.0->deepeval) (1.70.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.38.0 in e:\downloads\app\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.24.0->deepeval) (1.38.0)
Requirement already satisfied: opentelemetry-proto==1.38.0 in e:\downloads\app\python\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.24.0->deepeval) (1.38.0)
Requirement already satisfied: protobuf<7.0,>=5.0 in e:\downloads\app\python\lib\site-packages (from opentelemetry-proto==1.38.0->opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.24.0->deepeval) (5.29.5)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in e:\downloads\app\python\lib\site-packages (from opentelemetry-sdk<2.0.0,>=1.24.0->deepeval) (0.59b0)
Requirement already satisfied: six>=1.5 in e:\downloads\app\python\lib\site-packages (from posthog<6.0.0,>=5.4.0->deepeval) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in e:\downloads\app\python\lib\site-packages (from posthog<6.0.0,>=5.4.0->deepeval) (2.9.0.post0)
Requirement already satisfied: backoff>=1.10.0 in e:\downloads\app\python\lib\site-packages (from posthog<6.0.0,>=5.4.0->deepeval) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in e:\downloads\app\python\lib\site-packages (from posthog<6.0.0,>=5.4.0->deepeval) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in e:\downloads\app\python\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in e:\downloads\app\python\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in e:\downloads\app\python\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in e:\downloads\app\python\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in e:\downloads\app\python\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\downloads\app\python\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\downloads\app\python\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (2025.10.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\downloads\app\python\lib\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\trieu kinh quoc\appdata\roaming\python\python313\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (2.19.2)
Requirement already satisfied: shellingham>=1.3.0 in e:\downloads\app\python\lib\site-packages (from typer<1.0.0,>=0.9->deepeval) (1.5.4)
Requirement already satisfied: mdurl~=0.1 in e:\downloads\app\python\lib\site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.6.0->deepeval) (0.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in e:\downloads\app\python\lib\site-packages (from aiohttp->deepeval) (1.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in e:\downloads\app\python\lib\site-packages (from jinja2->deepeval) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in e:\downloads\app\python\lib\site-packages (from openai->deepeval) (4.11.0)
Requirement already satisfied: httpx<1,>=0.23.0 in e:\downloads\app\python\lib\site-packages (from openai->deepeval) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai->deepeval)
  Downloading jiter-0.12.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: sniffio in e:\downloads\app\python\lib\site-packages (from openai->deepeval) (1.3.1)
Requirement already satisfied: httpcore==1.* in e:\downloads\app\python\lib\site-packages (from httpx<1,>=0.23.0->openai->deepeval) (1.0.9)
Requirement already satisfied: h11>=0.16 in e:\downloads\app\python\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->deepeval) (0.16.0)
Requirement already satisfied: pywin32>=226 in c:\users\trieu kinh quoc\appdata\roaming\python\python313\site-packages (from portalocker->deepeval) (311)
Requirement already satisfied: iniconfig>=1 in e:\downloads\app\python\lib\site-packages (from pytest->deepeval) (2.3.0)
Requirement already satisfied: packaging>=20 in c:\users\trieu kinh quoc\appdata\roaming\python\python313\site-packages (from pytest->deepeval) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in e:\downloads\app\python\lib\site-packages (from pytest->deepeval) (1.6.0)
Requirement already satisfied: execnet>=2.1 in e:\downloads\app\python\lib\site-packages (from pytest-xdist->deepeval) (2.1.1)
Downloading deepeval-3.7.6-py3-none-any.whl (794 kB)
   ---------------------------------------- 0.0/794.9 kB ? eta -:--:--
   ------------- -------------------------- 262.1/794.9 kB ? eta -:--:--
   ---------------------------------------- 794.9/794.9 kB 5.0 MB/s  0:00:00
Downloading click-8.2.1-py3-none-any.whl (102 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading openai-2.14.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 8.6 MB/s  0:00:00
Downloading jiter-0.12.0-cp313-cp313-win_amd64.whl (204 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Downloading pyfiglet-1.0.4-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 10.9 MB/s  0:00:00
Downloading pytest_asyncio-1.3.0-py3-none-any.whl (15 kB)
Downloading pytest_repeat-0.9.4-py3-none-any.whl (4.2 kB)
Downloading sentry_sdk-2.48.0-py2.py3-none-any.whl (414 kB)
Installing collected packages: tabulate, sentry-sdk, pyfiglet, portalocker, jiter, click, pytest-repeat, pytest-asyncio, openai, deepeval

   ----------------------------------------  0/10 [tabulate]
   ----------------------------------------  0/10 [tabulate]
   ----------------------------------------  0/10 [tabulate]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   ---- -----------------------------------  1/10 [sentry-sdk]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   -------- -------------------------------  2/10 [pyfiglet]
   ------------ ---------------------------  3/10 [portalocker]
   ------------ ---------------------------  3/10 [portalocker]
   ---------------- -----------------------  4/10 [jiter]
  Attempting uninstall: click
   ---------------- -----------------------  4/10 [jiter]
    Found existing installation: click 8.3.0
   ---------------- -----------------------  4/10 [jiter]
   -------------------- -------------------  5/10 [click]
    Uninstalling click-8.3.0:
   -------------------- -------------------  5/10 [click]
      Successfully uninstalled click-8.3.0
   -------------------- -------------------  5/10 [click]
   -------------------- -------------------  5/10 [click]
   -------------------- -------------------  5/10 [click]
   -------------------- -------------------  5/10 [click]
   -------------------- -------------------  5/10 [click]
   -------------------- -------------------  5/10 [click]
   ------------------------ ---------------  6/10 [pytest-repeat]
   ---------------------------- -----------  7/10 [pytest-asyncio]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]
   -------------------------------- -------  8/10 [openai]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [18]:
from dotenv import load_dotenv
load_dotenv("E:\Downloads\projectcongty\.env")

True

In [25]:
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.models.base_model import DeepEvalBaseLLM
from multi_agent import llm  # Import LLM Gemini của bạn

# 1. Tạo Wrapper cho Custom LLM (Gemini)
class GoogleGeminiWrapper(DeepEvalBaseLLM):
    def __init__(self, model):
        self.model = model

    def load_model(self):
        return self.model

    def generate(self, prompt: str) -> str:
        # DeepEval gửi prompt dưới dạng string, ta gọi invoke của LangChain
        response = self.model.invoke(prompt)
        return response.content

    async def a_generate(self, prompt: str) -> str:
        # Hỗ trợ async nếu cần
        response = await self.model.ainvoke(prompt)
        return response.content

    def get_model_name(self):
        return "gemini-2.5-flash"

# Khởi tạo wrapper
custom_gemini = GoogleGeminiWrapper(llm)

# 2. Định nghĩa Metric GEval cho Query Coverage
# Tiêu chí: Các sub-queries có bao phủ đầy đủ các khía cạnh của câu hỏi gốc không?
query_coverage_metric = GEval(
    name="Query Coverage",
    criteria="Determine whether the generated sub-queries cover all necessary aspects and intents of the original query to ensure a comprehensive search.",
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],
    model=custom_gemini, # Sử dụng LLM của bạn làm giám khảo
    threshold=0.7
)

# 3. Chạy đánh giá trên tập test
print("--- Bắt đầu đánh giá Query Coverage bằng GEval ---")
geval_scores = []

# Chạy thử trên 5 mẫu đầu tiên để tiết kiệm thời gian
for i, (original_query, sub_queries) in enumerate(zip(questions_test[:], sub_queries_list[:])):
    
    # Chuyển list sub-queries thành string để đưa vào actual_output
    # Lưu ý: actual_output thường là câu trả lời, nhưng ở đây ta đang đánh giá output của agent sinh query
    sub_queries_str = "\n".join(sub_queries)
    
    test_case = LLMTestCase(
        input=original_query,
        actual_output=sub_queries_str,
        expected_output="" # Không cần thiết cho GEval nếu tiêu chí không yêu cầu so sánh
    )
    
    # Thực hiện đo lường
    query_coverage_metric.measure(test_case)
    
    print(f"Query {i+1}: {original_query}")
    print(f"Score: {query_coverage_metric.score}")
    print(f"Reason: {query_coverage_metric.reason}")
    print("-" * 30)
    
    geval_scores.append(query_coverage_metric.score)

if geval_scores:
    print(f"Average Query Coverage Score: {sum(geval_scores) / len(geval_scores)}")

--- Bắt đầu đánh giá Query Coverage bằng GEval ---

Query 1: Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?
Score: 1.0
Reason: The Actual Output comprehensively addresses the Input's primary intent of understanding 'how to prepare the dossier for pre-determining the code'. While the Input specifically asks about dossier preparation, the 'như thế nào?' (how?) implies a need for broader procedural information. The sub-queries effectively break down this 'how' into essential components: conditions, specific documents, overall procedure, responsible authority, and practical details like processing time and cost. This collective set of sub-queries fully represents the Input's search requirements, ensuring no critical components related to the process are missed.
------------------------------

Query 2: Xin cho hỏi thời hạn thanh toán trực tiếp chi phí khám, chữa bệnh bảo hiểm y tế tại cơ quan bảo hiểm xã hội là bao lâu?
Score: 0.9
Reason: The response directly addresses the input's primary intent by including the original query verbatim as the first sub-query. It further enhances the coverage of the 'thời hạn' (time limit) aspect with a specific sub-query about 'thời hạn nộp hồ sơ và thời hạn giải quyết'. While the output includes additional sub-queries about conditions, documents, procedures, and competent authority that were not explicitly requested in the input, these are highly relevant to the overall process of direct payment of health insurance costs and do not miss any critical components of the original search requirement.
------------------------------

Query 3: Thời điểm lập Hồ sơ cấp giấy phép của các công trình thuộc đối tượng lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan trong khai thác, sử dụng tài nguyên nước sau khi quyết định việc đầu tư thì việc lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan tiến hành như thế nào và có cần phải công khai thông tin về những nội dung liên quan đến khai thác, sử dụng tài nguyên nước theo quy định?
Score: 1.0
Reason: The actual output comprehensively addresses all key aspects and primary intents identified in the input. It breaks down the complex original query regarding the 'how' and 'public disclosure' of community consultation for water resource projects into specific, actionable sub-queries. These sub-queries cover the conditions for consultation, the required documentation, the procedures, the responsible authorities, and the specific timing for both consultation and public disclosure, thereby fully representing the input's search requirements.
------------------------------

Query 4: Trong trường hợp nào thì khai thác khoáng sản làm vật liệu xây dựng thông thường thông thường không phải xin giấy phép khai thác?
Score: 0.9
Reason: The Actual Output successfully identifies and directly addresses the primary intent of the Input query regarding the circumstances under which a mining license is not required for ordinary construction materials. The first two sub-queries directly rephrase this core question. Furthermore, the output provides a comprehensive set of related sub-queries that anticipate follow-up questions, covering definitions, procedures, authority, and penalties, which enhances the overall utility without missing any critical components of the original search requirement.
------------------------------

Query 5: Hồ sơ đề nghị góp ý đối với hồ sơ thiết kế cơ sở gồm những thành phần gì?
Score: 0.9
Reason: The response successfully identifies and addresses the primary intent of the input, which is to inquire about the 'thành phần' (components) of the dossier. It includes two sub-queries directly asking about the components, ensuring this critical aspect from the input is fully covered and not missed. Additionally, the response provides a comprehensive set of highly relevant sub-queries covering conditions, procedures, competent authorities, and deadlines, which, while expanding beyond the input's explicit scope, offer a valuable and holistic search strategy related to the initial query. The only minor shortcoming is the slight redundancy of having two very similar sub-queries for 'thành phần'.
------------------------------

Query 6: Khi nộp hồ sơ đăng ký hoạt động chi nhánh, văn phòng đại diện thuộc ngân hàng thương mại, tôi được yêu cầu nộp bổ sung Nghị quyết của Đại hội đồng cổ đông về việc thành lập chi nhánh, văn phòng đại diện. Xin hỏi, yêu cầu này có đúng với quy định pháp luật hiện hành hay không?
Score: 0.8
Reason: The actual output successfully identifies and addresses the primary intent of the input, which is to determine the legal correctness of requiring a Shareholders' General Meeting Resolution for branch/representative office registration. Specifically, the sub-query 'Hồ sơ đăng ký hoạt động chi nhánh, văn phòng đại diện ngân hàng thương mại có yêu cầu Nghị quyết của Đại hội đồng cổ đông không?' directly targets this core question. Additionally, it provides a comprehensive set of related sub-queries covering conditions, procedures, authority, and timelines, which are relevant to the overall context of the input. However, the first sub-query is a direct repetition of the entire input, which is redundant and not a distinct breakdown of the original query.
------------------------------

Query 7: Hồ sơ đề nghị đổi thẻ nhà báo gồm những gì?
Score: 0.9
Reason: The Actual Output effectively identifies and addresses the primary intent of the Input, which is to inquire about the contents of the application dossier for journalist card renewal. The sub-queries 'Hồ sơ đề nghị đổi thẻ nhà báo gồm những gì?' and 'Hồ sơ đề nghị đổi thẻ nhà báo bao gồm những giấy tờ gì?' directly cover this specific requirement, ensuring no critical components of the original query are missed. However, the output also includes several additional sub-queries (conditions, procedures, authority, time, fees) that, while related to the overall process of journalist card renewal, go beyond the very specific scope of the Input's question about the 'hồ sơ' (dossier) contents. While helpful, this expansion slightly deviates from a strict interpretation of 'fully represent the Input's search requirements' if interpreted as 'only represent'.
------------------------------

Query 8: Cơ quan Hải quan hay người khai hải quan có trách nhiệm tổ chức tham vấn trị giá hải quan?
Score: 0.7
Reason: The Actual Output successfully identifies and includes the primary intent of the Input, with sub-queries 1, 3, and 5 directly addressing the 'who is responsible/has authority' aspect. However, it introduces several new intents and aspects, such as 'conditions,' 'procedures,' and 'obligations of the declarant' (sub-queries 2, 4, and 6), which were not explicitly part of the original, highly specific 'who is responsible' query. While it covers the original intent, it expands significantly beyond the Input's specific search requirements.
------------------------------

Query 9: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Score: 0.9
Reason: The output strongly aligns with the evaluation steps by directly addressing the input's primary intent regarding the contents of the customs valuation dossier. Sub-queries 1 and 3 explicitly cover this requirement, ensuring no critical components from the input are missed. However, the output includes a redundant sub-query and expands significantly beyond the original input's narrow scope by introducing additional, albeit related, aspects such as cases, procedures, authority, and time limits.
------------------------------

Query 10: Tiền lương đóng bảo hiểm vào quỹ bảo hiểm tai nạn lao động, bệnh nghề nghiệp làm căn cứ tính hưởng chế độ tai nạn lao động được quy định như thế nào?
Score: 0.9
Reason: The response effectively breaks down the input query into a comprehensive set of sub-queries. It directly addresses the core intent regarding 'Tiền lương đóng bảo hiểm... làm căn cứ tính hưởng chế độ tai nạn lao động được quy định như thế nào?' by including a direct rephrasing and then elaborating on key aspects such as the components of the salary (sub-query 3), the procedures for determination (sub-query 4), and the calculation of benefits based on it (sub-query 6). It also includes relevant contextual aspects like the subjects involved (sub-query 2) and the competent authority (sub-query 5), ensuring a thorough representation of the input's search requirements. The only minor point is the first sub-query is a direct restatement of the input, which is slightly redundant if the goal is purely to *break down* the original query, but it doesn't detract from the overall comprehensiveness.
------------------------------

Query 11: Đề nghị làm rõ việc đánh dấu mẫu vật bằng “vật liệu khác” quy định tại khoản 2 Điều 34 Thông tư số 27/2018/TT-BNNPTNT là gì?
Score: 1.0
Reason: The Actual Output successfully identifies the key aspect of 'đánh dấu mẫu vật bằng “vật liệu khác”' and the specific legal reference from the Input. It then generates a comprehensive set of sub-queries that collectively address the primary intent of 'làm rõ ... là gì?' by breaking it down into relevant components such as conditions, documentation, procedures, authority, and legal consequences, ensuring no critical components are missed for a full clarification.
------------------------------

Query 12: Trong trường hợp tôi đã có văn bản làm căn cứ yêu cầu bồi thường và muốn yêu cầu cơ quan trực tiếp quản lý người thi hành công vụ gây thiệt hại bồi thường nhưng tôi không biết phải gửi hồ sơ yêu cầu bồi thường đến cơ quan nào thì tôi có thể đề nghị cơ quan nào xác định cơ quan giải quyết bồi thường giúp tôi?
Score: 1.0
Reason: The Actual Output effectively identifies and addresses all key aspects and the primary intent of the Input. The initial sub-query directly restates the user's core question, while subsequent sub-queries comprehensively cover related procedural details such as conditions, required documents, process, competent authority, and associated timelines and costs for identifying the compensation-resolving agency. This provides a thorough and complete set of information relevant to the user's complex query.
------------------------------

Query 13: Công ty tôi có nhu cầu xin cấp giấy phép bưu chính, vậy cho chúng tôi hỏi giấy phép bưu chính có thời hạn tối đa bao nhiêu năm?
Score: 1.0
Reason: The response successfully identifies the user's explicit question about the maximum duration of a postal license and the broader context of applying for such a license. It provides a comprehensive set of sub-queries that address both the specific question ('Thời hạn tối đa của giấy phép bưu chính là bao nhiêu năm?') and the implied needs related to the application process (conditions, documents, procedures, and authority). All key aspects and primary intents from the input are covered, and no critical components are missed.
------------------------------

Query 14: Năm tính thuế của nước cư trú của Tôi là từ ngày 01/4 đến ngày 31/3 năm sau, theo đó, Tôi sẽ không có được Giấy chứng nhận cư trú cho năm 2018 tại thời điểm nộp hồ sơ Thông báo áp dụng Hiệp định (vào tháng 3/2018). Với trường hợp của Tôi thì được giải quyết như thế nào?
Score: 0.9
Reason: The Actual Output effectively breaks down the complex user query into a comprehensive set of sub-queries. It addresses the core problem of not having a Certificate of Residence at the time of filing due to a non-standard tax year by asking about conditions, mandatory requirements, resolution procedures, tax authority discretion for non-standard years or late submission, and deadlines for supplementation. The sub-queries collectively cover all key aspects and the primary intent of finding a resolution for the specific scenario. The only minor drawback is the redundant inclusion of the original input as the first sub-query, which doesn't add new information but doesn't detract significantly from the overall quality.
------------------------------

Query 15: Theo quy định tại Khoản 3 Điều 16 Nghị định số 201/2013/NĐ-CP ngày 27/11/2013 của Chính phủ quy định chi tiết thi hành một số điều của Luật tài nguyên nước thì “xả nước thải của cá nhân, hộ gia đình thuộc trường hợp không phải xin cấp phép xả nước thải vào nguồn nước” và “xả nước thải của các cơ sở, sản xuất, kinh doanh dịch vụ với quy mô từ 05 m3/ngày đêm trở lên thuộc đối tượng phải cấp phép xả nước thải”. Tuy nhiên, phần hệ thống công trình hạ tầng kỹ thuật về xử lý, xả nước thải của khu căn hộ và dịch vụ thương mại không được tách riêng. Như vậy các Dự án tổ hợp thương mại, dịch vụ, căn hộ và chung cư có thuộc đối tượng phải xin cấp phép không?
Score: 1.0
Reason: The Actual Output strongly aligns with the evaluation steps. It accurately identifies the primary intent of the Input by including the original query as its first sub-query. Furthermore, it provides a highly comprehensive set of additional sub-queries that logically extend from the initial question, covering all critical aspects related to wastewater discharge permits for 'Dự án tổ hợp thương mại, dịch vụ, căn hộ và chung cư' (Commercial, service, apartment, and condominium complex projects). These follow-up questions address conditions, required documents, procedures, competent authority, processing time, and penalties, ensuring no critical components of the search requirements are missed.
------------------------------

Query 16: Tôi muốn biết sau bao lâu tôi sẽ được gia hạn hiệu lực VBBH?
Score: 1.0
Reason: The Actual Output comprehensively covers the primary intent of 'gia hạn hiệu lực VBBH' from the Input. It directly addresses the 'sau bao lâu' aspect with two sub-queries (the first repeating the input and the last clarifying 'Thời hạn giải quyết hồ sơ'). Beyond that, it provides a thorough set of related sub-queries covering conditions, required documents, procedures, and competent authority, ensuring all critical components for understanding the renewal process are addressed.
------------------------------

Query 17: Điều kiện cấp Giấy chứng nhận đủ điều kiện hoạt động kiểm định kỹ thuật an toàn lao động đối với tổ chức gồm những gì?
Score: 0.7
Reason: The Actual Output successfully addresses the primary intent of the Input by including sub-queries directly asking about the 'Điều kiện cấp Giấy chứng nhận đủ điều kiện hoạt động kiểm định kỹ thuật an toàn lao động đối với tổ chức'. However, it expands beyond the Input's specific search requirement for 'conditions' by adding queries about the application dossier, procedure, competent authority, and validity period. While these are related, they are not explicitly requested by the original query. There is also redundancy in the first two sub-queries.
------------------------------

Query 18: Thành phần hồ sơ và trách nhiệm lập hồ sơ đối với thương binh đang công tác trong Quân đội đề nghị giám định bổ sung vết thương còn sót?
Score: 0.9
Reason: The response effectively breaks down the input query into multiple sub-queries. It explicitly addresses the 'Thành phần hồ sơ' and 'Trách nhiệm lập hồ sơ' aspects from the input through specific sub-queries (3 and 6). Furthermore, it provides a comprehensive set of related sub-queries covering 'Điều kiện', 'Trình tự, thủ tục', and 'Cơ quan có thẩm quyền', which are highly relevant to the primary intent of 'đề nghị giám định bổ sung vết thương còn sót'. The only minor shortcoming is that the first sub-query is a direct restatement of the input, rather than a breakdown, but the subsequent queries demonstrate strong alignment with the evaluation steps.
------------------------------

Query 19: Ngân hàng Nhà nước Chi nhánh tỉnh thành phố có tiếp nhận và xử lý hồ sơ đăng ký khoản cho vay ra nước ngoài của tổ chức kinh tế trên địa bàn không?
Score: 1.0
Reason: The response strongly aligns with the evaluation steps. It accurately identifies the primary intent of the input regarding the provincial branch's authority to process overseas loan applications. Sub-queries 1 and 5 directly address this core question. Furthermore, the output provides a comprehensive set of highly relevant follow-up queries covering conditions, required documents, procedures, and processing times, which fully represent the broader search requirements implied by the initial specific query, ensuring no critical components are missed.
------------------------------

Query 20: Công ty của chúng  tôi mới được  cấp giấy chứng nhận đủ điều kiện  huấn luyện an toàn, vệ sinh lao động hạng B. Nay do Công ty chúng tôi thay đổi tên Công ty nên Công ty đã nộp hồ sơ đề nghị đổi tên Công ty trong giấy chứng nhận đủ điều kiện huấn luyện an toàn, vệ sinh lao động, vậy sau bao nhiêu ngày chúng tôi có thể nhận được giấy chứng nhận đổi tên?
Score: 0.6
Reason: The response correctly identified the primary intent of the input, which was to determine the processing time for the company name change on the certificate. Sub-query 6 directly addresses this intent, and sub-query 1 is a verbatim copy of the original query, also covering the intent. However, the output includes four additional sub-queries (conditions, required documents, procedures, and competent authority) that introduce new search requirements not explicitly present in the input's specific question about processing time. This indicates that the output does not 'fully represent the Input's search requirements' but rather expands upon them significantly, and including the original query as a sub-query is redundant.
------------------------------
Average Query Coverage Score: 0.9

Eval laws answer agent

In [44]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_parquet("hf://datasets/thangvip/vietnamese-legal-qa/data/train-00000-of-00001.parquet")

In [45]:
df.head(5)

,doc_name,doc_type_name,article_content,generated_qa_pairs,generation_time
0,"Luật Địa chất và Khoáng sản của Quốc hội, số 5...",Luật,Điều 5. Nguyên tắc hội nhập và hợp tác quốc tế...,[{'answer': 'Theo Khoản 1 Điều 5 Luật Địa chất...,11.126226
1,"Luật Địa chất và Khoáng sản của Quốc hội, số 5...",Luật,"Điều 2. Giải thích từ ngữ\n\nTrong Luật này, c...",[{'answer': 'Dựa trên Khoản 1 Điều 2 của Luật ...,11.682184
2,"Luật Địa chất và Khoáng sản của Quốc hội, số 5...",Luật,Điều 1. Phạm vi điều chỉnh\n\n1. Luật này quy ...,[{'answer': 'Theo khoản 1 Điều 1 của Luật Địa ...,11.741774
3,"Luật Địa chất và Khoáng sản của Quốc hội, số 5...",Luật,"Điều 4. Nguyên tắc điều tra cơ bản địa chất, đ...",[{'answer': 'Theo Điều 4 Khoản 1 của Luật Địa ...,16.472521
4,"Luật Địa chất và Khoáng sản của Quốc hội, số 5...",Luật,"Điều 3. Chính sách của Nhà nước về địa chất, k...",[{'answer': 'Theo Khoản 1 Điều 3 của Luật Địa ...,18.148291

In [30]:
from laws_agent import run_laws_agent

In [ ]:
from deepeval.metrics import FaithfulnessMetric, GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from langchain_core.messages import HumanMessage
from laws_agent import run_laws_agent
import json
import numpy as np

# 1. Cấu hình Metrics
# Faithfulness: Kiểm tra xem câu trả lời có dựa trên context không
faithfulness_metric = FaithfulnessMetric(
    threshold=0.7,
    model=custom_gemini,
    include_reason=True
)

# Thay thế AnswerCorrectnessMetric bằng GEval với tiêu chí Correctness
correctness_metric = GEval(
    name="Answer Correctness",
    criteria="Determine whether the actual output is factually correct and aligns with the expected output (ground truth).",
    evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT, LLMTestCaseParams.EXPECTED_OUTPUT],
    model=custom_gemini,
    threshold=0.7
)

# ...existing code...
print("--- Bắt đầu đánh giá Laws Agent ---")

results = []
question_count = 0
TARGET_SAMPLES = 5

# Duyệt qua dataframe (bỏ head(5) để duyệt đến khi đủ số câu hỏi thì thôi)
for index, row in df.iterrows():
    if question_count >= TARGET_SAMPLES:
        break

    context_content = row['article_content']
    qa_pairs_raw = row['generated_qa_pairs']
    
    # Xử lý format dữ liệu qa_pairs
    qa_pairs = []
    if isinstance(qa_pairs_raw, np.ndarray):
        qa_pairs = qa_pairs_raw.tolist()
    elif isinstance(qa_pairs_raw, list):
        qa_pairs = qa_pairs_raw
    elif isinstance(qa_pairs_raw, str):
        try:
            # Thay thế single quote bằng double quote để parse JSON nếu cần
            qa_pairs = json.loads(qa_pairs_raw)
        except json.JSONDecodeError:
            try:
                qa_pairs = json.loads(qa_pairs_raw.replace("'", '"'))
            except:
                print(f"Không thể parse qa_pairs tại index {index}")
                continue

    # Duyệt qua từng cặp câu hỏi trong list
    for qa in qa_pairs:
        if question_count >= TARGET_SAMPLES:
            break

        question = qa.get('question') 
        ground_truth = qa.get('answer')
        
        if not question or not ground_truth:
            continue

        print(f"\nĐang test câu hỏi {question_count + 1}/{TARGET_SAMPLES}: {question}")

        # 3. Chạy Agent
        state = {
            "messages": [HumanMessage(content=question)],
            "laws_context": context_content
        }
        
        try:
            response_message = run_laws_agent(state)
            actual_output = response_message.content
        except Exception as e:
            print(f"Lỗi khi chạy agent: {e}")
            continue

        # 4. Tạo Test Case
        test_case = LLMTestCase(
            input=question,
            actual_output=actual_output,
            expected_output=ground_truth,
            retrieval_context=[context_content]
        )

        # 5. Đo lường
        try:
            faithfulness_metric.measure(test_case)
            print(f"Faithfulness Score: {faithfulness_metric.score}")
            print(f"Reason: {faithfulness_metric.reason}")
        except Exception as e:
            print(f"Lỗi khi chấm Faithfulness: {e}")
            faithfulness_metric.score = 0

        try:
            correctness_metric.measure(test_case)
            print(f"Correctness Score: {correctness_metric.score}")
            print(f"Reason: {correctness_metric.reason}")
        except Exception as e:
            print(f"Lỗi khi chấm Correctness: {e}")
            correctness_metric.score = 0

        print("-" * 50)

        results.append({
            "question": question,
            "faithfulness": faithfulness_metric.score,
            "correctness": correctness_metric.score,
            "actual_output": actual_output,
            "expected_output": ground_truth
        })
        
        question_count += 1

# Tính điểm trung bình
if results:
    avg_faith = sum(r['faithfulness'] for r in results) / len(results)
    avg_corr = sum(r['correctness'] for r in results) / len(results)
    print(f"\n=== KẾT QUẢ TỔNG HỢP ===")
    print(f"Số lượng test case: {len(results)}")
    print(f"Average Faithfulness: {avg_faith}")
    print(f"Average Correctness: {avg_corr}")

--- Bắt đầu đánh giá Laws Agent ---

Đang test câu hỏi 1/5: Theo Điều 5 Luật Địa chất và Khoáng sản, hội nhập và hợp tác quốc tế về địa chất, khoáng sản được thực hiện trong những hoạt động cụ thể nào?

Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever. Excellent work!

Correctness Score: 0.9
Reason: The Actual Output is factually accurate and fully aligns with the Expected Output in terms of content, scope, and intent, correctly identifying the four activities from Khoản 1 Điều 5 Luật Địa chất và Khoáng sản. However, it deviates from the Expected Output's concise, single-sentence format by including additional formatting such as a heading, an introductory phrase, bullet points, and brief explanations for each activity, making it less direct than the expected response.
--------------------------------------------------

Đang test câu hỏi 2/5: Theo Điều 5 của Luật, khi thực hiện hội nhập và hợp tác quốc tế về địa chất, khoáng sản, Việt Nam cần tuân thủ những nguyên tắc và khuôn khổ pháp lý nào?

Faithfulness Score: 1.0
Reason: The score is 1.00 because there are no contradictions, indicating the actual output is perfectly faithful to the retrieval context. Excellent work!

Correctness Score: 0.9
Reason: The Actual Output is factually accurate and aligns very well with the Expected Output in terms of content, scope, and intent. It lists all the same general principles and legal frameworks. The structure of the Actual Output with headings and bullet points is clear and comprehensive. The only minor shortcoming is that the Actual Output does not explicitly cite 'Khoản 1 Điều 5' as the source for some principles, unlike the Expected Output, though it does state it's 'Dựa trên các luật được trích dẫn'.
--------------------------------------------------

Đang test câu hỏi 3/5: Giả sử có một tranh chấp quốc tế phát sinh liên quan đến địa chất, khoáng sản mà Việt Nam là một bên, việc giải quyết tranh chấp này sẽ được thực hiện theo nguyên tắc và cơ sở pháp lý nào theo Luật Địa chất và Khoáng sản? Hãy phân tích ý nghĩa của quy định này.

Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly aligned with the retrieval context, demonstrating excellent faithfulness! Keep up the great work!

Correctness Score: 0.9
Reason: The Actual Output is factually accurate, correctly identifying the principles (peaceful measures) and legal bases (international custom, international law, law of relevant parties) for dispute resolution as outlined in Article 5, Clause 2. It aligns strongly with the Expected Output in content, scope, and intent, providing a clear explanation of the provision and its significance. While the Actual Output does not explicitly reference Clause 1 as the Expected Output does, its discussion of Vietnam's 'chính sách đối ngoại hòa bình' (peaceful foreign policy) captures the essence of that broader principle, making the alignment sufficient.
--------------------------------------------------

Đang test câu hỏi 4/5: Theo Điều 2 của Luật Địa chất và Khoáng sản, "Địa chất" được định nghĩa như thế nào?

Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions found! Excellent work!

Correctness Score: 0.7
Reason: The Actual Output correctly provides the definition of 'Địa chất' as found in the Expected Output. However, it deviates by adding extra formatting such as a heading, bullet points, and bolding, which are not present in the Expected Output. Additionally, the Actual Output refers to the source as 'khoản 1 Điều 2 của Luật này', which is less specific than the 'Khoản 1 Điều 2 của Luật Địa chất và Khoáng sản' mentioned in the Expected Output.
--------------------------------------------------

Đang test câu hỏi 5/5: Hãy phân tích sự khác biệt và mối quan hệ giữa "Di chỉ địa chất" và "Di sản địa chất" theo quy định tại Điều 2 của Luật Địa chất và Khoáng sản.

Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever! Excellent work!

Correctness Score: 1.0
Reason: The actual output is factually accurate, correctly defining 'Di chỉ địa chất' and 'Di sản địa chất' based on Điều 2. It aligns strongly with the expected output in content and intent, providing a more detailed and structured explanation of the differences and relationships, which enhances clarity without introducing any inaccuracies or deviations from the core information.
--------------------------------------------------

=== KẾT QUẢ TỔNG HỢP ===
Số lượng test case: 5
Average Faithfulness: 1.0
Average Correctness: 0.8800000000000001

Docs Answer Agent Eval

In [1]:
from deepeval.metrics import FaithfulnessMetric, GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from langchain_core.messages import HumanMessage
from documens_agent import run_document_agent
import json
import numpy as np

In [2]:
from dotenv import load_dotenv
load_dotenv("E:\Downloads\projectcongty\.env")

True

In [3]:
import pandas as pd
import pandas as pd

splits = {'train': 'data/train-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/taidng/UIT-ViQuAD2.0/" + splits["validation"])

In [31]:
df["answers_only"] = df["answers"].apply(lambda x: x["text"][0] if len(x["text"]) > 0 else "")

In [32]:
#loại bỏ các hàng có answers_only = ""
df = df[df["answers_only"] != ""].reset_index(drop=True)

In [33]:
df.head(5)

,id,uit_id,title,context,question,answers,is_impossible,plausible_answers,answers_only
0,0008-0003-0002,uit_001746,Kiến,Kiến được tìm thấy trên tất cả các lục địa trừ...,Loài kiến chiếm 25% tổng sinh khối của hệ động...,"{'text': ['nhiệt đới'], 'answer_start': [639]}",False,None,nhiệt đới
1,0004-0007-0004,uit_001035,Chiến tranh Vùng Vịnh,Với thắng lợi mới đạt được của Iran trong cuộc...,Tổ chức Abu Nidal bị đuổi sang Syria vào thời ...,"{'text': ['tháng 11 năm 1983'], 'answer_start'...",False,None,tháng 11 năm 1983
2,0003-0047-0001,uit_000930,Canada,Canada có hai ngôn ngữ chính thức là tiếng Anh...,Ngôn ngữ nào phổ biến nhất ở Canada?,"{'text': ['tiếng Anh và tiếng Pháp'], 'answer_...",False,None,tiếng Anh và tiếng Pháp
3,0003-0013-0007,uit_000721,Canada,"Theo Hiệp định Paris 1783, Anh Quốc công nhận ...",Khi nào thì tỉnh Québec được chia làm hai vùng?,"{'text': ['1791'], 'answer_start': [339]}",False,None,1791
4,0010-0005-0003,uit_002122,Gia cầm,Ngan nhà và Ngan bướu mũi đã được thuần hóa từ...,Thịt ngan thường được lấy từ loại ngan nào?,"{'text': ['Ngan nhà và Ngan bướu mũi'], 'answe...",False,None,Ngan nhà và Ngan bướu mũi

In [34]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [35]:
first_10_questions = df["question"][:10].to_list()
first_10_context = df["context"][:10].to_list()
first_10_answers = df["answers_only"][:10].to_list()

In [1]:
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval.models.base_model import DeepEvalBaseLLM
from multi_agent import llm

# 1. Tạo Wrapper cho Custom LLM (Gemini)
class GoogleGeminiWrapper(DeepEvalBaseLLM):
    def __init__(self, model):
        self.model = model

    def load_model(self):
        return self.model

    def generate(self, prompt: str) -> str:
        # DeepEval gửi prompt dưới dạng string, ta gọi invoke của LangChain
        response = self.model.invoke(prompt)
        return response.content

    async def a_generate(self, prompt: str) -> str:
        # Hỗ trợ async nếu cần
        return self.generate(prompt)

    def get_model_name(self):
        return "gemini-2.5-flash"

# Khởi tạo wrapper
custom_gemini = GoogleGeminiWrapper(llm)

In [37]:
faithfulness_metric = FaithfulnessMetric(
    threshold=0.7,
    model = custom_gemini,
    include_reason=True
)

correctness_metric = GEval(
    name = "Answer Correctness",
    criteria= "Determine whether the actual output is factually correct and aligns with the expected output (ground truth).",
    evaluation_params=[LLMTestCaseParams.ACTUAL_OUTPUT, LLMTestCaseParams.EXPECTED_OUTPUT],
    model = custom_gemini,
    threshold=0.7
)

In [38]:
results = {}
for question,context, expected_answer in zip(first_10_questions, first_10_context, first_10_answers):
    state = {
        "messages": [HumanMessage(content=question)],
        "docs_context": context
    }
    response_message = run_document_agent(state)
    actual_output = response_message.content

    test_case = LLMTestCase(
        input=question,
        actual_output=actual_output,
        expected_output=expected_answer,
        retrieval_context=[context]
    )

    faithfulness_metric.measure(test_case)
    print(f"\nQuestion: {question}")
    print(f"Faithfulness Score: {faithfulness_metric.score}")
    print(f"Reason: {faithfulness_metric.reason}")

    correctness_metric.measure(test_case)
    print(f"Correctness Score: {correctness_metric.score}")
    print(f"Reason: {correctness_metric.reason}")

    print("-" * 50)
    results["faithfulness_scores"] = results.get("faithfulness_scores", []) + [faithfulness_metric.score]
    results["correctness_scores"] = results.get("correctness_scores", []) + [correctness_metric.score]

print(f"\n=== KẾT QUẢ TỔNG HỢP ===")
print(f"Average Faithfulness Score: {sum(results['faithfulness_scores']) / len(results['faithfulness_scores'])}")
print(f"Average Correctness Score: {sum(results['correctness_scores']) / len(results['correctness_scores'])}")

Question: Giải bóng chày Puerto Rico diễn ra vào thời gian nào trong năm?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions present. Excellent work!

Correctness Score: 0.6
Reason: The Actual Output correctly identifies 'mùa đông' as per the Expected Output, demonstrating factual accuracy. However, it includes significant additional text ('Dựa trên nội dung văn bản nhập vào, giải bóng chày chuyên nghiệp của Puerto Rico được tổ chức vào') which is not present in the concise Expected Output. This constitutes a misalignment in completeness and conciseness, as the Actual Output is much more verbose than expected.
--------------------------------------------------

Question: Vụ việc ly hôn của Eleanor và Roosevelt được giải quyết như thế nào?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever. Excellent work!

Correctness Score: 0.6
Reason: The Actual Output correctly identifies the initial part of the resolution, stating that Eleanor and Roosevelt reconciled 'Qua trung gian của Louis Howe, một cố vấn của Franklin, hai người hòa giải với nhau', which aligns with the Expected Output. However, it fails to include the subsequent crucial detail about Eleanor's living arrangements for the remainder of their marriage, specifically 'nhưng trong thời gian còn lại của cuộc hôn nhân, Eleanor đến sống một mình trong một ngôi nhà ở Hyde Park tại Valkill', indicating a lack of completeness.
--------------------------------------------------

Question: Tại khu vực miền tây Mông Cổ là nơi của người thuộc chủng nào sinh sống vào thời đại đồ đồng đá?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever! Great job!

Correctness Score: 0.0
Reason: The Actual Output states 'Europoid (da trắng)' which directly contradicts the Expected Output of 'Mongoloid'. This indicates a complete factual discrepancy and misalignment between the two outputs, failing to meet the criteria for factual accuracy and completeness.
--------------------------------------------------

Question: Tổ chức nào do Pierre Trudeau tạo ra còn tồn tại đến hôm nay?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever. Excellent work!

Correctness Score: 0.0
Reason: The Actual Output states an inability to provide an answer due to insufficient data, which is a complete factual discrepancy from the Expected Output, which provides a specific answer: 'Cơ quan Đánh giá đầu tư nước ngoài (FIRA)'. The Actual Output does not align with the Expected Output in terms of factual accuracy or completeness.
--------------------------------------------------

Question: Quốc hội sẽ không tiến bước nếu không có điều gì?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever. Excellent work!

Correctness Score: 0.0
Reason: The Actual Output does not align with the Expected Output. The Expected Output is a concise phrase 'sự thoả thuận của ông' (his agreement), whereas the Actual Output is a full sentence 'Dựa trên nội dung văn bản nhập vào, Quốc hội sẽ không tiến bước nếu không có sự thoả thuận của Gandhi.' (Based on the input text, the National Assembly will not move forward without Gandhi's agreement). There is a significant factual discrepancy and lack of completeness alignment, as the Actual Output introduces a different subject ('Quốc hội') and a different level of detail not present in the Expected Output.
--------------------------------------------------

Question: Bác sĩ, nhà thám hiểm Alain Bombard đã mất vào năm nào?
Faithfulness Score: 1.0
Reason: The score is 1.00 because there are no contradictions found, indicating excellent faithfulness to the retrieval context. Great job!

Correctness Score: 0.5
Reason: The Actual Output is factually correct, stating that Alain Bombard died in 2005, which aligns with the factual information. However, it does not fully align with the Expected Output's conciseness, as the Expected Output is simply '2005' while the Actual Output provides a full sentence with additional context.
--------------------------------------------------

Question: Toà báo TIME đã phát hành tờ "CHIẾN TRANH VÙNG VỊNH" vào thời gian nào?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions whatsoever! Excellent work!

Correctness Score: 0.4
Reason: The Actual Output correctly includes the date 'ngày 28 tháng 1 năm 1991' which is the Expected Output, demonstrating factual accuracy regarding the core information. However, it fails to fully align with the Expected Output because it contains significant additional and unrequested details about TIME magazine and the Gulf War, deviating from the precise and minimal ground truth.
--------------------------------------------------

Question: Vùng đô thị nào tại Texas có 5,7 triệu dân?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions found. Great job!

Correctness Score: 0.2
Reason: The actual output includes the expected entity 'Houston' but fails significantly in alignment with the expected output. It provides a verbose sentence with additional, unrequested factual information about population and an introductory phrase, instead of just the concise entity 'Houston'. This demonstrates a major discrepancy in both content and format compared to the expected output.
--------------------------------------------------

Question: Những cách thức nào thường được sử dụng trong các cuộc tấn công bằng bom hoá học?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions found. Excellent work!

Correctness Score: 0.7
Reason: The Actual Output conveys the same core factual information as the Expected Output. However, it includes an additional introductory phrase, 'Dựa trên nội dung văn bản nhập vào,' which is not present in the Expected Output. This prevents full alignment and exact completeness as per the ground truth, despite the core statement being factually correct.
--------------------------------------------------

Question: Việc Uganda tham chiến tại chiến trường Cộng hòa Congo đã gây ra thách thức nào cho nền kinh tế Uganda?
Faithfulness Score: 1.0
Reason: The score is 1.00 because the actual output is perfectly faithful to the retrieval context, with no contradictions found! Excellent work!

Correctness Score: 0.4
Reason: The Actual Output does not fully align with the Expected Output. It provides a complete sentence rather than the specific short phrase expected, indicating a significant structural misalignment. Additionally, the key phrase in the Actual Output includes the word 'kinh tế' ('economic'), which is an addition not present in the Expected Output's 'duy trì mức tăng trưởng khả quan' ('maintaining favorable growth'), representing a factual discrepancy from the ground truth.
--------------------------------------------------

=== KẾT QUẢ TỔNG HỢP ===
Average Faithfulness Score: 1.0
Average Correctness Score: 0.33999999999999997

Eval Extract Docs Agent

In [2]:
#lấy list tất cả các đường dẫn tuyệt đối file trong thư mục "pdf files"
import os
pdf_folder = r"C:\Users\Admin\Downloads\Project code\pdf files"
pdf_files = [os.path.join(pdf_folder, f) for f in os.listdir(pdf_folder) if f.endswith('.pdf')]
print(pdf_files)

['C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\hdsd mạng xã hội.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\Kỹ thuật môn bóng đá.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\nâng cao năng lực nghiên cứu đổi mới sáng tạo của sinh viên.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\thói quen sd mxh sinh viên.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\thể chế chính trị cộng hòa.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\tâm lý tình cảm vị thành niên.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\áp dụng công nghệ trong thể thao.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\ô nhiễm môi trường.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\đổi mới mô hình kinh doanh.pdf', 'C:\\Users\\Admin\\Downloads\\Project code\\pdf files\\ứng dụng AI trong học tập.pdf']

In [5]:
import os
from deepeval import evaluate
from deepeval.metrics import ContextualRecallMetric, ContextualPrecisionMetric
from deepeval.test_case import LLMTestCase
from multi_agent import AgentState
from extract_docs_agent import run_docs_agent 
import pandas as pd
from langchain_core.messages import HumanMessage
import time
test_data = pd.read_csv(r"C:\Users\Admin\Downloads\Project code\dataset\dataset_for_extract_docs.csv")
# Định nghĩa Metrics
context_precision = ContextualPrecisionMetric(threshold=0.7, model=custom_gemini)
context_recall = ContextualRecallMetric(threshold=0.7, model=custom_gemini)

test_cases = []
times = []
print("--- Bắt đầu đánh giá Retrieval ---")
scores = {}
for data in test_data.itertuples():
    query = data.Question
    state = AgentState(messages=[HumanMessage(content=query)], uploaded_files=pdf_files)
    a = time.time()
    retrieved_docs = run_docs_agent(state)
    b = time.time()
    print(f"Thời gian truy xuất tài liệu: {b - a} giây")
    times.append(b - a)
    test_case = LLMTestCase(
        input=data.Question,
        actual_output="Placeholder",
        expected_output=data.Answer, 
        retrieval_context=retrieved_docs 
    )
    test_cases.append(test_case)
    context_recall.measure(test_case)
    context_precision.measure(test_case)
    print(f"Query: {query}")
    print(f"Context Recall Score: {context_recall.score}")
    print(f"Reason: {context_recall.reason}")
    print(f"Context Precision Score: {context_precision.score}")
    print(f"Reason: {context_precision.reason}")
    print("-" * 30)
    scores["recall_score"] = scores.get("recall_score",[]) + [context_recall.score]
    scores["precision_score"] = scores.get("precision_score",[]) + [context_precision.score]

print(f"Average Context Recall Score: {sum(scores["recall_score"])/len(scores["recall_score"])}")
print(f"Average Context Precision Score: {sum(scores["precision_score"])/len(scores["precision_score"])}")
print(f"Average Retrieval Time: {sum(times)/len(times)} giây")

Output()

--- Bắt đầu đánh giá Retrieval ---
Thời gian truy xuất tài liệu: 0.16935420036315918 giây

Output()

Output()

Query: Dựa trên kết quả phân tích hồi quy của nghiên cứu, những nhân tố nào có ảnh hưởng tích cực đến năng lực đổi mới sáng tạo của sinh viên Trường Đại học Hồng Đức, và nhân tố nào được xác định là có tác động lớn nhất?
Context Recall Score: 1.0
Reason: The score is 1.00 because the expected output is perfectly aligned with the information in the nodes in retrieval context, with every sentence (1-6) being fully supported by details from nodes 1, 3, 4, 6, and 10. Excellent work!
Context Precision Score: 0.7166666666666666
Reason: The score is 0.72 because while many relevant nodes in retrieval contexts are ranked highly, the presence of irrelevant nodes at higher positions prevents a perfect score. For instance, the second node in retrieval contexts is irrelevant as it "describes the methodology and preliminary results of reliability and EFA analysis, stating "tác giả sử dụng mô hình hồi quy bội để phân tích ảnh hưởng của c ác nhân tố đến năng lực đổi mới sáng tạo của sinh viên chính quy Trường Đại học Hồng Đức." However, it does not provide the specific factors or their impact levels as requested by the input and present in the expected output." This irrelevant node is ranked higher than the third node in retrieval contexts, which explicitly "lists the three positive factors: "môi trường hỗ trợ sáng tạo của tổ chức, động lực nội tại và phong cách sáng tạo," identifies "môi trường hỗ trợ sáng tạo của tổ chức là yếu tố có tác động lớn nhất," and provides the beta coefficient for "Phong cách sáng tạo là nhân tố thứ ba ảnh hưởng đến năng lực đổi mới sáng tạo của sinh viên (β = 0,167)," all of which are crucial for the expected output." Similarly, the fifth node in retrieval contexts is irrelevant because it "details the research methodology, including sample selection and data collection, stating "chúng tôi đã lựa chọn một mẫu nghiên cứu định lượng chính thức với 500 phiếu." However, it does not contain any information about the specific factors influencing innovation capacity or their regression coefficients, which are central to the expected output." This node is ranked above the sixth node in retrieval contexts, which is highly relevant as it "provides the "Bảng 3. Kết quả ước lượng mô hình" which lists the standardized beta coefficients for "DLNT (0,312)", "PCST (0,167)", and "MTHT (0,470)", and explicitly states "có ba nhân tố ảnh hưởng đến năng lực đổi mới sáng tạo của sinh viên Trường Đại học Hồng Đức là : động lực nội tại (DLNT), môi trường hỗ trợ"." Despite these instances of irrelevant nodes being ranked higher, the score is at 0.72 because a substantial number of relevant nodes, such as the first node in retrieval contexts which "directly states that "có ba yếu tố đã được lựa chọn có ảnh hưởng tích cực đến năng lực đổi mới sáng tạo của sinh viên chính quy tại trường" and "Trong số các yếu tố này, môi trường hỗ trợ sáng tạo của tổ chức được xác định là yếu tố có tác động lớn nhất đến năng lực đổi mới sáng tạo của sinh viên," which aligns with the expected output's main findings regarding the number of factors and the most impactful one," are still found at the top ranks, indicating a good overall retrieval performance.
------------------------------
Thời gian truy xuất tài liệu: 0.15320897102355957 giây

Output()

Output()

Query: Tình bạn khác giới ở tuổi vị thành niên có những đặc điểm vai trò gì và các bạn trẻ cần lưu ý tránh những hành vi nào để duy trì mối quan hệ này một cách lành mạnh?
Context Recall Score: 1.0
Reason: The score is 1.00 because the output is perfectly supported by the retrieval context!
Context Precision Score: 1.0
Reason: The score is 1.00 because all relevant nodes in the retrieval contexts are perfectly ranked above all irrelevant nodes, demonstrating excellent retrieval order!
------------------------------
Thời gian truy xuất tài liệu: 0.11501574516296387 giây

Output()

Output()

Query: hãy phân tích các nguyên nhân gây ô nhiễm môi trường đất và những biện pháp, thực trạng quản lý rác thải để khắc phục tình trạng này tại Việt Nam được đề cập như thế nào?
Context Recall Score: 1.0
Reason: The score is 1.00 because the expected output is perfectly aligned with the information found in the nodes in retrieval context. Excellent work!
Context Precision Score: 0.9861111111111112
Reason: The score is 0.99, indicating excellent contextual precision where almost all relevant nodes are ranked higher than irrelevant nodes. The score is not a perfect 1 because an irrelevant node appears at rank 8 in the retrieval contexts. This node, according to its reason, "primarily focuses on water pollution, its sources, and types ('Ô nhiễm nước có nguồn gốc tự nhiên và nhân tạo'). While it mentions 'thuốc trừ sâu, diệt cỏ, phân bón trong nông nghiệp' as causes, its main context is water, not soil pollution or waste management", making it less relevant than the subsequent relevant node at rank 9. Another irrelevant node also appears at rank 10, which, according to its reason, "focuses on air pollution ('Ô nhiễm không khí') and provides a table of various pollutants and their loads, which is not relevant to the causes of soil pollution, waste management measures, or the reality of waste management in Vietnam".
------------------------------
Thời gian truy xuất tài liệu: 0.15629124641418457 giây

Output()

Output()

Query: hãy so sánh sự khác biệt cơ bản về nguyên tắc tổ chức quyền lực, mối quan hệ giữa các nhánh quyền lực và vai trò của người đứng đầu hành pháp trong thể chế cộng hòa đại nghị và thể chế cộng hòa tổng thống.
Context Recall Score: 1.0
Reason: The score is 1.00 because every sentence in the expected output is thoroughly supported by the nodes in retrieval context. For example, sentences 1-4 are well-attributed to nodes 2, 3, 5, 6, 8, and 9, while sentences 5-7 find strong backing in nodes 2, 6, 7, and 10. Fantastic job!
Context Precision Score: 1.0
Reason: The score is 1.00! This indicates an excellent ranking, as all relevant nodes in the retrieval contexts were perfectly positioned above any irrelevant ones.
------------------------------
Thời gian truy xuất tài liệu: 0.13996505737304688 giây

Output()

Output()

Query: hãy mô tả các công nghệ hiện đại đang được vận dụng để hỗ trợ đào tạo vận động viên và tác dụng cụ thể của chúng là gì?
Context Recall Score: 1.0
Reason: The score is 1.00 because the expected output is perfectly supported by the nodes in retrieval context. Excellent work!
Context Precision Score: 0.8083333333333332
Reason: The score is 0.81 because while many relevant nodes in the retrieval contexts are ranked highly, such as the first two nodes, the presence of irrelevant nodes at higher ranks prevents a perfect score. For example, the node at rank 3 is irrelevant as it "primarily focuses on 'ĐỀ XUẤT GIẢI PHÁP ỨNG DỤNG CÔNG NGHỆ 4.0 TRONG NHẬN DẠNG VÀ PHÂN TÍCH CHUYỂN ĐỘNG THỂ THAO' and provides a general introduction to the field. It does not describe specific modern technologies or their concrete effects on athlete training". Similarly, the node at rank 5 is irrelevant because it "is a summary that focuses on 'đề xuất được 6 giải pháp ứng dụng công nghệ 4.0 trong nhận dạng và phân tích chuyển động thể thao'. It provides a high-level overview but does not describe specific modern technologies or their concrete effects on athlete training". The node at rank 7 is also irrelevant, as it "outlines 'Một số giải pháp ứng dụng công nghệ 4.0 trong nhận dạng và phân tích chuyển động thể thao', such as 'Nâng cao hiểu biết về bối cảnh mới của lĩnh vực thể thao' and 'Thúc đẩy các ý tưởng đổi mới về công nghệ thể thao'. These are strategic solutions rather than descriptions of specific modern technologies and their concrete effects on athlete training". These instances of irrelevant nodes appearing before other relevant nodes indicate room for improvement in ranking.
------------------------------
Thời gian truy xuất tài liệu: 0.1561412811279297 giây

Output()

Output()

Query: đổi mới mô hình kinh doanh (BMI) bao gồm những thành phần nào và chúng tác động như thế nào đến kết quả hoạt động của doanh nghiệp khởi nghiệp tại Việt Nam?
Context Recall Score: 0.5
Reason: The score is 0.50 because while the first and fourth sentences of the expected output are well-attributable to the information in the node(s) in retrieval context, the second and third sentences contain claims not fully supported. Specifically, the first sentence's description of BMI components and their positive impact is confirmed by nodes 1, 3, and 8. The fourth sentence's explanation of the positive impact of 'đổi mới giá trị nắm giữ' and its contrast with other studies due to government support is found in nodes 1, 3, 4, and 5. However, the second sentence's assertion that 'đổi mới giá trị sáng tạo' has the 'mức độ ảnh hưởng mạnh nhất' and its specific outcomes are not explicitly stated in nodes 3, 6, 7, or 8. Furthermore, the third sentence's claim that 'đổi mới giá trị cung cấp' helps 'mở rộng đối tác' is contradicted by node 7, which attributes this to 'đổi mới giá trị sáng tạo', and its other stated outcomes are not directly linked in nodes 3 or 8.
Context Precision Score: 0.9888888888888889
Reason: The score is 0.99 because the ranking of retrieval contexts is nearly perfect, with almost all relevant nodes appearing before any irrelevant ones. The first eight nodes in the retrieval contexts are highly relevant to the input. The score is not 1 because the irrelevant node at rank 9, which "does not directly provide information about the components of BMI, their specific impact on performance, or the comparison with other countries as detailed in the expected output. Its contribution is too general compared to other documents.", is ranked higher than the relevant node at rank 10, which "partially repeats information found in document 6, specifically about BMI reducing costs and optimizing processes, and value proposition innovation helping to expand product portfolios. While relevant, the core information is already covered by other, more comprehensive documents.". Despite this minor misplacement of one relevant node after an irrelevant one, the overall contextual precision is excellent.
------------------------------
Thời gian truy xuất tài liệu: 0.18507933616638184 giây

Output()

Output()

Query: Dựa trên kết quả khảo sát sinh viên Trường Đại học Quốc tế Hồng Bàng được trình bày trong văn bản, việc sử dụng mạng xã hội mang lại những tác động tích cực và tiêu cực cụ thể nào đối với quá trình học tập và cuộc sống của sinh viên?
Context Recall Score: 0.6666666666666666
Reason: The score is 0.67 because a significant portion of the expected output is directly attributable to the nodes in retrieval context. For example, sentence 1, highlighting the two-sided impact of social media, is supported by nodes 2, 5, 6, 7, and 9. The specific negative impacts and their percentages mentioned in sentence 4 (wasted time 57.6%, academic results 42.4%) are explicitly stated in node 1. Furthermore, sentence 5, describing student distraction during class, is supported by node 8, and sentence 6's points on difficulty in information selection and negative health impacts are covered by nodes 1 and 7 respectively. However, the score is not perfect because certain specific percentages in the expected output, such as the 58.4% for faster homework in sentence 2 and the 62.6% for connecting with friends and 49.2% for saving study costs in sentence 3, are not explicitly present in the retrieval context, even though the general concepts are mentioned in nodes 4 and 7.
Context Precision Score: 0.9626543209876544
Reason: The score is 0.96 because the retrieval system demonstrated excellent performance, effectively prioritizing relevant information. The score is not higher because one irrelevant node in the retrieval contexts, the seventh node, was ranked above some relevant nodes. This seventh node is irrelevant as its content discusses "Nghiên cứu của Dương Thị Thanh và cộng sự đã trình bày thực trạng sử dụng mạng xã hội của sinh viên Khoa Mầm non và Tiểu học, Trường Đại học Tây Bắc" and "Nghiên cứu “Thực trạng sử dụng mạng xã hội của sinh viên Trường Đại học Y tế Thái Bình", which are studies from other universities and not the specific survey from Hong Bang International University that the input is based on. Ideally, this irrelevant node should have been ranked lower than all relevant nodes.
------------------------------
Thời gian truy xuất tài liệu: 0.17269062995910645 giây

Output()

Output()

Query: việc sử dụng mạng xã hội mang lại những tác động tích cực và tiêu cực cụ thể nào đối với quá trình học tập và cuộc sống của sinh viên?
Context Recall Score: 0.5
Reason: The score is 0.50 because while key aspects of the expected output are directly supported by the nodes in retrieval context, several specific details are not present. For example, sentence 1's assertion of a two-sided impact is well-grounded in nodes 2, 3, 6, 7, and 9. Specific negative impacts in sentence 4 (57.6% time wasted, 42.4% academic impact) are found in node 2, and details on in-class distractions in sentence 5 (38.4% texting, 17.3% entertainment) are supported by nodes 8 and 10. Conversely, sentences 2 and 3, which detail positive impacts and connection benefits, lack the precise percentages (87.4%, 58.4%, 62.6%, 49.2%) in nodes 1 and 5. Additionally, sentence 6's specific phrase 'chú trọng vào các tương tác ảo như "câu like"' is not present in nodes 2, 3, and 5, despite general mentions of information filtering and health impacts.
Context Precision Score: 0.9704861111111112
Reason: The score is 0.97, indicating excellent contextual precision where most relevant nodes are ranked highly. The score is not 1.0 because the 7th node in the retrieval contexts is irrelevant as it focuses on "'Tần suất sử dụng mạng xã hội' and 'Tỷ lệ (%)' for different platforms and hours per day," which is not utilized in the output's discussion of impacts. Additionally, the 10th node in the retrieval contexts is irrelevant because it primarily focuses on "frequency of social media usage and the concept of 'nghiện' (addiction), providing statistics like 'đa số sinh viên sử dụng mạng xã hội trong khoảng thời gian 1 giờ mỗi ngày (chiếm tỷ lệ 29.8%)'," which are not included in the output's focus on impacts. Despite these, the overall high ranking of relevant nodes demonstrates strong performance.
------------------------------
Thời gian truy xuất tài liệu: 0.16269564628601074 giây

Output()

Output()

Query: Theo nội dung văn bản, những thách thức chính nào đang đặt ra đối với việc phát triển và ứng dụng trí tuệ nhân tạo (AI) trong giáo dục đại học tại Việt Nam liên quan đến đội ngũ giảng viên, người học, hạ tầng kỹ thuật và nguồn nhân lực?
Context Recall Score: 1.0
Reason: The score is 1.00 because the expected output is perfectly supported by the nodes in retrieval context. Excellent work!
Context Precision Score: 1.0
Reason: The score is 1.00 because all relevant nodes are perfectly ranked above all irrelevant nodes, ensuring excellent contextual precision!
------------------------------
Thời gian truy xuất tài liệu: 0.18253874778747559 giây

Output()

Query: Dựa trên nội dung văn bản, hãy trình bày các quy định về số lượng cầu thủ được phép thay thế và quy trình thực hiện việc thay người trong một trận đấu bóng đá.
Context Recall Score: 1.0
Reason: The score is 1.00 because every sentence in the expected output is fully supported by the nodes in retrieval context, with information drawn from nodes 1, 2, and 3. Fantastic work!
Context Precision Score: 1.0
Reason: The score is 1.00 because all relevant nodes are perfectly ranked above all irrelevant nodes, providing an excellent retrieval order!
------------------------------
Average Context Recall Score: 0.8666666666666666
Average Context Precision Score: 0.9433140432098766
Average Retrieval Time: 0.15929808616638183 giây

Laws Answer Agent Eval

In [1]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_parquet("hf://datasets/thangvip/vietnamese-legal-qa/data/train-00000-of-00001.parquet")

In [9]:
from laws_agent import run_laws_agent
import time
from langchain_core.messages import HumanMessage

In [5]:
df = df.sample(frac=1, random_state=42)

In [11]:
times = []
for i, sample in enumerate(df.itertuples(),1):
    laws_context = (sample.article_content + "\n") *5
    question = sample.generated_qa_pairs[1]['question']
    answer = sample.generated_qa_pairs[1]['answer']
    state = {
        "messages": [HumanMessage(content=question)],
        "laws_context": laws_context}
    a = time.time()
    response = run_laws_agent(state)
    b = time.time()
    print(f"Question {i}: {question}")
    print(f"Time taken: {b - a} seconds")
    times.append(b - a)
    if i==100:
        break
print(f"Average time for each query: {sum(times)/len(times)} seconds")

Question 1: Điều 10 khoản 1 điểm d) quy định về chứng chỉ bồi dưỡng nghiệp vụ hòa giải, đối thoại nhưng cũng nêu rõ các trường hợp được miễn. Hãy giải thích những đối tượng nào được miễn chứng chỉ này và lý do tại sao họ lại được miễn?
Time taken: 3.0841116905212402 seconds
Question 2: Nêu sự khác biệt cơ bản về thủ tục cấp giấy phép sử dụng vũ khí quân dụng giữa đối tượng thuộc phạm vi quản lý của Bộ Quốc phòng và đối tượng không thuộc phạm vi quản lý của Bộ Quốc phòng theo Điều 21?
Time taken: 5.131699085235596 seconds
Question 3: Một tổ chức kinh tế có vốn đầu tư nước ngoài dự định sở hữu 40% vốn điều lệ của một doanh nghiệp trong ngành công nghiệp trọng điểm của Việt Nam. Doanh nghiệp này có vốn điều lệ là 1.800 tỷ đồng. Căn cứ vào Điều 21, việc sở hữu này có cần sự chấp thuận của Thủ tướng Chính phủ hay không? Giải thích.
Time taken: 4.987001895904541 seconds
Question 4: Điều 219 của Luật Tố tụng hành chính quy định như thế nào về trách nhiệm của Tòa án cấp phúc thẩm đối với việc xác minh chứng cứ mới được bổ sung?
Time taken: 2.85239577293396 seconds
Question 5: Dựa trên Điều 33, hãy phân tích sự khác biệt trong trách nhiệm và các nội dung thực hiện giữa trường hợp Ngân hàng Nhà nước trực tiếp mua bắt buộc và trường hợp Ngân hàng Nhà nước chỉ định tổ chức tín dụng khác mua bắt buộc.
Time taken: 6.57421612739563 seconds
Question 6: Dựa trên Điều 14 của Luật Bảo hiểm y tế, hãy so sánh căn cứ để đóng bảo hiểm y tế giữa người lao động thuộc đối tượng thực hiện chế độ tiền lương do Nhà nước quy định và người lao động hưởng tiền lương, tiền công theo quy định của người sử dụng lao động.
Time taken: 3.49206805229187 seconds
Question 7: Theo Điều 20 Luật Đường sắt, cơ quan nào có thẩm quyền quyết định việc góp vốn nhà nước tham gia vào dự án đầu tư phát triển kết cấu hạ tầng đường sắt quốc gia, đường sắt đô thị theo hình thức đối tác công tư, và thời gian áp dụng quyết định này là khi nào?
Time taken: 2.3970439434051514 seconds
Question 8: Điều 13 quy định các trường hợp dân quân tự vệ nòng cốt phải báo cáo hoặc đăng ký khi có sự thay đổi về địa điểm. Mục đích chung của các quy định này là gì đối với công tác quản lý và huy động dân quân tự vệ?
Time taken: 5.986504554748535 seconds
Question 9: Phân biệt "Hàng siêu trọng" và "Hàng siêu trường" dựa trên các định nghĩa trong Điều 3 của Luật Đường sắt số 35/2005/QH11.
Time taken: 3.765073537826538 seconds
Question 10: Dựa trên Điều 18 của Luật Chứng khoán, hãy phân tích những điểm khác biệt chính trong yêu cầu về hồ sơ giữa chào bán cổ phiếu lần đầu ra công chúng của công ty cổ phần và chào bán thêm cổ phiếu ra công chúng của công ty đại chúng.
Time taken: 12.105283975601196 seconds
Question 11: Căn cứ khoản 1b Điều 22, việc Ủy ban nhân dân cấp tỉnh trình Hội đồng nhân dân cùng cấp quyết định hỗ trợ thêm cho người hưởng trợ cấp hưu trí xã hội phụ thuộc vào những yếu tố nào?
Time taken: 3.3334949016571045 seconds
Question 12: Điều 30 của Dự thảo Luật Các tổ chức tín dụng (sửa đổi) đề cập đến việc Thống đốc Ngân hàng Nhà nước quy định hồ sơ, thủ tục cho những loại Giấy phép cụ thể nào?
Time taken: 2.3414626121520996 seconds
Question 13: Yêu cầu "Việc giải thể doanh nghiệp bảo hiểm, doanh nghiệp tái bảo hiểm phải được Bộ Tài chính chấp thuận bằng văn bản" tại khoản 2 Điều 115 có ý nghĩa gì đối với hoạt động quản lý nhà nước trong lĩnh vực kinh doanh bảo hiểm?
Time taken: 2.285742998123169 seconds
Question 14: Điều 81 quy định các nội dung quản lý nhà nước về hoạt động đường bộ, trong đó có việc "tổ chức nghiên cứu, ứng dụng khoa học và công nghệ; đào tạo, bồi dưỡng nguồn nhân lực trong hoạt động đường bộ". Hãy giải thích ý nghĩa của nội dung này đối với sự phát triển bền vững của ngành đường bộ Việt Nam.
Time taken: 3.5041072368621826 seconds
Question 15: Điều 15 của Luật Giá quy định các Bộ, cơ quan ngang Bộ có những quyền hạn và trách nhiệm cụ thể nào trong việc ban hành và phối hợp xây dựng văn bản quy phạm pháp luật về giá?
Time taken: 4.139676094055176 seconds
Question 16: Hãy so sánh thẩm quyền quyết định buộc xuất cảnh đối với người nước ngoài dựa trên các lý do khác nhau được quy định tại Điều 30 của Luật.
Time taken: 3.6080949306488037 seconds
Question 17: Điều 45 quy định về thời hạn giải quyết hưởng chế độ ốm đau. Hãy phân tích ý nghĩa của việc quy định các mốc thời gian cụ thể cho từng chủ thể (người lao động, người sử dụng lao động, cơ quan bảo hiểm xã hội) trong quy trình này.
Time taken: 9.553210496902466 seconds
Question 18: Mục đích cuối cùng của việc phối hợp giữa các cơ quan được quy định tại Điều 107 là gì?
Time taken: 2.3830583095550537 seconds
Question 19: Trong Khoản 1 Điều 43 Luật Dầu khí, cụm từ "nếu có" trong "chương trình, kế hoạch đã được phê duyệt (nếu có)" có ý nghĩa như thế nào đối với việc lập chương trình hoạt động và ngân sách hoạt động hằng năm của nhà thầu?
Time taken: 3.9792702198028564 seconds
Question 20: Điều 10 của Luật Tổ chức Tòa án nhân dân quy định về chế độ xét xử sơ thẩm có Hội thẩm tham gia. Vậy, ý nghĩa của cụm từ "theo quy định của luật" trong điều khoản này là gì?
Time taken: 1.5864765644073486 seconds
Question 21: Điều 38 Dự thảo Luật Cư trú lần 3 quy định việc đăng ký thường trú, tạm trú bị hủy bỏ trong những trường hợp cụ thể nào?
Time taken: 2.698808193206787 seconds
Question 22: Theo Điều 64 Luật Thanh tra, việc công bố quyết định thanh tra trong hoạt động thanh tra chuyên ngành có điểm gì khác biệt so với quy trình thông thường khi phát hiện hành vi vi phạm cần phải tiến hành thanh tra ngay?
Time taken: 4.254741907119751 seconds
Question 23: Dựa trên Điều 46, hãy phân tích sự khác biệt cơ bản về căn cứ tiến hành giữa hình thức "thanh tra theo kế hoạch" và "thanh tra đột xuất".
Time taken: 7.474323034286499 seconds
Question 24: Hãy phân tích và so sánh các thành phần đảm bảo hiệu quả giám sát của Quốc hội và Hội đồng nhân dân theo quy định tại Điều 10 của Luật này.
Time taken: 6.870959520339966 seconds
Question 25: Hãy giải thích ý nghĩa của cụm từ "chậm nhất là 05 ngày trước ngày mở phiên hòa giải, đối thoại" được quy định tại Khoản 1 Điều 24 đối với nghĩa vụ thông báo của Hòa giải viên.
Time taken: 5.698945760726929 seconds
Question 26: Điều 31 quy định các thời hạn khác nhau cho việc cấp Giấy phép đối với các loại hình tổ chức khác nhau. Hãy phân tích sự khác biệt về thời hạn này và lý giải nguyên nhân có thể dẫn đến sự khác biệt đó.
Time taken: 4.6181440353393555 seconds
Question 27: Anh An có vợ sinh đôi. Một trong hai cháu không may tử vong ngay sau khi sinh và chưa được cấp giấy chứng sinh. Cháu còn lại khỏe mạnh. Anh An cần nộp những giấy tờ gì để hưởng chế độ nghỉ việc khi vợ sinh con và chế độ trợ cấp thai sản một lần cho cháu bé đã mất?
Time taken: 6.091991424560547 seconds
Question 28: Cụm từ "theo quy định của Trung tâm này" tại Điều 70 Luật Các công cụ chuyển nhượng có ý nghĩa gì đối với việc xuất trình yêu cầu thanh toán séc?
Time taken: 2.9298927783966064 seconds
Question 29: Những yếu tố nào cần được xem xét khi xác định phạm vi bảo vệ công trình và hành lang an toàn giao thông đường sắt đô thị, và tại sao những yếu tố này lại quan trọng?
Time taken: 3.5984270572662354 seconds
Question 30: Người chưa thành niên là bị can, bị cáo bị giám sát bởi người đại diện phải thực hiện những nghĩa vụ cam đoan nào và hậu quả pháp lý nếu họ vi phạm các nghĩa vụ đó là gì?
Time taken: 5.442751884460449 seconds
Question 31: Điều 19 Khoản 2 quy định "Tổ chức tín dụng, chi nhánh ngân hàng nước ngoài phải duy trì giá trị thực của vốn điều lệ hoặc vốn được cấp tối thiểu bằng mức vốn pháp định". Yêu cầu này có ý nghĩa gì và cơ quan nào sẽ xử lý nếu giá trị thực của vốn giảm thấp hơn mức vốn pháp định?
Time taken: 5.728981018066406 seconds
Question 32: Điều 20 khoản 1 điểm c của Luật Trọng tài thương mại quy định về trường hợp đặc biệt đối với Trọng tài viên. Hãy giải thích trường hợp đặc biệt này là gì và ý nghĩa của việc cho phép trường hợp này trong việc lựa chọn Trọng tài viên.
Time taken: 8.212137460708618 seconds
Question 33: Theo Điều 158, điểm khác biệt cơ bản trong quy trình chuẩn bị phương án khắc phục giữa tổ chức tín dụng, chi nhánh ngân hàng nước ngoài đã có phương án khắc phục được thông qua theo Điều 143 và trường hợp chưa có là gì?
Time taken: 5.474467039108276 seconds
Question 34: Trong thời gian giữa kỳ họp thứ nhất và kỳ họp thứ hai của Quốc hội, cơ quan, tổ chức, đại biểu Quốc hội trình dự án luật có những trách nhiệm chính nào trong việc nghiên cứu, giải trình, tiếp thu, chỉnh lý dự thảo luật, và họ cần phối hợp với những cơ quan nào để thực hiện các trách nhiệm đó?
Time taken: 3.9836983680725098 seconds
Question 35: Trong quá trình nghiên cứu tiếp thu, giải trình và chỉnh lý dự thảo luật, nghị quyết, Ủy ban Thường vụ Quốc hội đóng vai trò như thế nào, đặc biệt trong các trường hợp có ý kiến khác nhau hoặc dự án phức tạp?
Time taken: 6.341932058334351 seconds
Question 36: Khoản 2 Điều 14 quy định Trung tâm Hòa giải, Đối thoại phải công bố thông tin sau khi thành lập. Việc công bố này nhằm mục đích gì và những nội dung cụ thể nào bắt buộc phải được công bố?
Time taken: 4.772551536560059 seconds
Question 37: Theo khoản 2 Điều 11 được sửa đổi trong Dự thảo Luật, văn bản quy định chi tiết phải có hiệu lực cùng thời điểm với văn bản hoặc điều, khoản, điểm được quy định chi tiết. Hãy phân tích ý nghĩa của quy định này trong việc đảm bảo tính thống nhất và hiệu quả của hệ thống pháp luật.
Time taken: 9.515824794769287 seconds
Question 38: Theo Điều 50, cơ quan cấp Phiếu lý lịch tư pháp có nghĩa vụ bổ sung, đính chính, thu hồi, hủy bỏ Phiếu lý lịch tư pháp trong những trường hợp cụ thể nào?
Time taken: 2.415895700454712 seconds
Question 39: Hãy so sánh cơ sở điều chỉnh tiền lương đã đóng bảo hiểm xã hội giữa người lao động tham gia bảo hiểm xã hội trước ngày 01 tháng 01 năm 2016 và người lao động bắt đầu tham gia từ ngày 01 tháng 01 năm 2016 trở đi theo Điều 63 của Luật Bảo hiểm xã hội.
Time taken: 3.4941933155059814 seconds
Question 40: Trong những trường hợp cụ thể nào Thống đốc Ngân hàng Nhà nước có thẩm quyền quy định cơ chế xác định lãi suất, phí trong hoạt động kinh doanh của tổ chức tín dụng, và mục đích của việc quy định này là gì?
Time taken: 2.8805651664733887 seconds
Question 41: Đối với dự án quan trọng quốc gia hoặc dự án nhóm A có nhiều dự án thành phần, việc quản lý các dự án thành phần này được quy định như thế nào và yêu cầu về việc phân chia dự án thành phần hoặc phân kỳ đầu tư là gì?
Time taken: 3.2302422523498535 seconds
Question 42: Hãy so sánh quy định về thời hạn gửi hồ sơ dự án, dự thảo và đối tượng nhận hồ sơ khi trình Quốc hội và Ủy ban thường vụ Quốc hội xem xét, thông qua theo Điều 73 của Luật này.
Time taken: 5.161212921142578 seconds
Question 43: Điều 27 quy định như thế nào về trách nhiệm của doanh nghiệp bảo hiểm và quyền khấu trừ phí bảo hiểm đối với hợp đồng bảo hiểm nhân thọ, hợp đồng bảo hiểm sức khỏe so với hợp đồng bảo hiểm tài sản, thiệt hại và trách nhiệm khi sự kiện bảo hiểm xảy ra trước thời điểm đơn phương chấm dứt hợp đồng theo khoản 1 Điều 26?
Time taken: 4.305320739746094 seconds
Question 44: Hãy giải thích phạm vi của hành vi "mua bán, chuyển giao, hủy trái phép tài liệu lưu trữ" được quy định tại Khoản 3 Điều 8. Cụm từ "trái phép" trong ngữ cảnh này hàm ý gì?
Time taken: 3.321491003036499 seconds
Question 45: Điều 62 quy định trách nhiệm của Ủy ban nhân dân cấp tỉnh và Bộ Tư pháp trong việc xây dựng và quản lý cơ sở dữ liệu công chứng như thế nào? Hãy so sánh vai trò của hai chủ thể này.
Time taken: 5.500382661819458 seconds
Question 46: Điều 43 của Luật Thanh tra quy định về thẩm quyền ban hành quy định trang phục, thẻ thanh tra có gì khác biệt giữa "Thanh tra viên" và "Người được giao thực hiện nhiệm vụ thanh tra chuyên ngành"?
Time taken: 3.972982406616211 seconds
Question 47: Điều 78 quy định Văn phòng đại diện của Tổ chức trọng tài nước ngoài tại Việt Nam có quyền "Tìm kiếm, thúc đẩy các cơ hội hoạt động trọng tài của tổ chức mình tại Việt Nam" nhưng lại "Không được thực hiện hoạt động trọng tài tại Việt Nam". Hãy giải thích sự khác biệt và giới hạn trong hoạt động của Văn phòng đại diện dựa trên các quy định này.
Time taken: 8.578140020370483 seconds
Question 48: Điều 36 Khoản 1 quy định việc khuyến khích xét nghiệm gen và tư vấn về gen di truyền đối với người có nguy cơ. Hãy phân tích ý nghĩa của quy định này trong việc nâng cao chất lượng dân số.
Time taken: 6.962294340133667 seconds
Question 49: Khoản 2 Điều 1 của Luật Tiếp công dân quy định rằng "Việc tiếp đại diện của cơ quan, tổ chức đến khiếu nại, kiến nghị, phản ánh, tiếp người nước ngoài đến khiếu nại, tố cáo, kiến nghị, phản ánh được thực hiện như đối với tiếp công dân." Quy định này có ý nghĩa gì trong việc mở rộng phạm vi áp dụng của Luật?
Time taken: 3.63634991645813 seconds
Question 50: Dựa vào Điều 71 Luật Ngân sách Nhà nước, hãy phân tích điểm chung về thời điểm thực hiện kiểm toán của Kiểm toán nhà nước đối với báo cáo quyết toán ngân sách nhà nước và báo cáo quyết toán ngân sách địa phương.
Time taken: 2.686506986618042 seconds
Question 51: Điều 69 Luật Đường bộ quy định những điều kiện nào đối với cơ sở, tổ chức, cá nhân cung cấp dịch vụ vận tải người bệnh và những yêu cầu nào đối với xe ô tô cứu thương dùng để vận tải người bệnh?
Time taken: 3.510802984237671 seconds
Question 52: Khoản 3 Điều 17 quy định thời hạn 30 ngày để Sở Tư pháp xử lý hồ sơ đăng ký hoạt động. Hãy phân tích ý nghĩa của thời hạn này đối với quá trình đăng ký và các bên liên quan, bao gồm cả quyền của người bị từ chối?
Time taken: 10.934570550918579 seconds
Question 53: Dựa trên Điều 22, hãy phân tích sự khác biệt về phạm vi và điều kiện giám sát của Ủy ban thường vụ Quốc hội khi xem xét văn bản quy phạm pháp luật (khoản 2) so với xem xét nghị quyết của Hội đồng nhân dân cấp tỉnh (khoản 5).
Time taken: 7.1617591381073 seconds
Question 54: Hãy phân tích và so sánh nghĩa vụ liên quan đến việc đăng ký giao dịch hoặc niêm yết cổ phiếu của công ty đại chúng được quy định tại điểm d và điểm đ khoản 1 Điều 34 Luật Chứng khoán. Nêu rõ sự khác biệt về thời hạn và nền tảng giao dịch ban đầu.
Time taken: 9.919916152954102 seconds
Question 55: Khi một quyết định hành chính bị hủy bỏ theo Điều 45, việc hủy bỏ đó có tác động như thế nào đến hiệu lực của quyết định và nghĩa vụ chung của các bên đã hưởng quyền, lợi ích từ quyết định đó là gì?
Time taken: 4.474203824996948 seconds
Question 56: Trong bối cảnh pháp luật kinh doanh bảo hiểm, cụm từ "Đề phòng, hạn chế tổn thất" tại Điều 59 thường được hiểu là đề cập đến nguyên tắc hoặc trách nhiệm nào của các bên liên quan đến hợp đồng bảo hiểm?
Time taken: 2.1362016201019287 seconds
Question 57: Khoản 2 Điều 4 của Luật Tố cáo quy định việc giải quyết tố cáo phải "bảo đảm an toàn cho người tố cáo" và "bảo đảm quyền và lợi ích hợp pháp của người bị tố cáo". Ý nghĩa của hai nguyên tắc này trong quá trình giải quyết tố cáo là gì?
Time taken: 11.113394260406494 seconds
Question 58: Dựa vào Điều 5, hãy phân biệt "loại công trình" và "cấp công trình" bằng cách nêu rõ các tiêu chí được sử dụng để xác định từng loại.
Time taken: 2.9366230964660645 seconds
Question 59: Căn cứ Điều 194, hãy phân tích trách nhiệm cụ thể của Bộ Công an và Bộ Quốc phòng trong việc đối phó với hành vi can thiệp bất hợp pháp vào hoạt động hàng không dân dụng. Vai trò của hai Bộ này có điểm gì khác biệt?
Time taken: 7.428044080734253 seconds
Question 60: Việc Thẩm phán phải kiểm tra biên bản và cùng với Thư ký phiên họp ký vào biên bản sau khi kết thúc phiên họp, theo khoản 2 Điều 67, có ý nghĩa pháp lý như thế nào?
Time taken: 2.1133477687835693 seconds
Question 61: Ngoài ngày hiệu lực thi hành chung, những quy định cụ thể nào của Luật Các tổ chức tín dụng (sửa đổi) có hiệu lực vào một thời điểm khác và thời điểm đó là khi nào?
Time taken: 2.839698314666748 seconds
Question 62: Vai trò của Bộ trưởng Bộ Tài chính trong việc đảm bảo an toàn tài chính của các tổ chức kinh doanh chứng khoán được quy định tại Điều 92 như thế nào?
Time taken: 2.746283769607544 seconds
Question 63: Dựa vào Điều 17 của Dự thảo Luật Kinh doanh bảo hiểm (sửa đổi), doanh nghiệp bảo hiểm có thể từ chối trả tiền bảo hiểm hoặc bồi thường trong những trường hợp nào, và họ có nghĩa vụ gì khi thực hiện việc từ chối đó?
Time taken: 3.3453807830810547 seconds
Question 64: Điều 21 quy định về nhiệm vụ thẩm tra của Ủy ban tài chính, ngân sách. Hãy phân tích điểm khác biệt chính về phạm vi và tính chất của nhiệm vụ thẩm tra giữa Khoản 1 và Khoản 2, đặc biệt liên quan đến các loại văn bản được thẩm tra và cơ quan trình?
Time taken: 9.242844820022583 seconds
Question 65: Một người hành nghề chứng khoán đang làm việc tại Công ty A, nhưng Công ty A không có nghiệp vụ môi giới chứng khoán. Người này muốn mở tài khoản giao dịch chứng khoán tại Công ty B (nơi mình không làm việc). Hành vi này có được phép theo quy định của Điều 98 Luật Chứng khoán không? Giải thích rõ.
Time taken: 3.381303548812866 seconds
Question 66: Dựa trên Điều 16 của Luật Kinh doanh bảo hiểm, hãy phân tích và so sánh "Nguyên tắc bồi thường" và "Nguyên tắc thế quyền" về phạm vi áp dụng và mục đích cốt lõi của chúng trong hợp đồng bảo hiểm.
Time taken: 237.4295334815979 seconds
Question 67: Theo Điều 49 Khoản 2, chứng khoán niêm yết, giao dịch tại Sở giao dịch chứng khoán không được giao dịch bên ngoài hệ thống giao dịch của Sở. Vậy, trong những trường hợp cụ thể nào thì ngoại lệ này được áp dụng và cơ quan nào có thẩm quyền quy định chi tiết về các trường hợp này?
Time taken: 3.3383052349090576 seconds
Question 68: Biện pháp hạn chế "không chia cổ tức, lợi tức, phân phối lợi nhuận sau thuế sau khi trích lập các quỹ, chuyển lợi nhuận về nước; hạn chế chuyển nhượng cổ phần, phần vốn góp, chuyển nhượng tài sản" quy định tại điểm a khoản 2 Điều 157 có ý nghĩa và mục đích gì đối với tổ chức tín dụng, chi nhánh ngân hàng nước ngoài được can thiệp sớm?
Time taken: 1.6724345684051514 seconds
Question 69: Điều 71 quy định Chủ tịch Hội đồng quản trị có những nghĩa vụ gì để đảm bảo tính minh bạch, hiệu quả và trách nhiệm giải trình trong hoạt động của Hội đồng quản trị và các thành viên?
Time taken: 10.433014869689941 seconds
Question 70: Nêu rõ vai trò của Công an cấp xã và Chủ tịch Ủy ban nhân dân cùng cấp trong quá trình thành lập Tổ bảo vệ an ninh, trật tự và công nhận thành viên của Tổ theo quy định tại Điều 16?
Time taken: 4.8455164432525635 seconds
Question 71: Điều 24 quy định trách nhiệm của cơ sở cung cấp dịch vụ phá thai trong việc ngăn chặn phá thai lựa chọn giới tính và hỗ trợ các đối tượng đặc biệt như thế nào?
Time taken: 3.194232702255249 seconds
Question 72: Theo Điều 145 Dự thảo Luật Kinh doanh bảo hiểm (sửa đổi), việc doanh nghiệp bảo hiểm và doanh nghiệp môi giới bảo hiểm cung cấp dịch vụ phụ trợ bảo hiểm cho doanh nghiệp bảo hiểm, doanh nghiệp tái bảo hiểm khác cần tuân thủ điều kiện gì?
Time taken: 2.4590907096862793 seconds
Question 73: Khi nào Bộ trưởng, Thủ trưởng cơ quan ngang bộ phải thành lập hội đồng tư vấn thẩm định đối với dự thảo thông tư và thành phần tham gia hội đồng này gồm những ai?
Time taken: 3.079746723175049 seconds
Question 74: Theo Điều 91, có sự khác biệt nào về thời hạn thông báo dự kiến chương trình kỳ họp giữa kỳ họp thường lệ và kỳ họp bất thường của Quốc hội không? Nếu có, hãy nêu rõ.
Time taken: 2.363891363143921 seconds
Question 75: Dựa vào tiêu đề "Chỉ định, thay đổi người thụ hưởng" tại Điều 37, có thể suy luận về những quyền và nghĩa vụ cơ bản nào của các bên liên quan đến người thụ hưởng trong hợp đồng bảo hiểm?
Time taken: 1.7525544166564941 seconds
Question 76: Điều 98 quy định lộ trình tăng tuổi hưởng lương hưu đối với nam và nữ như thế nào, và khi nào thì đạt đến tuổi nghỉ hưu tối đa được quy định?
Time taken: 3.4068360328674316 seconds
Question 77: Điều 24 của Dự thảo Luật Kinh doanh bảo hiểm (sửa đổi) quy định hợp đồng bảo hiểm chấm dứt trong những trường hợp nào ngoài các quy định chung?
Time taken: 3.050532341003418 seconds

Docs Answer Agent Time Eval

In [1]:
import pandas as pd
import pandas as pd

splits = {'train': 'data/train-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/taidng/UIT-ViQuAD2.0/" + splits["validation"])
df["answers_only"] = df["answers"].apply(lambda x: x["text"][0] if len(x["text"]) > 0 else "")
df = df[df["answers_only"] != ""].reset_index(drop=True)

In [3]:
def get_number_of_words(text:str):
    return len(text.split())

df["context_word_count"] = df["context"].apply(get_number_of_words)

In [5]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [18]:
from documens_agent import run_document_agent
import time
from langchain_core.messages import HumanMessage
from multi_agent import AgentState

In [22]:
times = []
for i, sample in enumerate(df.itertuples(),1):
    context = (sample.context + "\n") *17
    question = sample.question
    state = AgentState(messages=[HumanMessage(content=question)], docs_context=context)
    a = time.time()
    response = run_document_agent(state)
    b = time.time()
    print(f"Question {i}: {question}")
    print(f"Time taken: {b - a} seconds")
    print(response.content)
    print("-----")
    times.append(b - a)
    if i==100:
        break
print(f"Average time for each query: {sum(times)/len(times)} seconds")

Question 1: Ngoài Texas thì bang nào tại Hoa Kỳ cùng dẫn đầu trong bảng danh sách các bang có công ty lọt vào Fortune 500?
Time taken: 1.6531167030334473 seconds
Dựa trên nội dung văn bản nhập vào, theo số liệu năm 2010, California đồng hạng với Texas trong việc đứng đầu các tiểu bang có công ty lọt vào Fortune 500.
-----
Question 2: Tình trạng của người điều khiển giao thông đường bộ ở Paris như thế nào?
Time taken: 2.82619047164917 seconds
Dựa trên nội dung văn bản nhập vào, tôi không đủ dữ kiện để đưa ra câu trả lời
-----
Question 3: Mitterrand tham gia chiến trường ở vị trí nào?
Time taken: 1.402839183807373 seconds
Dựa trên nội dung văn bản nhập vào, Mitterrand tham gia chiến trường với vị trí "một trung sĩ bộ binh".
-----
Question 4: Viện Phục hồi Roosevelt Warm Springs được Roosevelt thành lập khi nào?
Time taken: 2.138273239135742 seconds
Dựa trên nội dung văn bản nhập vào, Viện Phục hồi Roosevelt Warm Springs (ban đầu là một trung tâm thủy liệu pháp) được Roosevelt thành lập vào năm 1926.
-----
Question 5: Thời tiết như thế nào tạo điều kiện thuận lợi cho hiện tượng phối giống của loài kiến?
Time taken: 1.9504938125610352 seconds
Dựa trên nội dung văn bản nhập vào, thời tiết tạo điều kiện thuận lợi cho hiện tượng phối giống của loài kiến thường là "vào những mùa ấm áp hay oi bức".
-----
Question 6: Lý do mà một số đoàn truyền giáo được ra đời tại Đông Texas vào năm 1690 là gì?
Time taken: 2.1476614475250244 seconds
Dựa trên nội dung văn bản nhập vào, lý do mà một số đoàn truyền giáo được ra đời tại Đông Texas vào năm 1690 là vì "nhà cầm quyền Tây Ban Nha lo ngại rằng Pháp tạo ra mối đe dọa cạnh tranh".
-----
Question 7: Cyathea intermedia là loài dương xỉ như thế nào?
Time taken: 2.2130556106567383 seconds
Dựa trên nội dung văn bản nhập vào, Cyathea intermedia là loài dương xỉ lớn nhất thế giới và là loài đặc hữu của Nouvelle-Calédonie. Nó rất phổ biến trên đất có tính a xít, mọc cao khoảng một mét mỗi năm tại duyên hải phía đông, thường là trên đất hoang hoặc trong rừng thưa.
-----
Question 8: Trong liên danh tranh cử của Đảng Dân chủ, Roosevelt được đề cử là ứng viên cho chức vụ gì?
Time taken: 1.7609314918518066 seconds
Dựa trên nội dung văn bản nhập vào, Roosevelt được đề cử là ứng viên Phó Tổng thống Hoa Kỳ trong liên danh tranh cử tổng thống của Thống đốc tiểu bang Ohio là James M. Cox.
-----
Question 9: Hội nghị Cairo diễn ra vào tháng 11 năm 1943 với sự gặp mặt của những ai?
Time taken: 2.280461549758911 seconds
Dựa trên nội dung văn bản nhập vào, Hội nghị Cairo diễn ra vào tháng 11 năm 1943 với sự gặp mặt của Roosevelt, Churchill và lãnh tụ Trung Quốc Quốc dân đảng Tưởng Giới Thạch.
-----
Question 10: Năm 2011 thì lượng nhập siêu hàng hóa và dịch vụ của Nouvelle-Calédonie là bao nhiêu?
Time taken: 1.5837066173553467 seconds
Dựa trên nội dung văn bản nhập vào, nhập siêu hàng hoá và dịch vụ của Nouvelle-Calédonie là 3,11 tỷ USD trong năm 2011.
-----
Question 11: Lệnh Hành pháp số 9066 mà Roosevelt ban hành, có hiệu lực với ai?
Time taken: 1.736046314239502 seconds
Dựa trên nội dung văn bản nhập vào, Lệnh Hành pháp số 9066 được áp dụng đối với "mọi người bị xếp loại là những người thuộc quốc gia thù địch, bao gồm những người có hai quốc tịch đang sống trong những vùng được cho là có nguy cơ cao mà bao trùm phần lớn các thành phố tại Tây Duyên hải Hoa Kỳ."
-----
Question 12: Nguyên nhân sâu xa khiến cho một số lượng lớn người Palestine bị trục xuất khỏi Kuwait là gì?
Time taken: 2.1635725498199463 seconds
Dựa trên nội dung văn bản nhập vào, nguyên nhân sâu xa khiến cho một số lượng lớn người Palestine bị trục xuất khỏi Kuwait là do "Tổ chức Giải phóng Palestine dưới quyền lãnh đạo của Yasser Arafat hoàn toàn ủng hộ Saddam Hussein, sau này dẫn tới một sự tuyệt giao trong quan hệ giữa Palestine-Kuwait, dẫn tới sự trục xuất nhiều người Palestine ra khỏi Kuwait."
-----
Question 13: Người Đức bắt đầu phục vụ ai?
Time taken: 1.6791670322418213 seconds
Dựa trên nội dung văn bản nhập vào, người Đức "dần dà nhiễm tư tưởng dễ chấp nhận sự chuyên chế, phục tòng một cách mù quáng đối với những ông vua ti tiện."
-----
Question 14: Địa điểm nào được xem như nguồn tài nguyên quý giá nhất Ả Rập Xê Út?
Time taken: 1.8714022636413574 seconds
Dựa trên nội dung văn bản nhập vào, địa điểm được xem như nguồn tài nguyên giá trị nhất của Ả Rập Xê Út là "các giếng dầu ở Hama".
-----
Question 15: Bên bờ trái sông Sen đã phát triển mạnh về hoạt động gì vào thế kỉ XII?
Time taken: 4.269680500030518 seconds
Dựa trên nội dung văn bản nhập vào, bên bờ trái sông Seine (Tả ngạn sông Seine) đã phát triển mạnh về giáo dục, với các nhà thờ đóng vai trò quan trọng và các trường học của giáo hội gây dựng được tiếng tăm.
-----
Question 16: Gruzia lập một cơ quan hành chính vào khi nào?
Time taken: 2.1333484649658203 seconds
Dựa trên nội dung văn bản nhập vào, Gruzia đã lập ra một Cơ quan hành chính lâm thời thực thể Nam Ossetia vào tháng 4 năm 2007.
-----
Question 17: Vì sao vua di chuyển đến Hôtel Saint-Pol?
Time taken: 2.5753397941589355 seconds
Dựa trên nội dung văn bản nhập vào, các vị vua di chuyển đến Hôtel Saint-Pol (và sau đó là Hôtel des Tournelles) vì "nơi dễ dàng thoát khi có binh biến", sau chính biến lớn đầu tiên trong lịch sử Pháp vào năm 1358 do sự bất mãn của dân chúng và tham vọng của quan thái thú Étienne Marcel.
-----
Question 18: Chính phủ Roosevelt đã có một cái nhìn gì khác sau khi biết được ý đồ của Đức Quốc Xã?
Time taken: 2.1552505493164062 seconds
Dựa trên nội dung văn bản nhập vào, sau khi biết được ý đồ của Đức Quốc Xã, chính phủ Roosevelt đã thay đổi cách nhìn trước đây về chế độ Đức Quốc xã. Trước đó, họ coi đây là "một chế độ khó ưa, tuy nhiên trên cơ bản không phải là vấn đề đáng lo đối với Mỹ", nhưng sau đó đã hoang mang rằng "tham vọng của người Đức không chỉ giới hạn trong khu vực châu Âu mà trên toàn thế giới".
-----
Question 19: Mỹ ủng hô người dân Puerto Rico theo tôn giáo nào?
Time taken: 1.5542528629302979 seconds
Dựa trên nội dung văn bản nhập vào, Mỹ khuyến khích Đạo Tin lành khi Puerto Rico gia nhập nước Mỹ.
-----
Question 20: Sau hai vị Hoàng đế là Leopold và Joseph thì vị Hoàng đế thứ ba trị vì Đế quốc trong giai đoạn bao lâu?
Time taken: 2.298379421234131 seconds
Dựa trên nội dung văn bản nhập vào, sau hai vị Hoàng đế Leopold I và Joseph I, vị Hoàng đế thứ ba là Karl VI (1711-1740) đã trị vì Đế quốc trong 29 năm.
-----
Question 21: CIA và Kuwait nhận định tính xác thực của thông tin trong văn bản như thế nào?
Time taken: 1.5714342594146729 seconds
Dựa trên nội dung văn bản nhập vào, CIA và Kuwait đã miêu tả cuộc gặp gỡ giữa giám đốc CIA William Webster và Thiếu tướng Fahd Ahmed Al-Fahd là một cuộc gặp thông thường và bản ghi nhớ mà Iraq tuyên bố tìm thấy chỉ là một sự giả mạo.
-----
Question 22: Nhà thám hiểm châu Âu đã gọi hòn đảo mới tìm thấy là gì?
Time taken: 1.4801032543182373 seconds
Dựa trên nội dung văn bản nhập vào, nhà thám hiểm châu Âu (Christopher Columbus) đã đặt tên cho hòn đảo mới tìm thấy là San Juan Bautista.
-----
Question 23: Loại hình âm nhạc Kaneka được khởi nguồn vào lúc nào?
Time taken: 2.872382402420044 seconds
Dựa trên nội dung văn bản nhập vào, loại hình âm nhạc Kaneka được khởi nguồn "trong thập niên 1980".
-----
Question 24: Hector Guimard là nghệ sĩ theo trường phái nào?
Time taken: 1.503432035446167 seconds
Dựa trên nội dung văn bản nhập vào, Hector Guimard là nghệ sĩ theo trường phái Tân nghệ thuật.
-----
Question 25: Thể loại nhạc xuất hiện trong Carnaval Paris là gì?
Time taken: 1.9652223587036133 seconds
Dựa trên nội dung văn bản nhập vào, thể loại nhạc xuất hiện trong Carnaval Paris là "Âm nhạc cho khiêu vũ của Paris trong thế kỷ 19".
-----
Question 26: Có sự kiện gì xảy ra vào ngày Quốc khánh trên Quốc lộ Champs-Élysées?
Time taken: 1.5851333141326904 seconds
Dựa trên nội dung văn bản nhập vào, vào Ngày quốc khánh Pháp 14 tháng bảy, tại đại lộ Champs-Élysées là dịp tổ chức duyệt binh truyền thống.
-----
Question 27: Hệ thống dịch vụ xe đạp nào lớn nhất châu Âu?
Time taken: 2.3335769176483154 seconds
Dựa trên nội dung văn bản nhập vào, hệ thống dịch vụ xe đạp Vélib' của Paris là "mạng lưới xe đạp dày đặc nhất châu Âu".
-----
Question 28: Xác của vợ Roosevelt được chôn cất ở đâu khi bà mất?
Time taken: 2.3017265796661377 seconds
Dựa trên nội dung văn bản nhập vào, sau khi vợ ông qua đời tháng 11 năm 1962, bà được chôn cất bên cạnh ông, tức là "trong vườn hồng của ngôi nhà gia đình Roosevelt (nay được gọi là Home of Franklin D. Roosevelt National Historic Site, tạm dịch là Di tích Lịch sử Quốc gia Nhà của Franklin D. Roosevelt) ở thị trấn Hyde Park".
-----
Question 29: Sau khi bị đánh bại bởi liên danh tranh cử của Đảng Cộng hòa, Roosevelt đã làm những gì?
Time taken: 1.87400221824646 seconds
Dựa trên nội dung văn bản nhập vào, sau khi bị đánh bại bởi liên danh tranh cử của Đảng Cộng hòa, Roosevelt đã "trở về hành nghề pháp lý tại New York và gia nhập Câu lạc bộ Civitan New York vừa mới được thành lập".
-----
Question 30: Nhóm tình nguyện của Gandhi lập ra gồm bao nhiêu người?
Time taken: 1.828000783920288 seconds
Dựa trên nội dung văn bản nhập vào, nhóm tình nguyện cứu thương của Gandhi gồm 300 người Ấn Độ và 800 người làm mướn.
-----
Question 31: Sự tranh chấp quyền lực tại Mông Cổ với điển hình là sự tranh chấp của các thế lực nào?
Time taken: 1.843299388885498 seconds
Dựa trên nội dung văn bản nhập vào, sự tranh chấp quyền lực tại Mông Cổ diễn ra đáng chú ý là giữa dòng hậu duệ Thành Cát Tư Hãn và người Ngõa Lạt không phải hậu duệ của ông (người Mông Cổ Tây).
-----
Question 32: Tại sao triều đình Habsburg phải cải cách?
Time taken: 1.8427040576934814 seconds
Dựa trên nội dung văn bản nhập vào, triều đình Habsburg phải tiến hành cải cách "Với thất bại của nền quân chủ Habsburg trong các cuộc chiến tranh nêu trên, và sự phát triển lớn mạnh của nền quân chủ Phổ".
-----
Question 33: Mỗi học sinh tại Texas thì bang phải chi bao nhiêu tiền vào khoảng giữa năm 2006 và 2007?
Time taken: 1.6572604179382324 seconds
Dựa trên nội dung văn bản nhập vào, giữa năm 2006 và 2007, Texas chi $7.275 cho mỗi học sinh.
-----
Question 34: Sự kiện nào đánh dấu sự hình thành của lưu vực sông Loire và sông Seine?
Time taken: 1.829702615737915 seconds
Dựa trên nội dung văn bản nhập vào, sự hình thành của dãy Alps đã báo trước cho sự hình thành lưu vực sông Loire và sông Seine.
-----
Question 35: Tỷ lệ diện tích hoang mạc tại bang Texas là bao nhiêu?
Time taken: 1.510155439376831 seconds
Dựa trên nội dung văn bản nhập vào, chỉ dưới 10 phần trăm diện tích đất của tiểu bang Texas là hoang mạc.
-----
Question 36: Paris có những viện bảo tàng nào chỉ lưu trữ tác phẩm của một danh nhân văn hóa?
Time taken: 1.8943510055541992 seconds
Dựa trên nội dung văn bản nhập vào, Paris có những viện bảo tàng chỉ lưu trữ tác phẩm của một danh nhân văn hóa bao gồm: bảo tàng Picasso, Không gian Dalí, bảo tàng Rodin, và bảo tàng Eugène Delacroix.
-----
Question 37: Vì sao ngành bất động sản ở La Défense phát triển rất mạnh?
Time taken: 3.143151044845581 seconds
Dựa trên nội dung văn bản nhập vào, tôi không đủ dữ kiện để đưa ra câu trả lời
-----
Question 38: Mitterrand đã có khoảng thời gian học tập 11 năm tại đâu?
Time taken: 2.637537956237793 seconds
Dựa trên nội dung văn bản nhập vào, tôi không đủ dữ kiện để đưa ra câu trả lời
-----
Question 39: Sắc lệnh ly khai khỏi hợp chúng quốc Hoa Kỳ được cử tri Texas chấp thuận khi nào?
Time taken: 1.602079153060913 seconds
Dựa trên nội dung văn bản nhập vào, Sắc lệnh ly khai khỏi Hợp chúng quốc Hoa Kỳ được các cử tri Texas chấp thuận vào ngày 23 tháng 2 năm 1861.
-----
Question 40: Thủ tướng John A.Macdonald đã ban hành chính sách về vấn đề gì để bảo đảm các ngành công nghiệp chế tạo phát triển?
Time taken: 1.7605366706848145 seconds
Dựa trên nội dung văn bản nhập vào, Thủ tướng John A. Macdonald đã ban hành "một chính sách quốc gia về thuế quan nhằm bảo hộ các ngành công nghiệp chế tạo còn non trẻ của Canada".
-----
Question 41: Nền văn hóa Okunev tại Mông Cổ đã xuất hiện trong khoảng thời gian nào?
Time taken: 1.8855383396148682 seconds
Dựa trên nội dung văn bản nhập vào, nền văn hóa Okunev tại Mông Cổ đã xuất hiện trong "thiên niên kỷ 2 TCN".
-----
Question 42: Vào năm nào thì sự tan rã của chủ nghĩa cộng sản đã diễn ra?
Time taken: 1.5339443683624268 seconds
Dựa trên nội dung văn bản nhập vào, sự sụp đổ của chủ nghĩa cộng sản đã diễn ra vào năm 1991.
-----
Question 43: Những nơi nào tại Texas thường bỏ phiếu cho người Cộng Hòa?
Time taken: 1.6070599555969238 seconds
Dựa trên nội dung văn bản nhập vào, hầu hết các khu vực nông thôn và ngoại ô ở Texas thường bỏ phiếu cho những người Cộng hòa.
-----
Question 44: Hai phe của cuộc chiến Ba mươi năm là ai?
Time taken: 9.928930759429932 seconds
Dựa trên nội dung văn bản nhập vào, khởi đầu cuộc chiến Ba mươi năm chủ yếu dựa trên xung đột tôn giáo giữa các phe nhóm Công giáo và Tin Lành. Dần dà, cuộc chiến lan rộng giữa một bên là những hoàng thân người Đức và bên kia chủ yếu là Thụy Điển và Pháp.
-----
Question 45: Khi de Gaulle trở lại, Mitterrand đã làm gì?
Time taken: 1.905130386352539 seconds
Dựa trên nội dung văn bản nhập vào, khi de Gaulle trở lại, Mitterrand đã "thay đổi sự đối lập của mình" và "quyết định đối đầu với Charles de Gaulle, Mitterrand đưa ra một lời kêu gọi bỏ phiếu "phản đối" trong cuộc trưng cầu dân ý về hiến pháp" vào tháng 9 năm 1958.
-----
Question 46: Những quốc gia nào tham vọng thiết lập chế độ chính trị đa đảng ở đất nước Uganda?
Time taken: 1.7289319038391113 seconds
Dựa trên nội dung văn bản nhập vào, các nước phương Tây và Mỹ muốn áp dụng chế độ đa đảng ở Uganda.
-----
Question 47: Bà nội của vị vua đất nước Mông Cổ giữa thế kỷ XVI tên là gì?
Time taken: 4.460602521896362 seconds
Dựa trên nội dung văn bản nhập vào, bà nội của A Nhĩ Thản Hãn, người lên nắm quyền ở Mông Cổ giữa thế kỷ XVI, là Mãn Đô Hải.
-----
Question 48: Texas khi thuộc về México đã được sắp xếp thuộc vào các tiểu bang nào?
Time taken: 1.7338323593139648 seconds
Dựa trên nội dung văn bản nhập vào, khi Texas thuộc về México, "México xếp khu vực là một phần của tiểu bang Coahuila và Tejas."
-----
Question 49: Cuộc sống gia đình của những người con của Roosevelt diễn ra như thế nào?
Time taken: 2.4632081985473633 seconds
Dựa trên nội dung văn bản nhập vào, cuộc sống gia đình của những người con của Roosevelt diễn ra như sau:
*   Một người con mất khi chưa tròn 1 tuổi.
*   Năm người con còn lại trải qua cuộc sống xáo trộn, bị lu mờ vì sự nổi tiếng của ông bố và bà mẹ.
*   Năm người này có tổng cộng 19 lần kết hôn, 15 lần ly dị và sinh 29 người con.
-----
Question 50: Tại Texas, số lượng người Cuba sinh sống là bao nhiêu?
Time taken: 1.542999029159546 seconds
Dựa trên nội dung văn bản nhập vào, có gần 38.000 người Cuba sinh sống tại Texas.
-----
Question 51: Vì sao lại có rất nhiều người Ireland di cư sang Canada?
Time taken: 1.517651081085205 seconds
Dựa trên nội dung văn bản nhập vào, rất nhiều người Ireland di cư sang Canada là do họ "chạy trốn Nạn đói lớn Ireland".
-----
Question 52: Gilles Kepel cho rằng cuộc chiến Vùng Vịnh đã gây ra một hậu quả nghiêm trọng là gì?
Time taken: 1.8708817958831787 seconds
Dựa trên nội dung văn bản nhập vào, Gilles Kepel cho rằng một hậu quả chủ chốt của Chiến tranh Vùng Vịnh là "sự hồi sinh rõ rệt của chủ nghĩa Hồi giáo cực đoan".
-----
Question 53: Nước thành viên của NATO có thể được tham gia vào các tổ chức nào?
Time taken: 2.140981912612915 seconds
Dựa trên nội dung văn bản nhập vào, một nước thành viên của NATO (như Canada) có thể tham gia vào các tổ chức quốc tế và liên chính phủ về kinh tế như G8, G20, Hiệp định Thương mại Tự do Bắc Mỹ, và Diễn đàn Hợp tác Kinh tế châu Á - Thái Bình Dương.
-----
Question 54: Hình ảnh nào được gắn liền với bang Texas?
Time taken: 2.063359022140503 seconds
Dựa trên nội dung văn bản nhập vào, hình ảnh được gắn liền với bang Texas là "hình ảnh cao bồi thể hiện trong phim Viễn Tây và nhạc đồng quê miền tây" và "các trùm tư bản dầu mỏ của bang".
-----
Question 55: Vì lí do gì mà đạo luật tiền thưởng khổng lồ được thông qua mặc cho sự phủ quyết của Roosevelt?
Time taken: 1.7171924114227295 seconds
Dựa trên nội dung văn bản nhập vào, đạo luật tiền thưởng khổng lồ được thông qua vào năm 1936 "vì sức ép của các cựu chiến binh", mặc dù bị Roosevelt phủ quyết.
-----
Question 56: Loài người xuất hiện sớm nhất ở nơi nào trong lãnh thổ của Canada?
Time taken: 1.6256861686706543 seconds
Dựa trên nội dung văn bản nhập vào, loài người xuất hiện sớm nhất tại bắc bộ khu vực Yukon từ 24.500 TCN.
-----
Question 57: Trong suốt thời chiến, tình hình trong nước của Hoa Kỳ như thế nào?
Time taken: 1.7249069213867188 seconds
Dựa trên nội dung văn bản nhập vào, trong suốt thời chiến, mặt trận trong nước của Hoa Kỳ có sự thay đổi xã hội rất năng động, và các vấn đề trong nước không còn là những mối quan tâm cấp thiết nhất của chính phủ Roosevelt.
-----
Question 58: Habsburg được lãnh đạo bởi những nhân vật nào?
Time taken: 1.501556634902954 seconds
Dựa trên nội dung văn bản nhập vào, thế giới Habsburg được lãnh đạo bởi "các giáo sĩ dòng Tên".
-----
Question 59: Các ca sĩ nổi tiếng của Pháp bắt đầu sự nghiệp từ những nơi nào ở Paris?
Time taken: 1.7709574699401855 seconds
Dựa trên nội dung văn bản nhập vào, các ca sĩ lớn của âm nhạc Pháp như Édith Piaf, Maurice Chevalier, Georges Brassens và Charles Aznavour đã từng tìm được danh tiếng ở những phòng hòa nhạc của Paris như: Bobino, Olympia, La Cigale hoặc Le Splendid.
-----
Question 60: Đơn vị tiền tệ được sử dụng tại Nouvelle-Calédonie là gì?
Time taken: 1.4795005321502686 seconds
Dựa trên nội dung văn bản nhập vào, đơn vị tiền tệ được sử dụng tại Nouvelle-Calédonie là franc CFP.
-----
Question 61: Mục đích của việc chính quyền thực hiện thanh toán cân bằng là gì?
Time taken: 1.8092310428619385 seconds
Dựa trên nội dung văn bản nhập vào, mục đích của việc chính phủ liên bang thực hiện thanh toán cân bằng là "nhằm bảo đảm các tiêu chuẩn thống nhất hợp lý về các dịch vụ và thuế được thi hành giữa các tỉnh giàu hơn và nghèo hơn."
-----
Question 62: Lý do nào đã khiến cho số nhân viên làm việc trong ngành báo chí tăng lên?
Time taken: 1.738084316253662 seconds
Dựa trên nội dung văn bản nhập vào, những cuộc cải cách thị trường đã dẫn tới sự gia tăng của số người làm việc trong ngành truyền thông sau từng năm, cùng với số lượng các sinh viên và trường báo chí.
-----
Question 63: Vào thời điểm Roosevelt nhậm chức, nước Mỹ đã và đang đối mặt với khó khăn gì?
Time taken: 4.1035072803497314 seconds
Dựa trên nội dung văn bản nhập vào, vào thời điểm Roosevelt nhậm chức (ngày 4 tháng 3 năm 1933), nước Mỹ đang ở thời điểm tồi tệ nhất của cuộc khủng hoảng lớn nhất trong lịch sử và đối mặt với các khó khăn sau:
*   Một phần tư lực lượng lao động mất việc làm.
*   Nông dân khốn đốn vì nông phẩm hạ giá 60%.
*   Sản xuất công nghiệp chỉ còn hơn một nửa so với cùng kỳ năm 1929.
*   Hai triệu người trở thành vô gia cư.
*   Các tổ chức tội phạm và giới sống ngoài pháp luật ngày càng gia tăng do thiếu việc làm.
*   Chiều ngày 4 tháng 3, tất cả ngân hàng tại 32 trên 48 tiểu bang cũng như Đặc khu Columbia đều đóng cửa.
*   Ngày 5 tháng 3, Ngân hàng Dự trữ Liên bang tại New York không thể mở cửa do khách hàng hốt hoảng rút một khối lượng lớn tiền mặt.
-----
Question 64: Nền khí hậu chủ đạo của Uganda là gì?
Time taken: 1.548461675643921 seconds
Dựa trên nội dung văn bản nhập vào, nền khí hậu chủ đạo của Uganda là "khí hậu xích đạo".
-----
Question 65: Thời điểm nào nhiệt độ Paris đạt mức cao nhất?
Time taken: 1.5956389904022217 seconds
Dựa trên nội dung văn bản nhập vào, nhiệt độ Paris đạt mức cao nhất vào ngày 28 tháng 6 năm 1948.
-----
Question 66: Ai đã kêu gọi người dân Paris không bỏ xứ trong cuộc tấn công của người Mông Cổ?
Time taken: 2.236341714859009 seconds
Dựa trên nội dung văn bản nhập vào, tôi không đủ dữ kiện để đưa ra câu trả lời
-----
Question 67: Thành phần chính của bộ lạc Ortoiroid tại đảo Puerto Rico là ai?
Time taken: 2.0046780109405518 seconds

Generate Sub Query Time Eval

In [6]:
import pandas as pd
data = pd.read_csv(r"E:\Downloads\projectcongty\Dataset\sent_truncated_dvc_train.csv", encoding='utf-16')
data = data.sample(frac=1, random_state=42)
from generate_subqueries_agent import run_generate_subqueries_agent
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, SystemMessagePromptTemplate
from langchain_core.messages import HumanMessage
from multi_agent import llm
from pydantic import BaseModel
from multi_agent import AgentState
import time
questions = data["noi_dung_hoi"].tolist()
sub_queries_list = []
questions_test = questions[:50]
times = []
import time 
for query in questions_test:
    state = AgentState(messages=[HumanMessage(content=query)])
    a = time.time()
    sub_queries = run_generate_subqueries_agent(state)
    b = time.time()
    print(f"Time taken for query '{query}': {b - a} seconds")
    print("------------------------------")
    times.append(b - a)

print(f"Average time for each query: {sum(times)/len(times)} seconds")

Time taken for query 'Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?': 3.5682120323181152 seconds
------------------------------
Time taken for query 'Xin cho hỏi thời hạn thanh toán trực tiếp chi phí khám, chữa bệnh bảo hiểm y tế tại cơ quan bảo hiểm xã hội là bao lâu?': 2.7636053562164307 seconds
------------------------------
Time taken for query 'Thời điểm lập Hồ sơ cấp giấy phép của các công trình thuộc đối tượng lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan trong khai thác, sử dụng tài nguyên nước sau khi quyết định việc đầu tư thì việc lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan tiến hành như thế nào và có cần phải công khai thông tin về những nội dung liên quan đến khai thác, sử dụng tài nguyên nước theo quy định?': 7.676631689071655 seconds
------------------------------
Time taken for query 'Trong trường hợp nào thì khai thác khoáng sản làm vật liệu xây dựng thông thường thông thường không phải xin giấy phép khai thác?': 4.0966956615448 seconds
------------------------------
Time taken for query 'Hồ sơ đề nghị góp ý đối với hồ sơ thiết kế cơ sở gồm những thành phần gì?': 5.117327451705933 seconds
------------------------------
Time taken for query 'Khi nộp hồ sơ đăng ký hoạt động chi nhánh, văn phòng đại diện thuộc ngân hàng thương mại, tôi được yêu cầu nộp bổ sung Nghị quyết của Đại hội đồng cổ đông về việc thành lập chi nhánh, văn phòng đại diện. Xin hỏi, yêu cầu này có đúng với quy định pháp luật hiện hành hay không?': 6.34926176071167 seconds
------------------------------
Time taken for query 'Hồ sơ đề nghị đổi thẻ nhà báo gồm những gì?': 4.095635175704956 seconds
------------------------------
Time taken for query 'Cơ quan Hải quan hay người khai hải quan có trách nhiệm tổ chức tham vấn trị giá hải quan?': 4.001158952713013 seconds
------------------------------
Time taken for query 'Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?': 3.3746025562286377 seconds
------------------------------
Time taken for query 'Tiền lương đóng bảo hiểm vào quỹ bảo hiểm tai nạn lao động, bệnh nghề nghiệp làm căn cứ tính hưởng chế độ tai nạn lao động được quy định như thế nào?': 8.087957859039307 seconds
------------------------------
Time taken for query 'Đề nghị làm rõ việc đánh dấu mẫu vật bằng “vật liệu khác” quy định tại khoản 2 Điều 34 Thông tư số 27/2018/TT-BNNPTNT là gì?': 4.298342943191528 seconds
------------------------------
Time taken for query 'Trong trường hợp tôi đã có văn bản làm căn cứ yêu cầu bồi thường và muốn yêu cầu cơ quan trực tiếp quản lý người thi hành công vụ gây thiệt hại bồi thường nhưng tôi không biết phải gửi hồ sơ yêu cầu bồi thường đến cơ quan nào thì tôi có thể đề nghị cơ quan nào xác định cơ quan giải quyết bồi thường giúp tôi?': 2.7647061347961426 seconds
------------------------------
Time taken for query 'Công ty tôi có nhu cầu xin cấp giấy phép bưu chính, vậy cho chúng tôi hỏi giấy phép bưu chính có thời hạn tối đa bao nhiêu năm?': 4.911801099777222 seconds
------------------------------
Time taken for query 'Năm tính thuế của nước cư trú của Tôi là từ ngày 01/4 đến ngày 31/3 năm sau, theo đó, Tôi sẽ không có được Giấy chứng nhận cư trú cho năm 2018 tại thời điểm nộp hồ sơ Thông báo áp dụng Hiệp định (vào tháng 3/2018). Với trường hợp của Tôi thì được giải quyết như thế nào?': 4.400797605514526 seconds
------------------------------
Time taken for query 'Theo quy định tại Khoản 3 Điều 16 Nghị định số 201/2013/NĐ-CP ngày 27/11/2013 của Chính phủ quy định chi tiết thi hành một số điều của Luật tài nguyên nước thì “xả nước thải của cá nhân, hộ gia đình thuộc trường hợp không phải xin cấp phép xả nước thải vào nguồn nước” và “xả nước thải của các cơ sở, sản xuất, kinh doanh dịch vụ với quy mô từ 05 m3/ngày đêm trở lên thuộc đối tượng phải cấp phép xả nước thải”. Tuy nhiên, phần hệ thống công trình hạ tầng kỹ thuật về xử lý, xả nước thải của khu căn hộ và dịch vụ thương mại không được tách riêng. Như vậy các Dự án tổ hợp thương mại, dịch vụ, căn hộ và chung cư có thuộc đối tượng phải xin cấp phép không?': 6.0441734790802 seconds
------------------------------
Time taken for query 'Tôi muốn biết sau bao lâu tôi sẽ được gia hạn hiệu lực VBBH?': 7.448013544082642 seconds
------------------------------
Time taken for query 'Điều kiện cấp Giấy chứng nhận đủ điều kiện hoạt động kiểm định kỹ thuật an toàn lao động đối với tổ chức gồm những gì?': 3.713047981262207 seconds
------------------------------
Time taken for query 'Thành phần hồ sơ và trách nhiệm lập hồ sơ đối với thương binh đang công tác trong Quân đội đề nghị giám định bổ sung vết thương còn sót?': 6.037138938903809 seconds
------------------------------
Time taken for query 'Ngân hàng Nhà nước Chi nhánh tỉnh thành phố có tiếp nhận và xử lý hồ sơ đăng ký khoản cho vay ra nước ngoài của tổ chức kinh tế trên địa bàn không?': 3.8453328609466553 seconds
------------------------------
Time taken for query 'Công ty của chúng  tôi mới được  cấp giấy chứng nhận đủ điều kiện  huấn luyện an toàn, vệ sinh lao động hạng B. Nay do Công ty chúng tôi thay đổi tên Công ty nên Công ty đã nộp hồ sơ đề nghị đổi tên Công ty trong giấy chứng nhận đủ điều kiện huấn luyện an toàn, vệ sinh lao động, vậy sau bao nhiêu ngày chúng tôi có thể nhận được giấy chứng nhận đổi tên?': 4.037064790725708 seconds
------------------------------
Time taken for query 'Tôi đang chuẩn bị hồ sơ để xin cấp giấy chứng nhận đủ điều kiện hoạt động huấn luyện an toàn, vệ sinh lao động lần đầu cho Công ty. Tôi xin hỏi hồ sơ cấp mới giấy chứng nhận đủ điều kiện hoạt động huấn luyện an toàn, vệ sinh lao động bao gồm những giấy tờ gì?': 4.074624061584473 seconds
------------------------------
Time taken for query 'Chi cục Hải quan có thực hiện tham vấn trị giá hải quan không?': 3.9421286582946777 seconds
------------------------------
Time taken for query 'Khi có thay đổi về tên, địa chỉ trụ sở chính, ngành, nghề kinh doanh, vốn điều lệ, người đại diện theo pháp luật thì liên hiệp hợp tác xã phải tiến hành thủ tục thay đổi gì với cơ quan quản lý liên hiệp hợp tác xã kể từ ngày Thông tư số 07/2019/TT-BKHĐT có hiệu lực thi hành ngày 28/5/2019?': 4.632546424865723 seconds
------------------------------
Time taken for query 'Cơ quan Hải quan hay người khai hải quan có trách nhiệm tổ chức tham vấn trị giá hải quan?': 3.9183120727539062 seconds
------------------------------
Time taken for query 'Vợ chồng ông N (trường trú tại xã Y, tỉnh A) được UBND xã X, tỉnh B giao tạm thời nuôi dưỡng trẻ em A bị bỏ rơi tại xã X. UBND xã X đã thực hiện đầy đủ các thủ tục pháp lý đối với trẻ em bị bỏ rơi theo quy định pháp luật. Sau khi nuôi dưỡng trẻ em được 2 tháng, vợ chồng ông N đã được UBND xã Y đăng ký việc nuôi con nuôi. Việc UBND xã Y đăng ký việc nuôi con nuôi trong trường hợp này có đúng không?': 5.584994077682495 seconds
------------------------------
Time taken for query 'Ai là người nộp hồ sơ thanh toán trực tiếp?': 5.441336393356323 seconds
------------------------------
Time taken for query 'Trong năm 2019, doanh nghiệp bảo hiểm muốn thay đổi phương pháp trích lập dự phòng bồi thường cho các dao động lớn về tổn thất áp dụng cho các nghiệp vụ bảo hiểm phi nhân thọ cho năm tài chính 2019? Doanh nghiệp bảo hiểm cần thực hiện thủ tục gì với Bộ Tài chính?': 5.073101758956909 seconds
------------------------------
Time taken for query 'Thời gian thực hành khám bệnh, chữa bệnh để cấp chứng chỉ hành nghề là gì?': 3.872441053390503 seconds
------------------------------
Time taken for query 'Thời hạn hiệu lực của Giấy phép chuyển đổi  thu, chi ngoại tệ và các hoạt động ngoại hối khác (đối với doanh nghiệp kinh doanh casino) là bao lâu?': 3.471365213394165 seconds
------------------------------
Time taken for query 'Tôi có thể đến nộp trực tiếp cho cơ quan có thẩm quyền hồ sơ xin cấp giấy  chứng nhận đủ điều kiện huấn luyện được không?': 3.7183775901794434 seconds
------------------------------
Time taken for query 'Khi thực hiện thủ tục xin giấy phép nhập khẩu hóa chất Bảng, doanh nghiệp cần nộp các hồ sơ gì? Thời gian xử lý hồ sơ là bao lâu.': 5.699104309082031 seconds
------------------------------
Time taken for query 'Thông báo việc không thụ lý giải quyết khiếu nại cho người khiếu nại biết khi cơ quan, tổ chức, cá nhân nhận được đơn khiếu nại thuộc một trong các trường hợp được quy định tại Điều 11 của Luật khiếu nại, được thực hiện như thế nào?': 4.714351177215576 seconds
------------------------------
Time taken for query 'Chi cục Hải quan có thực hiện tham vấn trị giá hải quan không?': 4.217269659042358 seconds
------------------------------
Time taken for query 'Mức đóng của học sinh sinh viên khi tham gia bảo hiểm y tế? Mức hỗ trợ từ Ngân sách nhà nước?': 4.911132574081421 seconds
------------------------------
Time taken for query 'Thời hạn tham vấn trị giá trị giá hải quan là bao nhiêu ngày?': 3.3535802364349365 seconds
------------------------------
Time taken for query 'Tôi hiện sinh sống tại khu vực giáp biên giới Trung Quốc. Tôi có thể mang xe ô tô cá nhân xuất cảnh, nhập cảnh qua cửa khẩu để vận chuyển hàng hóa hay không?': 3.8797566890716553 seconds
------------------------------
Time taken for query 'Hồ sơ đăng ký niêm yết trái phiếu của tổ chức phát hành nước ngoài trên Sở giao dịch chứng khoán tại Việt Nam bao gồm tài liệu gì?': 3.95477557182312 seconds
------------------------------
Time taken for query 'Công ty tôi muốn nộp hồ sơ xin cấp giấy đăng ký dịch vụ đào tạo an toàn bức xạ, hồ sơ bao gồm những gì?': 3.4520792961120605 seconds
------------------------------
Time taken for query 'Tổ chức, cá nhân nước ngoài nào được phép mang vũ khí thể thao vào, ra Việt Nam trong các trường hợp nào?': 4.027399301528931 seconds
------------------------------
Time taken for query 'Tôi muốn thực hiện Thông báo thay đổi địa điểm đặt trụ sở của Chi nhánh của Tổ chức trọng tài nước ngoài tại Việt Nam sang tỉnh, thành phố trực thuộc trung ương khác thì phải làm gì?': 3.853424310684204 seconds
------------------------------
Time taken for query 'Thành phần hồ sơ và trách nhiệm lập hồ sơ xác nhận thương binh đối với người đang công tác trong Quân đội bị thương từ ngày 31/12/1994 trở về trước còn lưu giữ được giấy tờ chứng minh bị thương, chưa được giám định thương tật?': 5.018848896026611 seconds
------------------------------
Time taken for query 'Tôi là người lao động tự do, làm thợ lặn và muốn được nhận hỗ trợ trực tiếp chi phí huấn luyện an toàn, vệ sinh lao động cho người làm công việc có yêu cầu nghiêm ngặt về an toàn, vệ sinh lao động thì phải thực hiện những thủ tục nào và phải nộp ở đâu?': 4.196902275085449 seconds
------------------------------
Time taken for query 'Công ty chúng tôi được phép khai thác khoáng sản làm vật liệu xây dựng thông thường thông thường trong dự án đầu tư xây dựng công trình và sản phẩm khai thác chỉ sử dụng cho công trình đó, công ty có phải nộp tiền cấp quyền khai thác khoáng sản sản không?': 6.553907871246338 seconds
------------------------------
Time taken for query 'Tổ chức chứng nhận tại Việt Nam là chi nhánh của tổ chức chứng nhận nước ngoài. Hiện nay, tổ chức chứng nhận tại Việt Nam không có chuyên gia đáp ứng yêu cầu quy định đối với các chương trình chứng nhận. Tuy nhiên, các chi nhánh của tổ chức chứng nhận nước ngoài có chuyên gia có kinh nghiệm đánh giá chứng nhận. Vậy, chi nhánh tại Việt Nam có được sử dụng các chuyên gia đánh giá của các chi nhánh khác để đăng ký hoạt động chứng nhận được không?': 4.812702894210815 seconds
------------------------------
Time taken for query 'Nguyên tắc công khai, minh bạch về tổ chức và hoạt động của cơ quan, tổ chức, đơn vị?': 4.687171220779419 seconds
------------------------------
Time taken for query 'Đối với cơ sở vừa sản xuất, vừa kinh doanh thực phẩm thì cơ sở được cấp mấy GCN?': 4.324395656585693 seconds
------------------------------
Time taken for query 'Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?': 3.9524450302124023 seconds
------------------------------
Time taken for query 'Thời điểm lập Hồ sơ cấp giấy phép của các công trình thuộc đối tượng lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan trong khai thác, sử dụng tài nguyên nước sau khi quyết định việc đầu tư thì việc lấy ý kiến đại diện cộng đồng dân cư, tổ chức, cá nhân liên quan tiến hành như thế nào và có cần phải công khai thông tin về những nội dung liên quan đến khai thác, sử dụng tài nguyên nước theo quy định?': 6.13311243057251 seconds
------------------------------
Time taken for query 'Khi nào tổ chức tín dụng, chi nhánh ngân hàng nước ngoài cần phải thực hiện thủ tục điều chỉnh thông tin ngân hàng?': 4.227446794509888 seconds
------------------------------
Time taken for query 'Chi cục Hải quan có thực hiện tham vấn trị giá hải quan không?': 5.371367692947388 seconds
------------------------------
Average time for each query: 4.634038181304931 seconds

Extract Law Agent Eval

In [13]:
import json
#read file E:\Downloads\projectcongty\Dataset\laws_100K.json
with open(r"C:\Users\Admin\Downloads\Project code\laws_first_100k.json", "r", encoding='utf-8') as f:
    laws_data = json.load(f)
# Convert to DataFrame
import pandas as pd
laws_df = pd.DataFrame(laws_data)

In [19]:
laws_df.iloc[79152][0]

'Điều 175 34/2016/NĐ-CP quy định chi tiết một số điều và biện pháp thi hành luật ban hành văn bản quy phạm pháp luật Sử dụng chuyên gia 1. Trong quá trình lập đề nghị xây dựng văn bản quy phạm pháp luật, soạn thảo, thẩm định, thẩm tra, Thủ trưởng các cơ quan, tổ chức, đơn vị được sử dụng chuyên gia có năng lực phù hợp với từng công việc. 2. Việc sử dụng chuyên gia phải theo các nguyên tắc sau: a) Được lựa chọn theo tiêu chí cụ thể cho từng công việc; b) Được thuê làm việc theo hợp đồng vụ việc; c) Nếu đã tham gia xây dựng nội dung chính sách, soạn thảo văn bản quy phạm pháp luật thì không tham gia thẩm định, thẩm tra đề nghị xây dựng văn bản quy phạm pháp luật, dự án, dự thảo văn bản quy phạm pháp luật đó. 3. Chuyên gia được hưởng các chế độ sau: a) Được nhận tiền thù lao theo thỏa thuận trong hợp đồng; b) Được cung cấp thông tin có liên quan trong quá trình thực hiện công việc của chuyên gia ghi trong hợp đồng; c) Được hỗ trợ chi phí tham dự hội nghị, hội thảo khoa học trong nước có nội dung phù hợp với công việc của chuyên gia ghi trong hợp đồng với mức hỗ trợ theo quy định hiện hành; d) Có quyền đề xuất phương thức thực hiện công việc của chuyên gia ghi trong hợp đồng phù hợp với yêu cầu chuyên môn của công việc đó; đ) Được khen thưởng và vinh danh xứng đáng với kết quả, cống hiến cho sự nghiệp xây dựng pháp luật và hoàn thiện hệ thống pháp luật Việt Nam. Chế độ ưu đãi đối với chuyên gia là người Việt Nam ở nước ngoài hoặc là người nước ngoài được áp dụng theo quy định về thu hút cá nhân hoạt động khoa học và công nghệ tại Việt Nam.'

In [2]:
# put the name of the column to rule
column_name = "rule"  # Replace with the actual column name you want to use for rules
def extract_rules_from_laws(df, column_name):
    rules = []
    for index, row in df.iterrows():
        if column_name in row and isinstance(row[column_name], str):
            rules.append(row[column_name])
    return rules
rules = extract_rules_from_laws(laws_df, column_name)

In [3]:
laws_df.rename(columns={0: "rules"}, inplace=True)

In [4]:
#tạo một cột index để đánh số thứ tự các luật
laws_df['index'] = laws_df.index

In [5]:
#chia thành 10 file json, mỗi file json chứa 10000 luật. Đặt tên file là laws_0.json, laws_1.json, ..., laws_9.json. lưu ra thư mục E:\Downloads\projectcongty\Dataset\laws_split
#lưu 2 cột, index (số thứ tự tương ứng của rule trong file gốc laws_100K.json) và rules (nội dung luật)
import os
output_dir = r"C:\Users\Admin\Downloads\Project code\datasets\laws_split"
os.makedirs(output_dir, exist_ok=True)
for i in range(10):
    start_index = i * 10000
    end_index = start_index + 10000
    laws_subset = laws_df.iloc[start_index:end_index]
    output_file = os.path.join(output_dir, f"laws_{i}.json")
    laws_subset.to_json(output_file, orient='records', force_ascii=False, lines=True)
    print(f"Saved {len(laws_subset)} laws to {output_file}")

Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_0.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_1.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_2.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_3.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_4.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_5.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_6.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_7.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_8.json
Saved 10000 laws to C:\Users\Admin\Downloads\Project code\datasets\laws_split\laws_9.json

In [7]:
#đọc lại file laws_0.json để kiểm tra xem đã lưu đúng chưa
import json
with open(r"C:\Users\Admin\Downloads\Project code\dataset\laws_split\laws_9.json", "r", encoding='utf-8') as f:
    laws_2_data = [json.loads(line) for line in f]

import pandas as pd
laws_2_df = pd.DataFrame(laws_2_data)
laws_2_df.head(5)

                                               rules  index
0  Điều 15 10/2014/NĐ-CP về điều lệ tổ chức và ho...  90000
1  Điều 16 10/2014/NĐ-CP về điều lệ tổ chức và ho...  90001
2  Điều 17 10/2014/NĐ-CP về điều lệ tổ chức và ho...  90002
3  Điều 18 10/2014/NĐ-CP về điều lệ tổ chức và ho...  90003
4  Điều 19 10/2014/NĐ-CP về điều lệ tổ chức và ho...  90004

In [20]:
from retrieve_laws_agent import run_retrieve_laws_agent
from generate_subqueries_agent import run_generate_subqueries_agent
from multi_agent import AgentState
from langchain_core.messages import HumanMessage
import pandas as pd

In [2]:
#test thử run_retrieve_laws_agent
state = AgentState(messages=[HumanMessage(content="Hiến Pháp Việt Nam")])
generated_subqueries = run_generate_subqueries_agent(state)
state["generated_subqueries"] = generated_subqueries
keys = run_retrieve_laws_agent(state)
print(keys)

[699, 1111, 959, 956, 780, 911, 732, 916, 1106, 1049]

In [3]:
data_test = pd.read_csv(r"C:\Users\Admin\Downloads\Project code\dataset\Kết quả Đánh giá model - Dataset trích xuất luật.csv")

In [4]:
data_test.head(5)

,Query,Answer,Lists of laws used
0,Trong công tác quản lý nhà nước và hỗ trợ hoạt...,"Theo quy định hiện hành, Ủy ban nhân dân cấp t...","[2427, 2428]"
1,Hãy so sánh khung hình phạt tù áp dụng cho 'Tộ...,"Theo quy định của Bộ luật Hình sự 2015, mức độ...","[10115, 10116, 10117, 10119]"
2,Một em bé 6 tuổi đang đứng chờ để băng qua một...,"Trong tình huống này, pháp luật quy định cụ th...","[22660, 22661, 29976]"
3,Tôi đang có dự định thành lập một cơ sở trợ gi...,"Để thành lập cơ sở trợ giúp trẻ em, bạn cần đá...","[30000, 30001, 30002]"
4,Ông Nguyễn Văn A là một nhà đầu tư cá nhân. Ôn...,Theo quy định tại khoản 1 Điều 35 Nghị định 15...,"[50084, 50007]"

In [6]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Query               102 non-null    object
 1   Answer              102 non-null    object
 2   Lists of laws used  102 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

In [7]:
queries = data_test["Query"].tolist()

In [8]:
#đổi định dạng cột "List of laws used" từ string thành list
import ast
laws_used = []
for law_list in data_test["Lists of laws used"].tolist():
    laws = ast.literal_eval(law_list)
    laws_used.append(laws)

In [44]:
print(len(laws_used))  #kiểm tra độ dài của laws_used
print(len(queries))  #kiểm tra độ dài của queries

102
102

In [45]:
import time
extracted_laws = []
times = []
for query in queries:
    state = AgentState(messages=[HumanMessage(content=query)])
    state["generated_subqueries"] = run_generate_subqueries_agent(state)
    a = time.time()
    keys = run_retrieve_laws_agent(state)
    b = time.time()
    print(f"Time taken for query: {b - a} seconds")
    times.append(b - a)
    print("------------------------------")
    extracted_laws.append(keys)
print(f"Average time for each query: {sum(times)/len(times)} seconds")

Time taken for query: 0.2276318073272705 seconds
------------------------------
Time taken for query: 0.18805146217346191 seconds
------------------------------
Time taken for query: 0.34168267250061035 seconds
------------------------------
Time taken for query: 0.29288220405578613 seconds
------------------------------
Time taken for query: 0.2828998565673828 seconds
------------------------------
Time taken for query: 0.3659780025482178 seconds
------------------------------
Time taken for query: 0.20931625366210938 seconds
------------------------------
Time taken for query: 0.19351410865783691 seconds
------------------------------
Time taken for query: 0.24759650230407715 seconds
------------------------------
Time taken for query: 0.20422053337097168 seconds
------------------------------
Time taken for query: 0.16798806190490723 seconds
------------------------------
Time taken for query: 0.14406275749206543 seconds
------------------------------
Time taken for query: 0.14385700225830078 seconds
------------------------------
Time taken for query: 0.14223408699035645 seconds
------------------------------
Time taken for query: 0.1387040615081787 seconds
------------------------------
Time taken for query: 0.1441042423248291 seconds
------------------------------
Time taken for query: 0.14960765838623047 seconds
------------------------------
Time taken for query: 0.14344120025634766 seconds
------------------------------
Time taken for query: 0.1451096534729004 seconds
------------------------------
Time taken for query: 0.16059446334838867 seconds
------------------------------
Time taken for query: 0.17434120178222656 seconds
------------------------------
Time taken for query: 0.14229536056518555 seconds
------------------------------
Time taken for query: 0.14439034461975098 seconds
------------------------------
Time taken for query: 0.14517951011657715 seconds
------------------------------
Time taken for query: 0.14239168167114258 seconds
------------------------------
Time taken for query: 0.14223790168762207 seconds
------------------------------
Time taken for query: 0.14296388626098633 seconds
------------------------------
Time taken for query: 0.17834091186523438 seconds
------------------------------
Time taken for query: 0.19722223281860352 seconds
------------------------------
Time taken for query: 0.14640235900878906 seconds
------------------------------
Time taken for query: 0.1525566577911377 seconds
------------------------------
Time taken for query: 0.17467665672302246 seconds
------------------------------
Time taken for query: 0.1441800594329834 seconds
------------------------------
Time taken for query: 0.14728713035583496 seconds
------------------------------
Time taken for query: 0.14663100242614746 seconds
------------------------------
Time taken for query: 0.146270751953125 seconds
------------------------------
Time taken for query: 0.14459919929504395 seconds
------------------------------
Time taken for query: 0.1445925235748291 seconds
------------------------------
Time taken for query: 0.19382977485656738 seconds
------------------------------
Time taken for query: 0.1830761432647705 seconds
------------------------------
Time taken for query: 0.17458081245422363 seconds
------------------------------
Time taken for query: 0.16952991485595703 seconds
------------------------------
Time taken for query: 0.1902942657470703 seconds
------------------------------
Time taken for query: 0.17935681343078613 seconds
------------------------------
Time taken for query: 0.24310827255249023 seconds
------------------------------
Time taken for query: 0.22043609619140625 seconds
------------------------------
Time taken for query: 0.16856932640075684 seconds
------------------------------
Time taken for query: 0.18417143821716309 seconds
------------------------------
Time taken for query: 0.17863035202026367 seconds
------------------------------
Time taken for query: 0.1737833023071289 seconds
------------------------------
Time taken for query: 0.2200624942779541 seconds
------------------------------
Time taken for query: 0.21648430824279785 seconds
------------------------------
Time taken for query: 0.18732619285583496 seconds
------------------------------
Time taken for query: 0.2293102741241455 seconds
------------------------------
Time taken for query: 0.17001914978027344 seconds
------------------------------
Time taken for query: 0.237473726272583 seconds
------------------------------
Time taken for query: 0.2200911045074463 seconds
------------------------------
Time taken for query: 0.21173739433288574 seconds
------------------------------
Time taken for query: 0.1727755069732666 seconds
------------------------------
Time taken for query: 0.1587238311767578 seconds
------------------------------
Time taken for query: 0.261521577835083 seconds
------------------------------
Time taken for query: 0.16923904418945312 seconds
------------------------------
Time taken for query: 0.17364168167114258 seconds
------------------------------
Time taken for query: 0.14444470405578613 seconds
------------------------------
Time taken for query: 0.14595603942871094 seconds
------------------------------
Time taken for query: 0.14178228378295898 seconds
------------------------------
Time taken for query: 0.1460866928100586 seconds
------------------------------
Time taken for query: 0.14083123207092285 seconds
------------------------------
Time taken for query: 0.14144325256347656 seconds
------------------------------
Time taken for query: 0.1487574577331543 seconds
------------------------------
Time taken for query: 0.14664626121520996 seconds
------------------------------
Time taken for query: 0.16904330253601074 seconds
------------------------------
Time taken for query: 0.22237324714660645 seconds
------------------------------
Time taken for query: 0.21796941757202148 seconds
------------------------------
Time taken for query: 0.22036051750183105 seconds
------------------------------
Time taken for query: 0.17779898643493652 seconds
------------------------------
Time taken for query: 0.17090940475463867 seconds
------------------------------
Time taken for query: 0.17477869987487793 seconds
------------------------------
Time taken for query: 0.1680889129638672 seconds
------------------------------
Time taken for query: 0.17797231674194336 seconds
------------------------------
Time taken for query: 0.17924952507019043 seconds
------------------------------
Time taken for query: 0.1759347915649414 seconds
------------------------------
Time taken for query: 0.1657707691192627 seconds
------------------------------
Time taken for query: 0.1915266513824463 seconds
------------------------------
Time taken for query: 0.1747608184814453 seconds
------------------------------
Time taken for query: 0.16993355751037598 seconds
------------------------------
Time taken for query: 0.17993402481079102 seconds
------------------------------
Time taken for query: 0.16855883598327637 seconds
------------------------------
Time taken for query: 0.17688846588134766 seconds
------------------------------
Time taken for query: 0.1670393943786621 seconds
------------------------------
Time taken for query: 0.17867374420166016 seconds
------------------------------
Time taken for query: 0.1668691635131836 seconds
------------------------------
Time taken for query: 0.18286442756652832 seconds
------------------------------
Time taken for query: 0.16773772239685059 seconds
------------------------------
Time taken for query: 0.17604398727416992 seconds
------------------------------
Time taken for query: 0.17215514183044434 seconds
------------------------------
Time taken for query: 0.17166519165039062 seconds
------------------------------
Time taken for query: 0.1851208209991455 seconds
------------------------------
Time taken for query: 0.17229390144348145 seconds
------------------------------
Time taken for query: 0.17251038551330566 seconds
------------------------------
Time taken for query: 0.17238187789916992 seconds
------------------------------
Time taken for query: 0.17104673385620117 seconds
------------------------------
Average time for each query: 0.18011775905010746 seconds

In [46]:
print(extracted_laws)
print(laws_used)

[[26113, 5752, 61479, 7610, 24043, 61616, 14040, 14079, 30986, 26120], [9796, 32195, 9768, 33062, 10115, 9809, 33063, 32885, 11398, 7787], [22690, 22649, 20681, 22658, 32145, 22655, 22693, 22657, 22659, 22697], [70593, 9035, 30000, 30004, 70552, 30002, 9023, 70590, 20780, 94635], [79704, 79689, 44871, 79698, 79683, 75318, 77467, 87412, 96120, 77465], [39992, 39967, 39996, 39974, 40011, 39979, 40040, 40067, 40041, 40074], [49755, 57337, 49727, 78334, 57332, 40832, 49728, 70155, 70110, 70136], [80094, 80091, 80065, 80095, 50922, 50924, 80071, 80090, 80066, 80068], [68346, 68348, 68351, 68352, 68353, 19149, 86745, 7598, 13660, 10455], [59554, 59553, 60704, 60734, 60712, 60719, 60692, 60728, 21702, 60706], [26350, 8928, 14076, 14053, 1835, 1834, 1833, 31377, 1798, 1855], [78835, 13335, 13336, 78832, 98410, 13338, 70310, 156, 78844, 70337], [70072, 2934, 2935, 82772, 96977, 75618, 73877, 75754, 8726, 61177], [21531, 21532, 89439, 21533, 21534, 21537, 59678, 86571, 89408, 89410], [84063, 84080, 84062, 84101, 84093, 84116, 30907, 19203, 30908, 84100], [5147, 6532, 9218, 9221, 9723, 18251, 15552, 10400, 15538, 61604], [84783, 26030, 16237, 84784, 83987, 2791, 55468, 2809, 2598, 81592], [30561, 30562, 30516, 6027, 9796, 23474, 6051, 9794, 30514, 23325], [20838, 20825, 20875, 20837, 29716, 23465, 86772, 9294, 66923, 19717], [92810, 57652, 57649, 78269, 57563, 85052, 22687, 9422, 65252, 22656], [19159, 4638, 85437, 85438, 4744, 19160, 11902], [58680, 58681, 75958, 93111, 93177, 58757, 58764, 93151, 93153, 93154], [71125, 87915, 85754, 85753, 87916, 86692, 87924, 86665, 47170, 86697], [57563, 78345, 78334, 80528, 96818, 86813, 57332, 93445, 22715, 43179], [23159, 23150, 23146, 13714, 24004, 22838, 322, 29838, 87164, 8920], [84005, 83992, 84003, 2716, 16183, 2817, 87166, 94414, 59369, 84021], [83104, 22524, 83052, 22339, 23445, 22512, 22353, 452, 453, 84658], [19568, 65923, 65925, 65926, 5316, 5314, 21565, 14576, 14571, 14572], [74703, 74673, 74704, 74715, 74723, 13520, 13510, 13517, 13484, 74735], [69302, 10782, 69304, 59718, 93632, 10666, 69307, 69298, 69271, 10684], [8262, 8301, 85063, 27834, 65204, 73111, 65741, 57563, 86171, 85055], [34923, 12093, 12345, 88912, 34897, 17298, 34952, 12225, 34896, 35599], [58579, 91872, 59757, 65869, 53855, 53742, 53768, 53778, 91775, 78076], [82172, 53428, 70293, 82170, 5300, 94506, 64399, 23959, 72785, 60993], [24810, 81065, 94622, 16014, 17916, 24787, 24789, 94628, 37749, 81161], [97568, 47933, 65372, 21524, 21472, 3259, 81907, 58838, 3285, 73370], [94142, 87467, 94020, 68106, 68090, 68130, 94107, 68101, 68126, 68107], [13877, 13886, 13869, 13891, 908, 10556, 29238, 23124, 10542, 65799], [62256, 72439, 62255, 72458, 72440, 72425, 72364, 72393, 72431, 72350], [34700, 29914, 34673, 70443, 91338, 91293, 47141, 91306, 91335, 91304], [92300, 99989, 99988, 92274, 99952, 67650, 20958, 20939, 56791, 67613], [10462, 15542, 15552, 10463, 18755, 15538, 9720, 5147, 22917, 15468], [68130, 94107, 68101, 68106, 68066, 68126, 81827, 94020, 94058, 37561], [63482, 53444, 57121, 334, 63475, 53441, 70046, 41646, 76471, 40968], [96584, 81873, 96602, 81844, 53564, 37635, 53579, 53580, 53565, 71626], [29594, 29598, 20141, 29528, 20263, 29499, 20209, 29600, 29651, 20129], [27756, 49159, 28482, 31000, 61616, 89468, 55144, 13940, 14077, 86082], [66329, 45237, 45232, 51277, 90347, 35239, 88781, 73366, 25448, 66330], [85466, 24764, 78876, 13350, 19270, 24763, 13370, 7974, 24762, 16056], [27787, 27794, 27813, 27823, 8279, 85283, 85282, 85285, 65860, 39886], [8738, 86030, 8737, 86032, 8740, 8717, 8673, 8669, 8726, 2935], [93569, 93582, 52713, 93555, 52774, 93608, 93557, 82973, 52707, 52715], [66783, 85527, 85525, 66782, 54912, 70176, 18247, 91587, 54907, 51709], [66704, 97538, 85667, 81970, 69708, 69765, 69712, 69702, 69690, 51644], [70497, 70498, 70499, 70500, 97364, 97760, 97762, 86772, 76424, 68038], [40655, 77468, 77471, 75382, 77464, 77469, 75983, 61179, 40654, 77481], [99028, 70838, 86458, 88879, 38336, 39496, 90153, 59410, 97677, 65121], [82179, 98349, 51316, 19317, 56334, 56340, 82052, 96655, 98346, 96656], [86630, 89959, 18168, 18172, 88876, 86627, 86602, 86633, 410, 61072], [24861, 22579, 38525, 96527, 76383, 65958, 96505, 38530, 37425, 44535], [86901, 86903, 86936, 51751, 51887, 94665, 29288, 79005, 23150, 79006], [28511, 20334, 98171, 4617, 20329, 98139, 98339, 28780, 25393, 98147], [14579, 19587, 98363, 98364, 98365, 70323, 24377], [92233, 41087, 92092, 92067, 41072, 75173, 40944, 92085, 97300, 97301], [75435, 60993, 19519, 72820, 72808, 19513, 64399, 72819, 82418, 94497], [19056, 19057, 19058, 19076, 23431], [85294, 65615, 57619, 85296, 85287, 39886, 78211, 57287, 85262, 57563], [54271, 54260, 54261, 54262, 54263, 20509, 54255, 54272, 83407, 4364], [99506, 8495, 51222, 63459, 63462, 8526, 84161, 12728, 65520, 76890], [37995, 48832, 37992, 37993, 37996, 38066, 77417, 77418, 37997, 54511], [94322, 27388, 84658, 12134, 23343, 10558, 94315, 48515, 84666, 23939], [9783, 18967, 98765, 9793, 828, 709, 10443, 11287, 713, 9807], [24313, 89521, 51568, 94506, 58792, 75424, 19149, 20487, 79974, 5229], [13478, 13495, 74698, 14082, 33703, 71849, 74753, 97189, 31582, 30983], [70744, 77479, 84191, 72887, 94008, 81570, 46805, 84799, 76200, 56219], [85519, 2773, 2767, 85505, 2765, 2772, 22787, 16196, 85496, 85498], [69315, 69354, 69333, 96793, 93328, 96825, 74787, 77273, 73542, 69256], [23158, 23972, 84166, 75572, 65889, 62039, 23073, 23965, 53193, 23952], [75983, 77482, 77483, 40675, 96925, 6594, 6600, 77485, 6631, 13143], [59176, 59182, 59224, 59225, 59226, 97962, 26407, 97956, 97899, 59165], [85462, 19128, 19235, 19289, 51374, 19249, 20780, 62439, 19316, 19252], [43468, 43469, 43471, 90264, 90265, 43383, 43384, 43390, 43391, 43392], [15813, 80823, 15814, 15816, 82884, 39581, 22301, 46607, 22827, 54319], [91537, 67483, 67423, 91447, 91413, 67360, 91416, 87467, 91504, 67347], [11432, 10499, 23755, 90578, 16382, 23810, 13481, 97158, 13520, 31412], [75517, 42748, 75529, 60850, 42749, 52421, 88400, 75531, 69898, 51172], [35347, 35239, 35449, 34538, 35283, 33842, 86494, 34984, 34078, 26422], [7895, 7896, 7903, 22024, 205, 64866, 186, 12633, 7887, 64893], [47864, 47904, 82240, 3800, 82269, 82279, 82196, 82291, 82223, 82191], [44081, 44077, 44085, 44087, 98764, 44088, 44069, 44080, 44071, 44084], [23127, 23088, 23093, 23128, 23087, 24969, 23080, 13778, 13727, 13721], [83727, 6845, 22178, 83692, 74718, 79625, 16792, 99201, 16808, 6882], [83241, 99489, 16800, 30850, 30811, 16890, 16808, 17067, 30834, 378], [35191, 35125, 35058, 15851, 34968, 27047, 57419, 12616, 15866, 12201], [15816, 15814, 15813, 15815, 80823, 15817, 80348, 80342, 15821, 14334], [19226, 20524, 5768, 70709, 53144, 20509, 53159, 20519, 14329, 22922], [17891, 8948, 45215, 54345, 76667, 96925, 19599, 69635, 54252, 82376], [8607, 8609, 8610, 8613, 8616, 8608, 8621, 8645, 37250, 8644], [13276, 13732, 13162, 15837, 13275, 3184, 24869, 3188, 10560, 11287], [85678, 88454, 72560, 75643, 88452, 88400, 91677, 51172, 69898, 69861], [8784, 17524, 52086, 8913, 8876, 11432, 52053, 8911, 23755, 73682], [42564, 43092, 38432, 39231, 40206, 82296, 44354, 57537, 41368, 82295]]
[[2427, 2428], [10115, 10116, 10117, 10119], [22660, 22661, 29976], [30000, 30001, 30002], [50084, 50007], [40000, 44335], [70110, 70133], [80091, 80019], [90004, 90013], [60703, 60704], [1778, 1779, 1780, 1781], [78835], [96978], [89425], [12579], [36412], [59931], [32629], [64989], [57698], [31825], [58752], [86703], [43663], [75217], [84003], [23445], [5314], [74711], [69301], [65209], [26988], [71739], [90274], [94623], [57178], [68086], [12891], [72350], [91294], [99989], [15542], [94131], [63482], [96571], [11163], [65214], [88781], [13347], [8279], [40196], [93558], [51709], [66709], [97767], [61179], [38337], [82070], [18172], [96505], [20759], [20330], [24377], [74979], [41945], [44668], [92802], [20507], [63452], [37996], [94332], [709], [28268], [13478], [76634], [85519], [96824], [23972], [40661], [26407], [85462], [3098], [4435], [67495], [90562], [60850], [76753], [27589], [82217], [98764], [79152], [22178], [16834], [57360], [15817], [22878], [45215], [71885], [23068], [69721], [8913], [37772]]

In [32]:
from retrieve_laws_agent import retrieve_laws
query = "Hồ sơ khai lệ phí trước bạ đối với tài sản là nhà, đất được nộp tại đâu?"
state = AgentState(messages=[HumanMessage(content=query)])
state["generated_subqueries"] = run_generate_subqueries_agent(state)
a = run_retrieve_laws_agent(state)
print(a)
for i in a:
    print(laws_df.iloc[i][0])

[75529, 42748, 75517, 60850, 52420, 52421, 75532, 88400, 75531, 17304]
Điều 10 140/2016/NĐ-CP về lệ phí trước bạ Khai, thu, nộp lệ phí trước bạ 1. Lệ phí trước bạ được khai theo từng lần phát sinh. Tổ chức, cá nhân có tài sản thuộc đối tượng chịu lệ phí trước bạ có trách nhiệm kê khai và nộp hồ sơ khai lệ phí trước bạ (gồm cả các trường hợp thuộc diện miễn lệ phí trước bạ theo quy định tại Điều 9 Nghị định này) cho Cơ quan Thuế khi đăng ký quyền sở hữu, quyền sử dụng với cơ quan nhà nước có thẩm quyền. 2. Nơi nộp hồ sơ khai lệ phí trước bạ - Đối với tài sản là nhà, đất: Hồ sơ khai lệ phí trước bạ nộp tại cơ quan tiếp nhận hồ sơ về giải quyết thủ tục đăng ký, cấp giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản khác gắn liền với đất theo quy định của pháp luật về đất đai. - Đối với tài sản khác: Hồ sơ khai lệ phí trước bạ nộp tại Chi cục Thuế địa phương nơi đăng ký quyền sở hữu, quyền sử dụng hoặc nộp qua Cổng thông tin điện tử của Tổng cục Thuế đối với hồ sơ khai thuế điện tử. 3. Hồ sơ khai lệ phí trước bạ a) Đối với tài sản là nhà, đất: - Tờ khai lệ phí trước bạ theo Mẫu số 01 Phụ lục ban hành kèm theo Nghị định này. - Các giấy tờ chứng minh tài sản (hoặc chủ tài sản) thuộc diện miễn lệ phí trước bạ (nếu có). b) Đối với tài sản khác (trừ tàu thuyền đánh cá, tàu thuyền vận tải thủy nội địa, tàu biển thiếu hồ sơ gốc hoặc đóng mới tại Việt Nam): - Tờ khai lệ phí trước bạ theo Mẫu số 02 Phụ lục ban hành kèm theo Nghị định này. - Các giấy tờ về mua bán, chuyển giao tài sản hợp pháp. - Giấy đăng ký quyền sở hữu, quyền sử dụng tài sản của chủ cũ (đối với tài sản đăng ký quyền sở hữu, quyền sử dụng tại Việt Nam từ lần thứ 2 trở đi).
Điều 9 10/2022/NĐ-CP quy định về lệ phí trước bạ Ghi nợ lệ phí trước bạ 1. Ghi nợ lệ phí trước bạ đối với đất và nhà gắn liền với đất của hộ gia đình, cá nhân thuộc đối tượng được ghi nợ tiền sử dụng đất theo quy định của pháp luật đất đai về thu tiền sử dụng đất. Khi thanh toán nợ lệ phí trước bạ thì hộ gia đình, cá nhân phải nộp lệ phí trước bạ tính theo giá nhà, đất do Ủy ban nhân dân tỉnh, thành phố trực thuộc trung ương quy định tại thời điểm kê khai lệ phí trước bạ. 2. Trường hợp hộ gia đình, cá nhân được ghi nợ lệ phí trước bạ theo quy định tại khoản 1 Điều này nếu chuyển nhượng, chuyển đổi, tặng cho quyền sở hữu nhà, quyền sử dụng đất cho tổ chức, cá nhân khác (trừ trường hợp tặng cho nhà, đất giữa các đối tượng quy định tại khoản 10 Điều 10 Nghị định này) thì phải nộp đủ số lệ phí trước bạ còn nợ trước khi chuyển nhượng, chuyển đổi, tặng cho. 3. Thủ tục ghi nợ lệ phí trước bạ a) Hộ gia đình, cá nhân thuộc đối tượng được ghi nợ lệ phí trước bạ nhà, đất nêu tại khoản 1 Điều này thực hiện khai lệ phí trước bạ và nộp hồ sơ khai lệ phí trước bạ theo quy định của pháp luật về quản lý thuế. b) Cơ quan có thẩm quyền cấp giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản gắn liền với đất kiểm tra hồ sơ, nếu xác định đúng đối tượng được ghi nợ lệ phí trước bạ nhà, đất nêu tại khoản 1 Điều này thì ghi vào giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản gắn liền với đất: “Nợ lệ phí trước bạ” trước khi cấp cho chủ sở hữu, sử dụng nhà, đất.
Điều 6 140/2016/NĐ-CP về lệ phí trước bạ Trường hợp phát sinh tài sản mà tại thời điểm nộp tờ khai lệ phí trước bạ chưa có trong Bảng giá tính lệ phí trước bạ do Bộ Tài chính ban hành thì Cơ quan Thuế áp dụng giá tính lệ phí trước bạ theo quy định tại điểm a khoản này để làm căn cứ tính lệ phí trước bạ. Trong thời hạn 3 ngày làm việc kể từ thời điểm tài sản được đăng ký trước bạ, Cơ quan Thuế báo cáo Bộ Tài chính để ban hành giá tính lệ phí trước bạ bổ sung. Trường hợp giá chuyển nhượng tài sản thực tế trên thị trường có biến động tăng hoặc giảm 20% trở lên so với giá tính lệ phí trước bạ tại Bảng giá tính lệ phí trước bạ thì Bộ Tài chính ban hành giá tính lệ phí trước bạ bổ sung đảm bảo giá tính lệ phí trước bạ sát với giá chuyển nhượng tài sản thực tế trên thị trường. Bộ Tài chính hướng dẫn thi hành quy định tại Điều này.
Điều 1 20/2019/NĐ-CP sửa đổi, bổ sung một số điều của nghị định số 140/2016/nđ-cp  ngày 10 tháng 10 năm 2016 của chính phủ về lệ phí trước bạ Nhà xưởng của cơ sở sản xuất; nhà kho, nhà ăn, nhà để xe của cơ sở sản xuất, kinh doanh. Nhà xưởng theo quy định tại khoản này được xác định theo pháp luật về phân cấp công trình xây dựng.” 4. Khoản 2, điểm a và điểm d khoản 3, điểm b khoản 4, khoản 5 Điều 10 được sửa đổi, bổ sung và bổ sung thêm khoản 7 vào Điều 10 như sau: a) Khoản 2 được sửa đổi, bổ sung như sau: “2. Nơi nộp hồ sơ khai lệ phí trước bạ a) Đối với tài sản là nhà, đất: hồ sơ khai lệ phí trước bạ nộp tại cơ quan tiếp nhận hồ sơ về giải quyết thủ tục đăng ký, cấp giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản khác gắn liền với đất theo quy định của pháp luật về đất đai. b) Đối với tài sản thuộc đối tượng chịu lệ phí trước bạ (trừ nhà, đất): Hồ sơ khai lệ phí trước bạ nộp tại Chi cục Thuế địa phương nơi đăng ký quyền sở hữu, quyền sử dụng, hoặc địa điểm do Ủy ban nhân dân tỉnh, thành phố trực thuộc trung ương quyết định trên cơ sở đề xuất của Cục trưởng Cục thuế, hoặc qua Cổng thông tin điện tử của Tổng cục Thuế đối với hồ sơ khai lệ phí trước bạ điện tử.” b) Khoản 3 được sửa đổi, bổ sung như sau: “a) Đối với tài sản là nhà, đất: - Bản chính Tờ khai lệ phí trước bạ theo Mẫu số 01 ban hành kèm theo Nghị định này. - Bản sao hợp lệ các giấy tờ chứng minh tài sản (hoặc chủ tài sản) thuộc diện miễn lệ phí trước bạ (nếu có), trừ trường hợp nộp bản chính theo quy định tại khoản 7 Điều này. - Bản sao hợp lệ giấy tờ chứng minh nhà, đất có nguồn gốc hợp pháp theo quy định của pháp luật. - Bản sao hợp lệ giấy tờ hợp pháp theo quy định của pháp luật về việc chuyển giao tài sản ký kết giữa bên giao tài sản và bên nhận tài sản.
Điều 10 126/2020/NĐ-CP quy định chi tiết một số điều của luật quản lý thuế Thời hạn nộp hồ sơ khai thuế của các khoản thu về đất, lệ phí môn bài, lệ phí trước bạ, tiền cấp quyền và các khoản thu khác theo pháp luật quản lý, sử dụng tài sản công Người nộp thuế thực hiện quy định về thời hạn nộp hồ sơ khai thuế theo quy định tại Điều 44 Luật Quản lý thuế. Đối với thời hạn nộp hồ sơ khai của các khoản thu về đất, lệ phí môn bài, lệ phí trước bạ, tiền cấp quyền và các khoản thu khác theo pháp luật quản lý, sử dụng tài sản công theo quy định tại khoản 5 Điều 44 Luật Quản lý thuế được thực hiện như sau: 1. Lệ phí môn bài a) Người nộp lệ phí môn bài (trừ hộ kinh doanh, cá nhân kinh doanh) mới thành lập (bao gồm cả doanh nghiệp nhỏ và vừa chuyển từ hộ kinh doanh) hoặc có thành lập thêm đơn vị phụ thuộc, địa điểm kinh doanh hoặc bắt đầu hoạt động sản xuất, kinh doanh thực hiện nộp hồ sơ khai lệ phí môn bài chậm nhất là ngày 30 tháng 01 năm sau năm thành lập hoặc bắt đầu hoạt động sản xuất, kinh doanh. Trường hợp trong năm có thay đổi về vốn thì người nộp lệ phí môn bài nộp hồ sơ khai lệ phí môn bài chậm nhất là ngày 30 tháng 01 năm sau năm phát sinh thông tin thay đổi. b) Hộ kinh doanh, cá nhân kinh doanh không phải nộp hồ sơ khai lệ phí môn bài. Cơ quan thuế căn cứ hồ sơ khai thuế, cơ sở dữ liệu quản lý thuế để xác định doanh thu làm căn cứ tính số tiền lệ phí môn bài phải nộp và thông báo cho người nộp lệ phí môn bài thực hiện theo quy định tại Điều 13 Nghị định này. 2. Lệ phí trước bạ Thời hạn nộp hồ sơ khai lệ phí trước bạ cùng với thời hạn nộp hồ sơ đăng ký quyền sở hữu, quyền sử dụng tài sản với cơ quan quản lý nhà nước có thẩm quyền (bao gồm cả trường hợp thực hiện theo cơ chế một cửa liên thông hoặc nộp trực tiếp tại cơ quan thuế).
Điều 10 126/2020/NĐ-CP quy định chi tiết một số điều của luật quản lý thuế Cơ quan thuế căn cứ hồ sơ khai thuế, cơ sở dữ liệu quản lý thuế để xác định doanh thu làm căn cứ tính số tiền lệ phí môn bài phải nộp và thông báo cho người nộp lệ phí môn bài thực hiện theo quy định tại Điều 13 Nghị định này. 2. Lệ phí trước bạ Thời hạn nộp hồ sơ khai lệ phí trước bạ cùng với thời hạn nộp hồ sơ đăng ký quyền sở hữu, quyền sử dụng tài sản với cơ quan quản lý nhà nước có thẩm quyền (bao gồm cả trường hợp thực hiện theo cơ chế một cửa liên thông hoặc nộp trực tiếp tại cơ quan thuế). 3. Thuế sử dụng đất phi nông nghiệp a) Đối với tổ chức: a.1) Kê khai lần đầu: Thời hạn nộp hồ sơ chậm nhất là 30 ngày kể từ ngày phát sinh nghĩa vụ thuế sử dụng đất phi nông nghiệp. a.2) Trong chu kỳ ổn định, hàng năm tổ chức không phải kê khai lại thuế sử dụng đất phi nông nghiệp nếu không có sự thay đổi về người nộp thuế và các yếu tố dẫn đến thay đổi số thuế phải nộp. a.3) Kê khai khi có phát sinh thay đổi các yếu tố làm thay đổi căn cứ tính thuế dẫn đến tăng, giảm số thuế phải nộp và khai bổ sung khi phát hiện hồ sơ khai thuế đã nộp cho cơ quan thuế có sai sót ảnh hưởng đến số thuế phải nộp: Thời hạn nộp hồ sơ chậm nhất là 30 ngày kể từ ngày phát sinh thay đổi. Khai bổ sung hồ sơ khai thuế được áp dụng đối với: Trường hợp phát sinh các yếu tố làm thay đổi căn cứ tính thuế dẫn đến tăng, giảm số thuế phải nộp; trường hợp phát hiện hồ sơ khai thuế đã nộp cho cơ quan thuế có sai sót, nhầm lẫn gây ảnh hưởng đến số thuế phải nộp. b) Đối với hộ gia đình, cá nhân: b.1) Khai lần đầu: Thời hạn nộp hồ sơ chậm nhất là 30 ngày kể từ ngày phát sinh nghĩa vụ thuế sử dụng đất phi nông nghiệp.
Điều 10 140/2016/NĐ-CP về lệ phí trước bạ Thông báo nộp lệ phí trước bạ đối với nhà, đất theo Mẫu số 03 Phụ lục ban hành kèm theo Nghị định này; Thông báo nộp lệ phí trước bạ đối với tài sản khác được ghi ngay trên Tờ khai nộp lệ phí trước bạ của tài sản đó. Trường hợp nộp hồ sơ khai lệ phí trước bạ qua Cổng thông tin điện tử của Tổng cục Thuế thì Thông báo nộp lệ phí trước bạ được Cổng thông tin điện tử của Tổng cục thuế trả về điện thoại, tài khoản giao dịch thuế điện tử hoặc thư điện tử của tổ chức, cá nhân theo từng mã giao dịch điện tử theo quy định về giao dịch điện tử trong lĩnh vực thuế. b) Người nộp lệ phí trước bạ thực hiện nộp tiền lệ phí trước bạ vào ngân sách nhà nước tại các cơ quan, tổ chức thu lệ phí trước bạ theo quy định của Luật quản lý thuế trong thời hạn 30 ngày làm việc kể từ ngày ký thông báo nộp lệ phí trước bạ của cơ quan thuế. 5. Việc lập và cấp chứng từ thu lệ phí trước bạ thực hiện theo quy định. Trường hợp tổ chức, cá nhân nộp lệ phí trước bạ qua ngân hàng bằng phương thức điện tử thì chứng từ nộp lệ phí trước bạ điện tử được ngân hàng truyền về Cổng thông tin điện tử của Tổng cục Thuế để ký số cung cấp cho các tổ chức, cơ quan có thẩm quyền đã kết nối thông tin với cơ quan thuế. Chứng từ điện tử được ký số là căn cứ để giải quyết thủ tục hành chính liên quan đến việc đăng ký tài sản và tổ chức, cá nhân không phải cung cấp chứng từ giấy. 6. Trường hợp quy trình phối hợp liên thông của các cơ quan quản lý nhà nước thực hiện thủ tục hành chính trong công tác cấp giấy chứng nhận quyền sở hữu, sử dụng tài sản có quy định khác về hồ sơ, thủ tục, quy trình thu, nộp lệ phí trước bạ thì thực hiện theo quy định đó. Bộ Tài chính hướng dẫn thi hành quy định tại Điều này.
Điều 29 46/2014/NĐ-CP quy định về thu tiền thuê đất, thuê mặt nước Bộ Tài nguyên và Môi trường có trách nhiệm Phối hợp với Bộ Tài chính để hướng dẫn hồ sơ, trình tự, thủ tục tiếp nhận, luân chuyển hồ sơ giữa cơ quan tài chính, cơ quan tài nguyên và môi trường, cơ quan thuế, kho bạc nhà nước các cấp để xác định và thu nộp tiền thuê đất, thuê mặt nước.
Điều 10 140/2016/NĐ-CP về lệ phí trước bạ d) Trường hợp hồ sơ khai lệ phí trước bạ điện tử là Tờ khai lệ phí trước bạ theo Mẫu số 01 (đối với tài sản là nhà, đất) và Mẫu số 02 (đối với tài sản khác) Phụ lục ban hành kèm theo Nghị định này, các giấy tờ hợp pháp kèm theo Tờ khai lệ phí trước bạ thực hiện theo quy định của các cơ quan cấp đăng ký khi làm thủ tục đăng ký cấp giấy chứng nhận quyền sở hữu, quyền sử dụng tài sản. 4. Thời hạn ra thông báo và nộp lệ phí trước bạ a) Chi cục Thuế ra thông báo nộp lệ phí trước bạ trong thời hạn 03 ngày làm việc (đối với tài sản là nhà, đất) hoặc 01 ngày làm việc đối với tài sản khác kể từ khi nhận đủ hồ sơ hợp lệ. Trường hợp hồ sơ không hợp lệ thì Chi cục Thuế trả lại hồ sơ cho cơ quan tiếp nhận hồ sơ về giải quyết thủ tục đăng ký, cấp giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản khác gắn liền với đất theo quy định của pháp luật về đất đai (đối với hồ sơ lệ phí trước bạ nhà, đất) hoặc cho người có tài sản (đối với hồ sơ lệ phí trước bạ tài sản khác) theo thời hạn quy định tại điểm này. Thông báo nộp lệ phí trước bạ đối với nhà, đất theo Mẫu số 03 Phụ lục ban hành kèm theo Nghị định này; Thông báo nộp lệ phí trước bạ đối với tài sản khác được ghi ngay trên Tờ khai nộp lệ phí trước bạ của tài sản đó. Trường hợp nộp hồ sơ khai lệ phí trước bạ qua Cổng thông tin điện tử của Tổng cục Thuế thì Thông báo nộp lệ phí trước bạ được Cổng thông tin điện tử của Tổng cục thuế trả về điện thoại, tài khoản giao dịch thuế điện tử hoặc thư điện tử của tổ chức, cá nhân theo từng mã giao dịch điện tử theo quy định về giao dịch điện tử trong lĩnh vực thuế.
Điều 109 45/2013/QH13 đất đai Nộp tiền sử dụng đất, tiền thuê đất khi chuyển mục đích sử dụng đất, gia hạn sử dụng đất

In [36]:
from retrieve_laws_agent import retrieve_laws

extracted_laws_2 = []
for query in queries:
    a = retrieve_laws({"query": query})
    extracted_laws_2.append(a)
    print(a)

print(len(extracted_laws_2))

[61479, 14079, 24043, 14007, 15436, 14077, 7610, 31020, 61616, 89468]
[11398, 32195, 9796, 9768, 9818, 32885, 9789, 10333, 33198, 9076]
[22690, 22649, 22655, 22697, 22661, 22658, 22659, 20681, 32148, 22693]
[30002, 20780, 15730, 30000, 20797, 20782, 9023, 20785, 30004, 98964]
[75318, 96120, 50007, 50013, 50034, 50037, 50045, 50047, 50049, 50061]
[39992, 39996, 40011, 40040, 40041, 40042, 40043, 40044, 40045, 40051]
[70155, 70110, 70136, 57266, 57272, 57275, 57276, 57279, 57280, 57281]
[80091, 80094, 80065, 80095, 80105, 80085, 80092, 80063, 80071, 80100]
[68346, 68348, 68351, 68352, 68353, 68354, 68355, 68356, 68357, 68358]
[59554, 60734, 59553, 46326, 60704, 60731, 60719, 94161, 59094, 44372]
[1798, 1855, 1886, 1806, 1811, 1813, 1789, 1807, 1787, 1800]
[98410, 70310, 70337, 98411, 20637, 70314, 4824, 98412, 98418, 70313]
[70072, 96977, 82772, 41345, 22832, 82771, 75618, 70075, 70076, 39963]
[21531, 21532, 21533, 21534, 21537, 21540, 21541, 89412, 89421, 89424]
[84063, 84080, 30907, 30908, 84093, 12579, 84062, 84101, 84116, 84100]
[5147, 6532, 9218, 9221, 9723, 10425, 10473, 11428, 15443, 15445]
[84783, 83987, 26030, 2791, 16237, 84784, 75205, 81592, 75204, 98851]
[6027, 30561, 30562, 6031, 30516, 6045, 6047, 30710, 6046, 5178]
[20838, 9294, 23465, 6539, 18782, 60402, 6559, 19844, 23459, 19717]
[92810, 78269, 57649, 92724, 57652, 78163, 92729, 57619, 57553, 92725]
[4638, 85438, 85437, 19159, 19160, 4744, 4653, 4655, 4692, 51266]
[58757, 58764, 93151, 93153, 93154, 93157, 93158, 93148, 93149, 93150]
[87916, 85754, 71125, 85753, 87915, 86674, 86692, 87924, 84578, 86703]
[57563, 80528, 80526, 80527, 96818, 96815, 92782, 96814, 96820, 80524]
[24004, 87164, 6850, 83838, 33769, 24039, 24010, 61656, 39167, 39169]
[84005, 83992, 84003, 2716, 16183, 16184, 2712, 55451, 25978, 84021]
[83052, 452, 23446, 99009, 22334, 12000, 430, 83105, 95240, 83132]
[5314, 19568, 65923, 65925, 65926, 5316, 21565, 14571, 65921, 65922]
[74703, 74673, 74704, 74715, 74723, 13443, 13485, 13486, 72635, 72636]
[69302, 69304, 69307, 69298, 69271, 69269, 96763, 69306, 69297, 96753]
[85063, 86171, 62017, 8270, 71434, 69248, 86170, 27834, 69249, 86169]
[12345, 12225, 12193, 34950, 12240, 12226, 12258, 12149, 12228, 12221]
[53742, 53768, 53778, 91775, 91804, 91807, 91859, 91797, 91768, 91814]
[82172, 53428, 5300, 70293, 82170, 46213, 46160, 46203, 46217, 46143]
[24810, 81065, 16014, 24787, 79207, 94622, 16018, 16016, 71454, 77933]
[97568, 81907, 81216, 81905, 90849, 45559, 93994, 22985, 91216, 81232]
[94142, 68126, 94020, 68106, 94079, 68067, 68081, 68105, 68099, 68102]
[13886, 13877, 13891, 908, 10556, 13795, 10514, 20783, 23124, 13895]
[62256, 72440, 72458, 62255, 72439, 72433, 72424, 72393, 72350, 72387]
[29914, 34673, 34700, 91338, 91293, 18377, 47112, 16741, 47149, 34715]
[99989, 92300, 99988, 92274, 99952, 99981, 63309, 92314, 99983, 99984]
[10462, 5147, 6532, 9218, 9221, 9723, 10425, 10473, 11428, 15443]
[68106, 68130, 94142, 68126, 94079, 67159, 68066, 68101, 94058, 94059]
[63482, 41646, 67631, 53438, 72866, 14310, 20965, 6346, 86429, 63481]
[96584, 96602, 71644, 53579, 53580, 53581, 53582, 53584, 53587, 53589]
[29594, 29598, 29528, 20263, 29499, 20209, 29651, 29520, 30681, 20141]
[27756, 28482, 49159, 14077, 15436, 24481, 24043, 83438, 8064, 61479]
[66329, 45237, 45232, 51277, 90347, 48586, 60492, 60503, 26478, 16730]
[85466, 19270, 24764, 13350, 78876, 13363, 24762, 51892, 24763, 85471]
[8279, 27787, 27794, 27813, 27823, 27827, 27830, 27831, 27835, 27836]
[8737, 86030, 86032, 8738, 8740, 86029, 86031, 8682, 8703, 29149]
[93569, 93582, 52713, 93558, 93571, 52741, 93583, 52758, 93572, 93593]
[66783, 85525, 66782, 85527, 67688, 39886, 85528, 67696, 53563, 8355]
[81970, 69690, 85667, 97538, 69765, 69712, 81969, 69725, 51582, 51585]
[97760, 97762, 86772, 76424, 68038, 76446, 86767, 76425, 98045, 55480]
[61179, 75382, 40655, 77471, 77468, 77464, 40654, 77481, 77470, 97498]
[70838, 99028, 39496, 38337, 38336, 70837, 89982, 97677, 71486, 99029]
[96656, 56334, 56340, 82052, 96655, 96658, 96659, 96667, 96668, 96677]
[89959, 88876, 18172, 86630, 86602, 39480, 87275, 87276, 86445, 69398]
[96527, 44535, 96505, 65958, 96523, 65953, 96499, 96501, 96504, 96512]
[86901, 86903, 86936, 51751, 51887, 94722, 51725, 51729, 55503, 87169]
[20329, 28511, 98147, 98145, 98171, 98139, 20332, 20334, 4617, 20331]
[14579, 19587, 98363, 98364, 98365, 98366, 98367, 98368, 98372, 98373]
[92233, 92067, 75173, 75187, 92234, 75188, 92064, 92235, 75172, 92231]
[19513, 19519, 75435, 18282, 33548, 14499, 57852, 94500, 24329, 64375]
[19056, 19057, 19058, 19076, 23431, 44639, 44640, 44641, 44642, 44643]
[57619, 78211, 78245, 57795, 57625, 44404, 57649, 57612, 57621, 92777]
[54271, 54260, 54261, 54262, 54263, 54264, 54265, 54266, 54267, 54268]
[51222, 8495, 8526, 68732, 99506, 63462, 68717, 8528, 63459, 51228]
[37995, 38066, 37994, 77417, 77418, 48832, 37992, 37996, 37997, 37998]
[94322, 94315, 94390, 94335, 94313, 94393, 94389, 94386, 42150, 94388]
[709, 713, 729, 828, 886, 1031, 1118, 997, 9179, 97901]
[24313, 89521, 24322, 94506, 20669, 81109, 24296, 94404, 24312, 24300]
[71849, 31582, 13433, 74697, 74719, 74669, 74759, 74758, 74702, 74721]
[70744, 72887, 84191, 94008, 68686, 98628, 71159, 83424, 56232, 80049]
[85519, 2773, 2767, 85505, 22787, 2765, 16196, 85498, 85496, 16256]
[69315, 69354, 69333, 69355, 96793, 69329, 96767, 69307, 96830, 93328]
[23158, 23972, 65889, 23073, 84166, 10474, 38298, 84173, 23955, 90558]
[40675, 96925, 75983, 77482, 77483, 77485, 77486, 77487, 40655, 77462]
[59176, 59182, 59224, 59225, 59226, 59227, 59228, 59229, 59238, 59239]
[85462, 19128, 19289, 19287, 19235, 19282, 19283, 19306, 4745, 4750]
[43468, 43469, 43471, 90264, 90265, 90287, 90292, 90306, 90308, 90309]
[39581, 46607, 54319, 54324, 54325, 54326, 80341, 46608, 54335, 15783]
[91537, 67360, 91416, 67423, 67483, 67347, 67348, 67349, 67350, 67353]
[10499, 23755, 11432, 90578, 16382, 13096, 89717, 38876, 90559, 90577]
[75529, 42748, 60850, 75517, 52420, 52436, 75532, 75521, 42749, 52421]
[35347, 34984, 35239, 25448, 35449, 22996, 35341, 36215, 42733, 34987]
[7895, 7896, 7903, 22024, 27574, 22022, 22025, 12635, 27589, 4736]
[82240, 3800, 82196, 82223, 82224, 82228, 82232, 82264, 82282, 82283]
[44081, 98764, 44077, 44085, 44087, 44080, 44088, 44089, 44084, 44086]
[24969, 13721, 23058, 23066, 23064, 13726, 23065, 4571, 69217, 78981]
[83727, 6845, 83692, 22178, 79625, 24893, 16792, 24909, 99214, 74718]
[30850, 30834, 30809, 16800, 30861, 30802, 30800, 22184, 16882, 16867]
[15851, 15866, 8929, 14051, 10538, 793, 12967, 774, 15897, 15856]
[15816, 15814, 15813, 15815, 80823, 86771, 51288, 54879, 44793, 46606]
[19226, 20519, 5768, 22914, 70709, 20467, 14329, 5289, 22898, 22885]
[17891, 45215, 8948, 54345, 22286, 39146, 8959, 76200, 25002, 54344]
[8607, 8609, 8610, 8613, 8616, 8619, 8645, 8621, 8644, 8614]
[13276, 13732, 15837, 13162, 13275, 3184, 12884, 12887, 28427, 773]
[88454, 85678, 88452, 69890, 75643, 91677, 88397, 69861, 90454, 7446]
[11432, 23755, 10499, 13096, 16382, 31540, 89717, 52053, 79666, 18882]
[42564, 43092, 39231, 40206, 39940, 44890, 38432, 37939, 45341, 39911]
102

In [59]:
precisions = []
recalls = []
for output_laws, actual_laws in zip(extracted_laws_2, laws_used):
    output_laws = output_laws[:10]
    tp = set(output_laws) & set(actual_laws)
    fp = set(output_laws) - set(actual_laws)
    fn = set(actual_laws) - set(output_laws)
    precision = len(tp) / (len(tp) + len(fp)) if (len(tp) + len(fp)) > 0 else 0
    recall = len(tp) / (len(tp) + len(fn)) if (len(tp) + len(fn)) > 0 else 0
    print(f"Precision: {precision}, Recall: {recall}")
    precisions.append(precision)
    recalls.append(recall)
    print("-----")
average_precision = sum(precisions) / len(precisions) if precisions else 0
average_recall = sum(recalls) / len(recalls) if recalls else 0
print(f"Average Precision: {average_precision}, Average Recall: {average_recall}")

Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 0.3333333333333333
-----
Precision: 0.2, Recall: 0.6666666666666666
-----
Precision: 0.1, Recall: 0.5
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 0.5
-----
Precision: 0.1, Recall: 0.5
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 0.5
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.1, Recall: 1.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Precision: 0.0, Recall: 0.0
-----
Average Precision: 0.029411764705882353, Average Recall: 0.2549019607843137

In [58]:
reciprocal_ranks = []
for output_laws, true_laws in zip(extracted_laws_2, laws_used):
    output_laws = output_laws[:10]
    rank = 0
    for i,law in enumerate(output_laws,1):
        if law in true_laws:
            rank = i
            break
    if rank > 0:
        reciprocal_rank = 1 / rank
        print(f"Reciprocal Rank: {reciprocal_rank}")
        reciprocal_ranks.append(reciprocal_rank)
    else:
        print("Reciprocal Rank: 0")
        reciprocal_ranks.append(0)
    print("-----")
average_reciprocal_rank = sum(reciprocal_ranks) / len(reciprocal_ranks) if reciprocal_ranks else 0
print(f"Average Reciprocal Rank: {average_reciprocal_rank}")

Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.2
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0.3333333333333333
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.5
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.2
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.16666666666666666
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.1
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.3333333333333333
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.1111111111111111
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.25
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0.25
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.3333333333333333
-----
Reciprocal Rank: 0.3333333333333333
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.125
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.5
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 1.0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.3333333333333333
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.1111111111111111
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.5
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.25
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0.5
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Reciprocal Rank: 0
-----
Average Reciprocal Rank: 0.15127995642701525

In [57]:
#calculate average precision
average_precisions = []
for output_laws, actual_laws in zip(extracted_laws_2, laws_used):
    output_laws = output_laws[:10]
    total_precision_k = 0
    for i, law in enumerate(output_laws,1):
        first_k_laws = output_laws[:i]
        tp = set(first_k_laws) & set(actual_laws)
        precision_at_k = len(tp) / i if i > 0 else 0
        rel_k = 1 if law in actual_laws else 0
        total_precision_k += precision_at_k * rel_k
    average_precision = total_precision_k/len(actual_laws) if len(actual_laws) > 0 else 0
    print(f"Average Precision: {average_precision}")
    average_precisions.append(average_precision)
    print("-----")

average_of_average_precisions = sum(average_precisions) / len(average_precisions) if average_precisions else 0
print(f"Mean Average Precision (MAP): {average_of_average_precisions}")

Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.06666666666666667
-----
Average Precision: 0.5
-----
Average Precision: 0.16666666666666666
-----
Average Precision: 0.0
-----
Average Precision: 0.25
-----
Average Precision: 0.5
-----
Average Precision: 0.0
-----
Average Precision: 0.1
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.16666666666666666
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.1
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.3333333333333333
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.1111111111111111
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.25
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.25
-----
Average Precision: 0.0
-----
Average Precision: 0.3333333333333333
-----
Average Precision: 0.3333333333333333
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.125
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.5
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 1.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.3333333333333333
-----
Average Precision: 0.0
-----
Average Precision: 0.1111111111111111
-----
Average Precision: 0.0
-----
Average Precision: 0.5
-----
Average Precision: 0.0
-----
Average Precision: 0.25
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.5
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Average Precision: 0.0
-----
Mean Average Precision (MAP): 0.13510348583877996

Time Eval Classifer Based Agent

In [19]:
from router_agent import run_router_agent
import pandas as pd
import time as time
from multi_agent import AgentState
from langchain_core.messages import HumanMessage
sentences = pd.read_csv(r"C:\Users\Admin\Downloads\Project code\dataset\results_for_router_matching_based.csv")
sentences = sentences["query"].tolist()
print(len(sentences))
total_time = 0
for i, sentence in enumerate(sentences,1):
    state = {"messages": [HumanMessage(content=sentence)]}
    start_time = time.time()
    route = run_router_agent(state)
    end_time = time.time()
    elapsed_time = end_time - start_time
    total_time += elapsed_time
    print(f"Query {i}: {sentence}")
    print(f"Decided route: {route}")

print(f"Average time per query: {total_time / len(sentences):.4f} seconds")

2000
Query 1: Công ty của chúng  tôi mới được  cấp giấy chứng nhận đủ điều kiện  huấn luyện an toàn, vệ sinh lao động hạng B. Nay do Công ty chúng tôi thay đổi tên Công ty thì chúng tôi có phải làm thủ tục đối tên Công ty trên giấy chứng nhận đã được cấp không? Và thành phần hồ sơ cần phải nộp bao gồm những giấy tờ gì?
Decided route: extract_laws
Query 2: Augustus tự nhận mình là gì?
Decided route: documents
Query 3: Em của tôi đã mất, nay liên quan đến việc phân chia di sản thừa kế của gia đình cần phải có giấy xác nhận việc em tôi còn độc thân. Vậy UBND cấp xã có thẩm quyền cấp giấy này cho em tôi không?
Decided route: extract_laws
Query 4: Nguyên lão có thể bị cách chức nếu vi phạm điều gì?
Decided route: extract_laws
Query 5: Sau khi nộp hồ sơ công nhận hạng cơ sở lưu trú du lịch thì khi nào khách sạn tôi được thẩm định xếp hạng?
Decided route: extract_laws
Query 6: Điều kiện xác nhận nội dung quảng cáo mỹ phẩm là gì?
Decided route: extract_laws
Query 7: Adam Smith dành nhiều thời gian trong Thư viện Anh để làm gì?
Decided route: documents
Query 8: Thời hạn tham vấn trị giá trị giá hải quan là bao nhiêu ngày?
Decided route: extract_laws
Query 9: Kính viễn vọng cải tiến của Kepler có gì nổi trội hơn kính viễn vọng của Galileo?
Decided route: documents
Query 10: Để được cấp phép cho người Việt Nam định cư ở nước ngoài, tổ chức, cá nhân nước ngoài tiến hành nghiên cứu, sưu tầm di sản văn hóa phi vật thể từ hai tỉnh, thành phố trực thuộc trung ương trở lên, cần phải nộp những loại giấy tờ gì?
Decided route: extract_laws
Query 11: Các đội bóng nổi tiếng ở Mali tập trung chủ yếu ở đâu?
Decided route: documents
Query 12: Có thể sử dụng từ “tập đoàn” để đặt tên doanh nghiệp hay không?
Decided route: documents
Query 13: Quy trình tiếp công dân được thực hiện như thế nào?
Decided route: documents
Query 14: Ở bộ môn bóng đá, Malaysia đang có những việc làm gì trong nỗ lực phát triển nền bóng đá nước nhà?
Decided route: documents
Query 15: Theo Living Planet Report, nguồn tài nguyên sinh vật phải tăng lên bao nhiêu lần mới đủ cho nhu cầu của con người?
Decided route: documents
Query 16: Bồ Đào Nha còn có những cộng đồng tín đồ nào?
Decided route: documents
Query 17: Wifi xuất hiện đầu tiên ở quốc gia nào?
Decided route: documents
Query 18: Tại sao việc Phạm Văn Đồng sử dụng phiên dịch người Trung Quốc tại cuộc đàm phán là sai lầm?
Decided route: documents
Query 19: Xin cho biết sau khi lập Hồ sơ lập phương án ứng phó với tình huống khẩn cấp, tổ chức, cá nhân khai thác công trình thủy lợi cần gửi Hồ sơ đến cơ quan nào để thẩm định?
Decided route: extract_laws
Query 20: Thủ tục cấp giấy phép mang vũ khí thể thao để luyện tập, thi đấu thể thao; triển lãm, trưng bày, chào hàng, giới thiệu sản phẩm; làm đạo cụ trong hoạt động văn hóa, nghệ thuật thì thực hiện như thế nào?
Decided route: extract_laws
Query 21: Vì sao đảng Đại Việt lại bị lộ ra bằng chứng về kế hoạch hợp tác với Pháp?
Decided route: documents
Query 22: Tôi muốn xin miễn thuế nhập khẩu đối với hàng hóa nhập khẩu phục vụ nghiên cứu khoa học, phát triển công nghệ. Tôi cần chuẩn bị hồ sơ gồm những gì?
Decided route: extract_laws
Query 23: Hồ sơ đề nghị khen thưởng đột xuất có biên bản họp Hội đồng TĐKT của đơn vị không?
Decided route: extract_laws
Query 24: Công ty in chúng tôi sản xuất sách hướng dẫn sử dụng máy móc, thiết bị. Vậy Quý cơ quan quản lý nhà nước cho hỏi Công ty chúng tôi có phải có giấy phép hoạt động in không?
Decided route: extract_laws
Query 25: Trong quá trình cải tạo lại khu vườn sau nhà, tôi có phát hiện 01 bình gốm và được cơ quan chức năng xác định là cổ vật. Tôi đã giao nộp cho nhà nước. Vậy tôi được hưởng quyền lợi gì?
Decided route: extract_laws
Query 26: Vấn đề nào thường xuyên xảy ra tại Đại Minh vào giai đoạn trung kỳ trở về sau?
Decided route: documents
Query 27: Bố tôi đi bộ đội, chiến đấu ở chiến trường Campuchia, hy sinh năm 1977, hài cốt đã được đơn vị đưa về an táng trong Nghĩa trang liệt sĩ huyện Tân Biên, tỉnh Tây Ninh. Tuy nhiên, gia đình tôi chưa nhận được thông tin báo tử của đơn vị, cũng chưa được hưởng chế độ gì. Tôi muốn đề nghị xác nhận liệt sĩ cho bố tôi, xin hỏi thủ tục thực hiện như thế nào?
Decided route: extract_laws
Query 28: Ai đã giới thiệu những máy in ép tới Anh vào năm 1476?
Decided route: documents
Query 29: Ngoài ngành công nghiệp chế tạo, Amur còn phát triển kinh tế ở những lĩnh vực nào khác?
Decided route: documents
Query 30: Số học sinh tại các trường Cơ Đốc giáo vào những năm trước Dân Quốc là bao nhiêu?
Decided route: documents
Query 31: Có bao nhiêu phần trăm người dân nêu rằng họ có sức khoẻ tốt?
Decided route: documents
Query 32: Cá teleost và động vật lưỡng cư có đặc điểm gì giống nhau?
Decided route: documents
Query 33: Kể từ năm nào thì Cộng hòa Dân chủ Đức là cố vấn của Liên hiệp quốc?
Decided route: documents
Query 34: Rừng bao phủ bao nhiêu diện tích vườn quốc gia Killarney?
Decided route: documents
Query 35: Phải gửi bao nhiêu bộ hồ sơ đến Bộ Nông nghiệp và Phát triển nông thôn để đề nghị chấp thuận các hoạt động xây dựng, cải tạo công trình giao thông liên quan đến đê điều?
Decided route: extract_laws
Query 36: Mali tham gia giúp đỡ các xung đột ở đâu?
Decided route: documents
Query 37: Công ty chúng tôi đã được cấp giấy phép hoạt động in xuất bản phẩm. Nay chúng tôi đã làm mất giấy phép. Chúng tôi muốn hỏi quý cơ quan quản lý nhà nước về hoạt động in hồ sơ để được cấp lại giấy phép hoạt động in?
Decided route: extract_laws
Query 38: Khi nào tôi cần thực hiện thủ tục công bố lại hoạt động cảng thủy nội địa?
Decided route: extract_laws
Query 39: Nhà đầu tư ra nước ngoài trong hoạt động dầu khí có trách nhiệm thực hiện đăng ký thay đổi giao dịch ngoại hối đối với NHNN trong các trường hợp nào?
Decided route: extract_laws
Query 40: Dân số Den Haag năm 1965 khoảng bao nhiêu?
Decided route: documents
Query 41: Đạo Luật Liên hiệp từng thất bại năm nào?
Decided route: documents
Query 42: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Decided route: extract_laws
Query 43: Những đóng góp của von Neumann còn liên quan tới lĩnh vực nào?
Decided route: documents
Query 44: Dự luật Luật đi lại Tiệp Khắc được dân chúng phản hồi thế nào?
Decided route: documents
Query 45: Thương binh vi phạm pháp luật, tháng 12/2013 bị Tòa án tuyên bố phạt tù 6 năm vì tội lừa đảo, chiếm đoạt tài sản, đã chấp hành xong hình phạt tù năm 2018, có được hưởng lại chế độ thương binh không? Thủ tục như thế nào
Decided route: extract_laws
Query 46: Tên gọi Ngũ xích đạo có nghĩa là gì?
Decided route: documents
Query 47: Năm 1078, Trung Quốc sản xuất được lượng thép là bao nhiêu trên năm?
Decided route: documents
Query 48: Những người nào đã nói lên những điều tương tự như Edward Said?
Decided route: documents
Query 49: Nguồn ẩm thực Mali chủ yếu với món ăn làm từ gì?
Decided route: documents
Query 50: Căn cứ văn bản quy phạm pháp luật nào quy định việc lấy mẫu để kiểm tra muối nhập khẩu
Decided route: extract_laws
Query 51: Nhà đầu tư không phải là tổ chức tín dụng có trách nhiệm thực hiện đăng ký thay đổi giao dịch ngoại hối liên quan đến hoạt động đầu tư ra nước ngoài trong các trường hợp nào?
Decided route: extract_laws
Query 52: Chúng đã có thái độ như thế nào với những người giàu có?
Decided route: documents
Query 53: Ai có thẩm quyền giải quyết tố cáo hành vi vi phạm pháp luật trong thực hiện nhiệm vụ, công vụ của cán bộ, công chức, viên chức?
Decided route: extract_laws
Query 54: Wojtyla đã không tham gia vào những sự kháng cự chống lại ai?
Decided route: documents
Query 55: Mỗi công nhân trong ngành nào có đóng góp lớn vào GDP Mỹ?
Decided route: documents
Query 56: Sau bao nhiêu ngày chúng tôi có thể nhận được kết quả thẩm định thiết kế?
Decided route: extract_laws
Query 57: Tổ chức, doanh nghiệp vận chuyển vật liệu nổ phải đảm bảo các điều kiện gì?
Decided route: extract_laws
Query 58: Hồ sơ xin ý kiến dự án đầu tư xây dựng công trình đường ống, đường dây vượt qua luồng trên không liên quan đến đường thuỷ nội địa cần những gì?
Decided route: extract_laws
Query 59: Cá nhân phải đáp ứng điều kiện nào để được cấp chứng chỉ hành nghề đo đạc và bản đồ hạng I?
Decided route: extract_laws
Query 60: Phía Tây Nam của Đồng Tháp Mười còn có những con sông nào?
Decided route: documents
Query 61: Người khai hải quan và cơ quan Hải quan khi thực hiện tham vấn trị giá hải quan có ghi nhận lại nội dung tham vấn không?
Decided route: extract_laws
Query 62: Sau tất cả vụ kiện tụng, cựu hoa hậu Pennsylvania Sheena Monnin đã nói gì?
Decided route: documents
Query 63: Trường hợp nào phải thực hiện điều chỉnh giấy phép khai thác nước dưới đất?
Decided route: extract_laws
Query 64: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Decided route: extract_laws
Query 65: Công ty chúng tôi đã đăng ký hoạt động in, nay chúng tôi có thay đổi về người đứng đầu cơ sở in. Vậy quý cơ quan cho chúng tôi hỏi Công ty chúng tôi có cần đăng ký lại hoạt động in không?
Decided route: extract_laws
Query 66: Tổ chức hoặc cá nhân muốn cấp giấy chứng nhận đăng ký cảng hàng không thì cần nộp hồ sơ gì?
Decided route: extract_laws
Query 67: Trong giai đoạn phát triển của mình, Roma đã trở mình như thế nào?
Decided route: documents
Query 68: Thương binh vi phạm pháp luật, tháng 12/2013 bị Tòa án tuyên bố phạt tù 6 năm vì tội lừa đảo, chiếm đoạt tài sản, đã chấp hành xong hình phạt tù năm 2018, có được hưởng lại chế độ thương binh không? Thủ tục như thế nào
Decided route: extract_laws
Query 69: Ai là người có quyền tố cáo cuối cùng trong toàn án chính phủ?
Decided route: documents
Query 70: Hồ sơ xin ý kiến dự án đầu tư xây dựng công trình cầu quay, cầu cất, cầu nâng hạ, cầu phao liên quan đến đường thuỷ nội địa cần những gì?
Decided route: extract_laws
Query 71: Thời hạn tham vấn trị giá trị giá hải quan là bao nhiêu ngày?
Decided route: extract_laws
Query 72: Hoa thường được tạo ra trên cành nào của cây?
Decided route: documents
Query 73: Việc thay đổi nội dung đăng ký hoạt động của Văn phòng công chứng được chuyển nhượng cần những giấy tờ gì?
Decided route: extract_laws
Query 74: Công ty chúng tôi có nhu cầu nhập máy in laser 4 màu dùng cho văn phòng. Chúng tôi muốn hỏi máy trên làm thủ tục nhập khẩu có phải có giấy phép nhập khẩu của Bộ Thông tin và Truyền thông không?
Decided route: extract_laws
Query 75: Tính trên toàn cầu thì trong các quốc gia đông dân nhất là Việt Nam đang đứng ở vị trí thứ mấy?
Decided route: documents
Query 76: Giữa xã hội và cá nhân tồn tại một thực thể gì mà xã hội ảnh hưởng đến cá nhân thông qua đó?
Decided route: documents
Query 77: Công ty tôi muốn nộp hồ sơ để chứng nhận chất lượng an toàn kỹ thuật và bảo vệ môi trường cho kiểu loại xe ô tô . Vậy, chúng tôi muốn hỏi là kể từ khi nộp hồ sơ thì sau bao lâu công ty chúng tôi nhận được Giấy chứng nhận chất lượng?
Decided route: extract_laws
Query 78: Từ những điều gì mà khiến cho ngành hành pháp và lập pháp ngày càng suy yếu so với quyền lực của quốc hội?
Decided route: documents
Query 79: Nguồn kinh tế của Ả Rập Xê Út phụ thuộc chủ yếu vào việc khai thác loại khoáng sản nào?
Decided route: documents
Query 80: Khi có nhu cầu xác nhận việc thực hiện nghĩa vụ nộp thuế, người nộp thuế gửi văn bản đề nghị xác nhận hoàn thành nghĩa vụ nộp thuế bằng hình thức nào?
Decided route: extract_laws
Query 81: LPL là tên viết tắt của chất nào?
Decided route: documents
Query 82: Trung Hoa được Tần Thủy Hoàng thiết lập vào thời gian nào?
Decided route: documents
Query 83: Hộ kinh doanh được thăm dò khoáng sản làm vật liệu xây dựng thông thường thì phải đáp ứng điều kiện gì?
Decided route: extract_laws
Query 84: Cơ quan nào có thẩm quyền sửa đổi, bổ sung, hủy bỏ hợp đồng, giao dịch đã được chứng thực?
Decided route: extract_laws
Query 85: Cửa hàng thuốc thú y của chị C đã được kiểm tra cấp giấy chứng nhận đủ điều kiện buôn bán từ tháng 9/2018. Chị chuyển cửa hàng sang địa điểm mới từ tháng 6/2019 thì cửa hàng tại địa điểm mới có cần phải được kiểm tra và cấp giấy chứng nhận đủ điều kiện buôn bán?
Decided route: extract_laws
Query 86: Cơ quan nào thực hiện thẩm quyền chấp thuận xây dựng công trình thiết yếu trong phạm vi bảo vệ KCHT GTĐB của quốc lộ?
Decided route: extract_laws
Query 87: Tôi muốn biết những tổ chức như nào thì có quyền đăng ký nhãn hiệu chứng nhận?
Decided route: extract_laws
Query 88: Tổng chỉ tiêu UBND thành phố trình với HĐND thành phố năm 2014 là bao nhiêu chỉ tiêu về kinh tế và xã hội?
Decided route: documents
Query 89: Vật chất tạo nên bụi kim cương là gì?
Decided route: documents
Query 90: Hồ sơ mở tài khoản thanh toán tại Ngân hàng Nhà nước đối với các tổ chức tín dụng, Kho bạc Nhà nước trên địa bàn theo quyết định của Thống đốc Ngân hàng Nhà nước Việt Nam gồm những giấy tờ gì?
Decided route: extract_laws
Query 91: Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?
Decided route: extract_laws
Query 92: Trình tự thực hiện thủ tục chấp thuận thành lập chi nhánh, phòng giao dịch của ngân hàng hợp tác xã như thế nào?
Decided route: extract_laws
Query 93: Khi nào thì các sắc lệnh chuẩn bị cho việc tấn công đánh trả quân Pháp được chính quyền Việt Nam đưa ra?
Decided route: documents
Query 94: Để vừa ẩn nấp vừa dừng lại, quân Trung Quốc đã thực hiện kế sách gì?
Decided route: documents
Query 95: Để được cấp phép cho người Việt Nam định cư ở nước ngoài, tổ chức, cá nhân nước ngoài tiến hành nghiên cứu, sưu tầm di sản văn hóa phi vật thể từ hai tỉnh, thành phố trực thuộc trung ương trở lên, cần phải nộp những loại giấy tờ gì?
Decided route: extract_laws
Query 96: Tôi là chủ sở hữu của các nhãn hiệu đã được đăng ký bảo hộ tại Cục Sở hữu trí tuệ. Tôi có được cơ quan hải quan chấp nhận kiểm tra, giám sát hải quan đối với các nhãn hiệu thuộc sở hữu của tôi không?
Decided route: extract_laws
Query 97: Lần đầu tiên Pháp đăng cai tổ chức Thế vận hội là năm nào?
Decided route: documents
Query 98: Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?
Decided route: extract_laws
Query 99: Điều kiện để được cấp GCN đủ điều kiện hoạt động kiểm định được quy định tại văn bản nào?
Decided route: extract_laws
Query 100: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Decided route: extract_laws
Query 101: Đặc điểm của tia hồng ngoại khi được truyền đến khí quyển Trái Đất là gì?
Decided route: documents
Query 102: Ai là người áp dụng sự phê bình Hegel và chửi mắng người khác?
Decided route: documents
Query 103: Cộng đồng người Síp Thổ Nhĩ Kỳ phản ứng thế nào về cuộc trưng cầu dân ý do Nhà thờ Chính thống phương Đông tổ chức?
Decided route: documents
Query 104: Hồ sơ đề nghị khoanh nợ đối với trường hợp khách hàng bị thiệt hại về tài sản do thiên tai, dịch bệnh xảy ra trên phạm vi rộng bao gồm những giấy tờ gì?
Decided route: extract_laws
Query 105: Dân số ở Mĩ biến động vào thời gian nào?
Decided route: documents
Query 106: Trung Quốc đã đánh bại được Đế quốc Nhật Bản vào năm nào?
Decided route: documents
Query 107: Nhờ đâu hai mắt của tôm tít có thể hoạt động đồng bộ với nhau?
Decided route: documents
Query 108: Có bao nhiêu phần trăm người Việt ủng hộ Putin?
Decided route: documents
Query 109: Óc Eo, Việt Nam được đề xuất là một đia điểm như thế nào?
Decided route: documents
Query 110: Tên của hãng máy bay duy nhất hoạt động ở Niue?
Decided route: documents
Query 111: Mặc dù chấp nhận nhận lương nhưng cuối cùng Washington vẫn phải từ chối tiền lương vì lí do gì?
Decided route: documents
Query 112: Công ty TNHH một thành viên có thể chuyển đổi thành công ty TNHH hai thành viên trở lên do chủ sở hữu công ty sử dụng một phần vốn điều lệ để trả nợ được không?
Decided route: extract_laws
Query 113: Tôi là người lao động tự do, làm thợ lặn và muốn được nhận hỗ trợ trực tiếp chi phí huấn luyện an toàn, vệ sinh lao động cho người làm công việc có yêu cầu nghiêm ngặt về an toàn, vệ sinh lao động thì phải thực hiện những thủ tục nào và phải nộp ở đâu?
Decided route: extract_laws
Query 114: Cơ quan nào có thẩm quyền Cấp, cấp lại giấy chứng nhận cơ sở đủ điều kiện sản xuất thức ăn thủy sản, sản phẩm xử lý môi trường nuôi trồng thủy sản (trừ nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài)
Decided route: extract_laws
Query 115: Những thành tựu và phát minh nổi bật của Ai Cập cổ đại là gì?
Decided route: documents
Query 116: Richard II là con của ai?
Decided route: documents
Query 117: Đề nghị cho biết  Hồ sơ đăng ký lưu hành thuốc thú y dạng dược phẩm, hoá chất, chế phẩm sinh học được miễn khảo nghiệm gồm những loại giấy tờ gì?
Decided route: extract_laws
Query 118: Thử thách to lớn nhất của tướng George Washington là gì?
Decided route: documents
Query 119: Bài hát mà ca sĩ Emily Sande đã trình diễn trong lễ bế mạc Olympic 2012 tên là gì?
Decided route: documents
Query 120: Người được bảo vệ phải thực hiện thủ tục gì để được thay đổi, bổ sung, chấm dứt việc áp dụng biện pháp bảo vệ?
Decided route: extract_laws
Query 121: Quy định về thành phần hồ sơ đối với đề nghị điều chỉnh tên, địa chỉ của địa điểm kinh doanh mua, bán vàng miếng đã được cấp phép như thế nào?
Decided route: extract_laws
Query 122: Hồ sơ đăng ký niêm yết trái phiếu của tổ chức phát hành nước ngoài trên Sở giao dịch chứng khoán tại Việt Nam bao gồm tài liệu gì?
Decided route: documents
Query 123: Công ty của chúng  tôi được thành lập vào năm 2018. Nay chúng tôi  muốn nộp hồ sơ xin cấp lần đầu giấy chứng nhận đủ điều kiện  huấn luyện an toàn, vệ sinh lao động hạng B thì sau bao lậu chúng tôi sẽ được cấp giấy chứng nhận?
Decided route: extract_laws
Query 124: Vũ Hán bị chiếm bởi người nào?
Decided route: documents
Query 125: Đảng bộ và chính quyền Việt Nam Cộng hòa chính thức hoạt động vào thời điểm nào?
Decided route: documents
Query 126: Người tố cáo có được rút đơn tố cáo không?
Decided route: extract_laws
Query 127: Ai đã bị Gioan Phaolô II tuyệt thông vào năm 1988?
Decided route: documents
Query 128: Điều gì đã có ở các bệnh viện trước Ai Cập cổ đại vào khoảng 6000 năm TCN?
Decided route: documents
Query 129: Theo quy định tại Điều 17 Nghị định số 195/2013/NĐ-CP ngày 21/11/2013 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật Xuất bản, một trong những tiêu chuẩn về nhân lực kỹ thuật để điều hành, quản lý quá trình xuất bản xuất bản phẩm điện tử là “có phẩm chất chính trị, đạo đức tốt”. Trong hồ sơ Đề án gửi lên Cục Xuất bản, In và Phát hành, nhà xuất bản cần phải nộp tài liệu gì để chứng minh tiêu chuẩn này?
Decided route: extract_laws
Query 130: Thiên văn học từng bao gồm các ngành nào?
Decided route: documents
Query 131: Trường hợp người lao động xin không đóng bảo hiểm xã hội bắt buộc có được không?
Decided route: extract_laws
Query 132: Tôi muốn dự thi lấy giấy chứng nhận khả năng chuyên môn thuyền trưởng hạng ba thì điều kiện cần những gì?
Decided route: extract_laws
Query 133: Vì sao Alexandros được vua nước Ba Tư nể phục?
Decided route: documents
Query 134: Hãy kể tên những tính từ được phát sinh từ danh từ trong tiếng Anh?
Decided route: documents
Query 135: Hiện tượng ánh sáng xám được phát hiện lần đầu khi nào?
Decided route: documents
Query 136: Tôi muốn tìm hiểu về đối tượng được xét tặng kỷ niệm chương “Vì sự nghiệp Văn hóa, Thể thao và Du lịch”?
Decided route: documents
Query 137: Hồ sơ đề nghị cấp GCN đủ điều kiện hoạt động kiểm định được quy định tại văn bản nào?
Decided route: extract_laws
Query 138: Hồ sơ tham vấn trị giá hải quan gồm những chứng từ, tài liệu nào?
Decided route: extract_laws
Query 139: Thành phần hồ sơ khai báo kiểm dịch nhập khẩu động vật, sản phẩm động vật thủy sản để tiêu thụ trong nước bao gồm những loại giấy tờ gì?
Decided route: extract_laws
Query 140: Thế nào là từ chối nhận việc làm không có lý do chính đáng?
Decided route: extract_laws
Query 141: Thời hạn giải quyết thủ tục đăng ký khoản vay nước ngoài/khoản phát hành trái phiếu quốc tế được Chính phủ bảo lãnh mất bao nhiêu ngày?
Decided route: extract_laws
Query 142: Những loài chim nào phổ biến ở Ireland?
Decided route: documents
Query 143: Để xác định trước mã số cần chuẩn bị hồ sơ như thế nào?
Decided route: extract_laws